# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: 'Size stats'
description: 'Calculates mistica lib size overhead'
inputs:
    github-token:
        description: 'GitHub token, required to comment on PRs'
        required: true
runs:
    using: 'node12'
    main: 'main.js'
