import React from 'react';
import {Boxed} from '../boxed';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Boxed,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=2203%3A7639',
    {
        props: {
            slot: figma.boolean('Slot'),
            replaceSlot: figma.instance('Replace slot'),
            themeContext: figma.enum('Theme context', {
                Default: 'default',
                Inverse: 'inverse',
            }),
            inverse: figma.boolean('Inverse'),
        },
        example: (props) => <Boxed />,
    }
);
