import React from 'react';
import CoverHero from '../cover-hero';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    CoverHero,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=38178%3A702',
    {
        props: {
            slideshow: figma.boolean('Slideshow'),
            slideshowBullets: figma.boolean('Slideshow bullets'),
            slideshowAutoplay: figma.boolean('Slideshow autoplay'),
            themeVariant: figma.enum('Theme variant', {
                Media: 'media',
                Default: 'default',
                Inverse: 'inverse',
                Alternative: 'alternative',
            }),
            background: figma.enum('Background', {
                Image: 'image',
                Video: 'video',
                Color: 'color',
                'Custom color': 'custom-color',
            }),
            centered: figma.boolean('Centered'),
            noPaddingY: figma.boolean('NoPaddingY'),
        },
        example: (props) => <CoverHero />,
    }
);
