import React from 'react';
import LogoO2 from '../logo-o2';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    LogoO2,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=43729%3A101',
    {
        props: {
            themeContext: figma.enum('Theme context', {
                Default: 'default',
                Inverse: 'inverse',
            }),
        },
        example: (props) => <LogoO2 />,
    }
);
