root: true
extends:
    - '@telefonica/eslint-config'
plugins:
    - mistica-local-rules
overrides:
    - files:
          - '*.js'
      parser: espree
      env:
          node: true
          es2020: true
    - files:
          - '.storybook/**/*.{js,ts,tsx}'
          - 'src/__stories__/**/*.{js,ts,tsx}'
          - 'playroom/**/*.{js,ts,tsx}'
          - '**/*-test.tsx'
          - '**/*-story.tsx'
      rules:
          mistica-local-rules/use-client: 'off'
    - files:
          - '*.tsx'
      rules:
          no-restricted-imports:
              - error
              - patterns:
                    - group:
                          - '@vanilla-extract/css'
                          - '**/sprinkles.css'
                      message: This package should only be imported in css files
rules:
    import/extensions:
        - error
        - js: never
          json: always
          css: always
    mistica-local-rules/use-client: error
