const fs = require('fs');
const swcConfig = JSON.parse(fs.readFileSync(`${__dirname}/.swcrc`, 'utf-8'));
const swcTransform = ['@swc/jest', {...swcConfig, sourceMaps: 'inline'}];

/**
 * The icons live in the packages/mistica-icons workspace, and they read the theme of the root
 * package. Only the unit tests map those two names to the TypeScript sources, in
 * jest.unit.config.js. The SSR tests must not: they render the built packages, and a mix of source
 * and build creates two copies of the theme context.
 */
module.exports = {
    // Automatically restore mock state between every test
    restoreMocks: true,
    collectCoverageFrom: [
        '**/src/**/*.tsx',
        '!**/node_modules/**',
        '!**/__*__/**', // ignore tests, acceptance, stories, etc
        '!**/packages/mistica-icons/**', // autogenerated icons, in their own package
    ],
    transform: {
        '\\.css\\.ts$': ['@vanilla-extract/jest-transform', swcTransform],
        '^.+\\.(t|j)sx?$': swcTransform,
    },
    coverageReporters: ['json-summary', 'lcov'],
};
