module.exports = {
    ...require('./jest.base.config'),
    testTimeout: 40000,
    displayName: 'unit',

    /**
     * A unit test renders a component from its source, so the icons and the run-time entry point
     * must come from their sources too. One module instance of the theme context, one theme.
     * The same pairs live in tsconfig.json, .storybook/vite.config.mjs and playroom.config.js.
     */
    moduleNameMapper: {
        '^@telefonica/mistica$': '<rootDir>/src/index.tsx',
        '^@telefonica/mistica-icons/keywords$':
            '<rootDir>/packages/mistica-icons/src/generated/icons-keywords.tsx',
        '^@telefonica/mistica-icons/(icon-.*)$': '<rootDir>/packages/mistica-icons/src/generated/$1.tsx',
    },

    collectCoverage: true,
    collectCoverageFrom: [
        '**/src/**/*.[jt]s(x)?',
        '!**/node_modules/**',
        '!**/__*__/**', // ignore tests, acceptance, stories, etc
        '!**/packages/mistica-icons/**', // autogenerated icons, in their own package
        '!**/*.d.ts',
    ],

    coverageReporters: ['lcov'],
    coverageDirectory: './reports/coverage',

    testEnvironment: 'jsdom',
    testMatch: ['**/__tests__/*-test.tsx'],
    testEnvironmentOptions: {url: 'http://test.tuenti.com'},
    setupFilesAfterEnv: ['<rootDir>/setup-test-env.tsx'],
};
