// flow-typed signature: 706fb7fa78aa2c3982a360f1eb228e97
// flow-typed version: <<STUB>>/@juggle/resize-observer_v3.2.0/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@juggle/resize-observer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@juggle/resize-observer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@juggle/resize-observer/lib/algorithms/broadcastActiveObservations' {
  declare module.exports: any;
}

declare module '@juggle/resize-observer/lib/algorithms/calculateBoxSize' {
  declare module.exports: any;
}

declare module '@juggle/resize-observer/lib/algorithms/calculateDepthForNode' {
  declare module.exports: any;
}

declare module '@juggle/resize-observer/lib/algorithms/deliverResizeLoopError' {
  declare module.exports: any;
}

declare module '@juggle/resize-observer/lib/algorithms/gatherActiveObservationsAtDepth' {
  declare module.exports: any;
}

declare module '@juggle/resize-observer/lib/algorithms/hasActiveObservations' {
  declare module.exports: any;
}

declare module '@juggle/resize-observer/lib/algorithms/hasSkippedObservations' {
  declare module.exports: any;
}

declare module '@juggle/resize-observer/lib/DOMRectReadOnly' {
  declare module.exports: any;
}

declare module '@juggle/resize-observer/lib/exports/resize-observer' {
  declare module.exports: any;
}

declare module '@juggle/resize-observer/lib/exports/resize-observer.umd' {
  declare module.exports: any;
}

declare module '@juggle/resize-observer/lib/ResizeObservation' {
  declare module.exports: any;
}

declare module '@juggle/resize-observer/lib/ResizeObserver' {
  declare module.exports: any;
}

declare module '@juggle/resize-observer/lib/ResizeObserverBoxOptions' {
  declare module.exports: any;
}

declare module '@juggle/resize-observer/lib/ResizeObserverCallback' {
  declare module.exports: any;
}

declare module '@juggle/resize-observer/lib/ResizeObserverController' {
  declare module.exports: any;
}

declare module '@juggle/resize-observer/lib/ResizeObserverDetail' {
  declare module.exports: any;
}

declare module '@juggle/resize-observer/lib/ResizeObserverEntry' {
  declare module.exports: any;
}

declare module '@juggle/resize-observer/lib/ResizeObserverOptions' {
  declare module.exports: any;
}

declare module '@juggle/resize-observer/lib/ResizeObserverSize' {
  declare module.exports: any;
}

declare module '@juggle/resize-observer/lib/utils/element' {
  declare module.exports: any;
}

declare module '@juggle/resize-observer/lib/utils/global' {
  declare module.exports: any;
}

declare module '@juggle/resize-observer/lib/utils/process' {
  declare module.exports: any;
}

declare module '@juggle/resize-observer/lib/utils/queueMicroTask' {
  declare module.exports: any;
}

declare module '@juggle/resize-observer/lib/utils/queueResizeObserver' {
  declare module.exports: any;
}

declare module '@juggle/resize-observer/lib/utils/resizeObservers' {
  declare module.exports: any;
}

declare module '@juggle/resize-observer/lib/utils/scheduler' {
  declare module.exports: any;
}

// Filename aliases
declare module '@juggle/resize-observer/lib/algorithms/broadcastActiveObservations.js' {
  declare module.exports: $Exports<'@juggle/resize-observer/lib/algorithms/broadcastActiveObservations'>;
}
declare module '@juggle/resize-observer/lib/algorithms/calculateBoxSize.js' {
  declare module.exports: $Exports<'@juggle/resize-observer/lib/algorithms/calculateBoxSize'>;
}
declare module '@juggle/resize-observer/lib/algorithms/calculateDepthForNode.js' {
  declare module.exports: $Exports<'@juggle/resize-observer/lib/algorithms/calculateDepthForNode'>;
}
declare module '@juggle/resize-observer/lib/algorithms/deliverResizeLoopError.js' {
  declare module.exports: $Exports<'@juggle/resize-observer/lib/algorithms/deliverResizeLoopError'>;
}
declare module '@juggle/resize-observer/lib/algorithms/gatherActiveObservationsAtDepth.js' {
  declare module.exports: $Exports<'@juggle/resize-observer/lib/algorithms/gatherActiveObservationsAtDepth'>;
}
declare module '@juggle/resize-observer/lib/algorithms/hasActiveObservations.js' {
  declare module.exports: $Exports<'@juggle/resize-observer/lib/algorithms/hasActiveObservations'>;
}
declare module '@juggle/resize-observer/lib/algorithms/hasSkippedObservations.js' {
  declare module.exports: $Exports<'@juggle/resize-observer/lib/algorithms/hasSkippedObservations'>;
}
declare module '@juggle/resize-observer/lib/DOMRectReadOnly.js' {
  declare module.exports: $Exports<'@juggle/resize-observer/lib/DOMRectReadOnly'>;
}
declare module '@juggle/resize-observer/lib/exports/resize-observer.js' {
  declare module.exports: $Exports<'@juggle/resize-observer/lib/exports/resize-observer'>;
}
declare module '@juggle/resize-observer/lib/exports/resize-observer.umd.js' {
  declare module.exports: $Exports<'@juggle/resize-observer/lib/exports/resize-observer.umd'>;
}
declare module '@juggle/resize-observer/lib/ResizeObservation.js' {
  declare module.exports: $Exports<'@juggle/resize-observer/lib/ResizeObservation'>;
}
declare module '@juggle/resize-observer/lib/ResizeObserver.js' {
  declare module.exports: $Exports<'@juggle/resize-observer/lib/ResizeObserver'>;
}
declare module '@juggle/resize-observer/lib/ResizeObserverBoxOptions.js' {
  declare module.exports: $Exports<'@juggle/resize-observer/lib/ResizeObserverBoxOptions'>;
}
declare module '@juggle/resize-observer/lib/ResizeObserverCallback.js' {
  declare module.exports: $Exports<'@juggle/resize-observer/lib/ResizeObserverCallback'>;
}
declare module '@juggle/resize-observer/lib/ResizeObserverController.js' {
  declare module.exports: $Exports<'@juggle/resize-observer/lib/ResizeObserverController'>;
}
declare module '@juggle/resize-observer/lib/ResizeObserverDetail.js' {
  declare module.exports: $Exports<'@juggle/resize-observer/lib/ResizeObserverDetail'>;
}
declare module '@juggle/resize-observer/lib/ResizeObserverEntry.js' {
  declare module.exports: $Exports<'@juggle/resize-observer/lib/ResizeObserverEntry'>;
}
declare module '@juggle/resize-observer/lib/ResizeObserverOptions.js' {
  declare module.exports: $Exports<'@juggle/resize-observer/lib/ResizeObserverOptions'>;
}
declare module '@juggle/resize-observer/lib/ResizeObserverSize.js' {
  declare module.exports: $Exports<'@juggle/resize-observer/lib/ResizeObserverSize'>;
}
declare module '@juggle/resize-observer/lib/utils/element.js' {
  declare module.exports: $Exports<'@juggle/resize-observer/lib/utils/element'>;
}
declare module '@juggle/resize-observer/lib/utils/global.js' {
  declare module.exports: $Exports<'@juggle/resize-observer/lib/utils/global'>;
}
declare module '@juggle/resize-observer/lib/utils/process.js' {
  declare module.exports: $Exports<'@juggle/resize-observer/lib/utils/process'>;
}
declare module '@juggle/resize-observer/lib/utils/queueMicroTask.js' {
  declare module.exports: $Exports<'@juggle/resize-observer/lib/utils/queueMicroTask'>;
}
declare module '@juggle/resize-observer/lib/utils/queueResizeObserver.js' {
  declare module.exports: $Exports<'@juggle/resize-observer/lib/utils/queueResizeObserver'>;
}
declare module '@juggle/resize-observer/lib/utils/resizeObservers.js' {
  declare module.exports: $Exports<'@juggle/resize-observer/lib/utils/resizeObservers'>;
}
declare module '@juggle/resize-observer/lib/utils/scheduler.js' {
  declare module.exports: $Exports<'@juggle/resize-observer/lib/utils/scheduler'>;
}
