// Generates .design-sync/ds-entry.js — the slim bundle entry used by cfg.entry.
// Re-exports every NON-icon symbol of the package plus a curated common-icon
// allowlist, so the IIFE bundle stays under the 5 MB upload cap (the full
// 2162-icon catalogue is ~13 MB and cannot ship whole).
// Re-run after the DS adds/removes top-level exports:
//   node .design-sync/gen-entry.mjs
import {readFileSync, writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {dirname, join} from 'node:path';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const indexSrc = readFileSync(join(repoRoot, 'dist-es/index.js'), 'utf8');

const exportBlocks = [...indexSrc.matchAll(/export\s*\{([^}]*)\}/g)].map((m) => m[1]).join(',');
const names = [
    ...new Set([...exportBlocks.matchAll(/(?:[\w$]+\s+as\s+)?([A-Za-z_$][\w$]*)/g)].map((m) => m[1])),
].filter((n) => n && n !== 'default');

const isIcon = (n) => /^Icon[A-Z]/.test(n);
const nonIcon = names.filter((n) => !isIcon(n));
const icons = names.filter(isIcon);

// Curated common-UI concepts. An icon is kept when its base name (Icon + concept
// + variant) contains one of these tokens; the Regular variant is preferred.
// Exact base-name concepts confirmed present in the catalogue (common UI/UX
// icons; Telefónica-specific telecom icons are intentionally excluded).
const CONCEPTS = [
    'Close', 'Search', 'Menu', 'KebabMenu', 'Check', 'Plus', 'Minus', 'Trash', 'Delete',
    'Edit', 'EditPencil', 'EditPaper', 'Settings', 'Filter', 'Sort', 'Refresh', 'Download',
    'Upload', 'Share', 'Print', 'Copy', 'Save', 'Star', 'Heart', 'HeartBubble', 'Bookmark',
    'Flag', 'Bell', 'AlarmClock', 'Alert', 'Information', 'InformationUser', 'Question',
    'Warning', 'Help', 'Home', 'HomeWifi', 'HomeSecurity', 'User', 'Profile', 'AddUser',
    'Email', 'EmailSend', 'Phone', 'AddPhone', 'Chat', 'Message', 'Comment', 'Calendar',
    'Clock', 'Location', 'LocationMap', 'Map', 'Camera', 'Image', 'ImageOff', 'Video',
    'Play', 'Pause', 'Stop', 'Music', 'FastForward', 'Microphone', 'MicrophoneDisabled',
    'Headphones', 'Loudspeaker', 'Document', 'File', 'FileImage', 'Folder', 'Book',
    'ContactBook', 'CreditCard', 'Coins', 'Gift', 'GiftCard', 'Wallet', 'Wifi', 'Battery',
    'BatteryCharging', 'BatteryFull', 'Globe', 'Earth', 'Link', 'Grid', 'Dashboard',
    'Archive', 'BarChart', 'Barcode', 'Bug', 'Code', 'Database', 'Computer', 'Laptop',
    'Keyboard', 'Key', 'Fingerprint', 'FaceScan', 'LockClosed', 'LockOpen', 'DoorLock',
    'Car', 'Bus', 'Drink', 'Fire', 'Microscope', 'Microchip', 'Hockey', 'Airplay',
    'Trophy', 'Target', 'Scan', 'Ticket', 'Tag', 'Cloud', 'Power', 'Login', 'Logout',
    'Visibility', 'Eye',
];
// Story-referenced icons MUST ship: stories import them from the barrel and the
// preview shims those imports to the global, so a missing icon renders as
// `undefined` and throws ("Element type is invalid"), blanking the whole
// preview. Scan every story file for Icon* identifiers and keep the ones that
// are real package exports.
import {readdirSync, statSync} from 'node:fs';
const walk = (dir, acc = []) => {
    for (const f of readdirSync(dir)) {
        const p = join(dir, f);
        const st = statSync(p);
        if (st.isDirectory()) walk(p, acc);
        else if (/-story\.tsx?$/.test(f)) acc.push(p);
    }
    return acc;
};
const storyIconSet = new Set();
for (const sf of walk(join(repoRoot, 'src'))) {
    const txt = readFileSync(sf, 'utf8');
    for (const m of txt.matchAll(/\bIcon[A-Z][A-Za-z0-9]+\b/g)) {
        if (icons.includes(m[0])) storyIconSet.add(m[0]);
    }
}
const STORY_ICONS = [...storyIconSet];

const variantRank = (n) => (/Regular$/.test(n) ? 0 : /Filled$/.test(n) ? 1 : /Light$/.test(n) ? 2 : 3);
const conceptOf = (n) => n.replace(/^Icon/, '').replace(/(Regular|Filled|Light)$/, '');
// Whole icon families worth shipping in full (directional / chevrons — high
// reuse in real UIs). Matched by base-name prefix; everything else exact.
const FAMILIES = ['Arrow', 'Chevron', 'Caret'];
const matchesConcept = (n) => {
    const base = conceptOf(n);
    return CONCEPTS.includes(base) || FAMILIES.some((f) => base.startsWith(f));
};

// One variant per concept (prefer Regular), only for matched concepts.
const byConcept = new Map();
for (const n of icons.filter(matchesConcept)) {
    const key = conceptOf(n);
    const cur = byConcept.get(key);
    if (!cur || variantRank(n) < variantRank(cur)) byConcept.set(key, n);
}
const curatedIcons = new Set(byConcept.values());
for (const s of STORY_ICONS) if (icons.includes(s)) curatedIcons.add(s);

const keep = [...nonIcon, ...[...curatedIcons].sort()];
const banner = `// AUTO-GENERATED by .design-sync/gen-entry.mjs — do not edit by hand.\n// Slim bundle entry: ${nonIcon.length} non-icon exports + ${curatedIcons.size} curated icons.\n`;
const body = `export {\n${keep.map((n) => `    ${n},`).join('\n')}\n} from '../dist-es/index.js';\n`;
writeFileSync(join(repoRoot, '.design-sync/ds-entry.js'), banner + body);
console.error(`wrote .design-sync/ds-entry.js: ${keep.length} exports (${nonIcon.length} non-icon + ${curatedIcons.size} icons)`);

// Combined component CSS (used as cfg.cssEntry). dist-es/style.css carries the
// v16_67_ vanilla-extract classes that match the bundle; components use
// `font-family: inherit`, so we append a body rule applying the Movistar brand
// font (On Air, shipped via cfg.extraFonts). Regenerated here so it never rots
// against dist-es/style.css. gitignored — re-run gen-entry.mjs on re-sync.
const distCss = readFileSync(join(repoRoot, 'dist-es/style.css'), 'utf8');
const brandFontRule = `\n/* design-sync: apply the Movistar brand font (On Air) at the root; components inherit it */\nhtml, body { font-family: 'On Air', 'Helvetica Neue', Arial, sans-serif; }\n`;
writeFileSync(join(repoRoot, '.design-sync/ds-styles.css'), distCss + brandFontRule);
console.error(`wrote .design-sync/ds-styles.css: dist-es/style.css + On Air body rule`);
