// flow-typed signature: 640b59ec09def30ddfe3596aff2e9151
// flow-typed version: <<STUB>>/@telefonica/libphonenumber_v2.7.5/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@telefonica/libphonenumber'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@telefonica/libphonenumber' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@telefonica/libphonenumber/libphonenumber' {
  declare module.exports: any;
}

// Filename aliases
declare module '@telefonica/libphonenumber/libphonenumber.js' {
  declare module.exports: $Exports<'@telefonica/libphonenumber/libphonenumber'>;
}
