// flow-typed signature: 47d2cd63af2eb93d77b18c26b16bd305
// flow-typed version: <<STUB>>/jest-environment-puppeteer_v4.4.0/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-environment-puppeteer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-environment-puppeteer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-environment-puppeteer/lib/global' {
  declare module.exports: any;
}

declare module 'jest-environment-puppeteer/lib/PuppeteerEnvironment' {
  declare module.exports: any;
}

declare module 'jest-environment-puppeteer/lib/readConfig' {
  declare module.exports: any;
}

declare module 'jest-environment-puppeteer/setup' {
  declare module.exports: any;
}

declare module 'jest-environment-puppeteer/teardown' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-environment-puppeteer/index' {
  declare module.exports: $Exports<'jest-environment-puppeteer'>;
}
declare module 'jest-environment-puppeteer/index.js' {
  declare module.exports: $Exports<'jest-environment-puppeteer'>;
}
declare module 'jest-environment-puppeteer/lib/global.js' {
  declare module.exports: $Exports<'jest-environment-puppeteer/lib/global'>;
}
declare module 'jest-environment-puppeteer/lib/PuppeteerEnvironment.js' {
  declare module.exports: $Exports<'jest-environment-puppeteer/lib/PuppeteerEnvironment'>;
}
declare module 'jest-environment-puppeteer/lib/readConfig.js' {
  declare module.exports: $Exports<'jest-environment-puppeteer/lib/readConfig'>;
}
declare module 'jest-environment-puppeteer/setup.js' {
  declare module.exports: $Exports<'jest-environment-puppeteer/setup'>;
}
declare module 'jest-environment-puppeteer/teardown.js' {
  declare module.exports: $Exports<'jest-environment-puppeteer/teardown'>;
}
