// flow-typed signature: c4455b88ee924c97d9ec7e71b6d3cbe1
// flow-typed version: <<STUB>>/jss-plugin-vendor-prefixer_v10.1.1/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jss-plugin-vendor-prefixer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jss-plugin-vendor-prefixer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jss-plugin-vendor-prefixer/dist/jss-plugin-vendor-prefixer.bundle' {
  declare module.exports: any;
}

declare module 'jss-plugin-vendor-prefixer/dist/jss-plugin-vendor-prefixer.cjs' {
  declare module.exports: any;
}

declare module 'jss-plugin-vendor-prefixer/dist/jss-plugin-vendor-prefixer.esm' {
  declare module.exports: any;
}

declare module 'jss-plugin-vendor-prefixer/dist/jss-plugin-vendor-prefixer' {
  declare module.exports: any;
}

declare module 'jss-plugin-vendor-prefixer/dist/jss-plugin-vendor-prefixer.min' {
  declare module.exports: any;
}

declare module 'jss-plugin-vendor-prefixer/src' {
  declare module.exports: any;
}

declare module 'jss-plugin-vendor-prefixer/src/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jss-plugin-vendor-prefixer/dist/jss-plugin-vendor-prefixer.bundle.js' {
  declare module.exports: $Exports<'jss-plugin-vendor-prefixer/dist/jss-plugin-vendor-prefixer.bundle'>;
}
declare module 'jss-plugin-vendor-prefixer/dist/jss-plugin-vendor-prefixer.cjs.js' {
  declare module.exports: $Exports<'jss-plugin-vendor-prefixer/dist/jss-plugin-vendor-prefixer.cjs'>;
}
declare module 'jss-plugin-vendor-prefixer/dist/jss-plugin-vendor-prefixer.esm.js' {
  declare module.exports: $Exports<'jss-plugin-vendor-prefixer/dist/jss-plugin-vendor-prefixer.esm'>;
}
declare module 'jss-plugin-vendor-prefixer/dist/jss-plugin-vendor-prefixer.js' {
  declare module.exports: $Exports<'jss-plugin-vendor-prefixer/dist/jss-plugin-vendor-prefixer'>;
}
declare module 'jss-plugin-vendor-prefixer/dist/jss-plugin-vendor-prefixer.min.js' {
  declare module.exports: $Exports<'jss-plugin-vendor-prefixer/dist/jss-plugin-vendor-prefixer.min'>;
}
declare module 'jss-plugin-vendor-prefixer/src/index' {
  declare module.exports: $Exports<'jss-plugin-vendor-prefixer/src'>;
}
declare module 'jss-plugin-vendor-prefixer/src/index.js' {
  declare module.exports: $Exports<'jss-plugin-vendor-prefixer/src'>;
}
declare module 'jss-plugin-vendor-prefixer/src/index.test.js' {
  declare module.exports: $Exports<'jss-plugin-vendor-prefixer/src/index.test'>;
}
