// flow-typed signature: c8d06ef4f016262d3938c48faac3924d
// flow-typed version: <<STUB>>/jss-plugin-default-unit_v10.1.1/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jss-plugin-default-unit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jss-plugin-default-unit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jss-plugin-default-unit/dist/jss-plugin-default-unit.bundle' {
  declare module.exports: any;
}

declare module 'jss-plugin-default-unit/dist/jss-plugin-default-unit.cjs' {
  declare module.exports: any;
}

declare module 'jss-plugin-default-unit/dist/jss-plugin-default-unit.esm' {
  declare module.exports: any;
}

declare module 'jss-plugin-default-unit/dist/jss-plugin-default-unit' {
  declare module.exports: any;
}

declare module 'jss-plugin-default-unit/dist/jss-plugin-default-unit.min' {
  declare module.exports: any;
}

declare module 'jss-plugin-default-unit/src/defaultUnits' {
  declare module.exports: any;
}

declare module 'jss-plugin-default-unit/src' {
  declare module.exports: any;
}

declare module 'jss-plugin-default-unit/src/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jss-plugin-default-unit/dist/jss-plugin-default-unit.bundle.js' {
  declare module.exports: $Exports<'jss-plugin-default-unit/dist/jss-plugin-default-unit.bundle'>;
}
declare module 'jss-plugin-default-unit/dist/jss-plugin-default-unit.cjs.js' {
  declare module.exports: $Exports<'jss-plugin-default-unit/dist/jss-plugin-default-unit.cjs'>;
}
declare module 'jss-plugin-default-unit/dist/jss-plugin-default-unit.esm.js' {
  declare module.exports: $Exports<'jss-plugin-default-unit/dist/jss-plugin-default-unit.esm'>;
}
declare module 'jss-plugin-default-unit/dist/jss-plugin-default-unit.js' {
  declare module.exports: $Exports<'jss-plugin-default-unit/dist/jss-plugin-default-unit'>;
}
declare module 'jss-plugin-default-unit/dist/jss-plugin-default-unit.min.js' {
  declare module.exports: $Exports<'jss-plugin-default-unit/dist/jss-plugin-default-unit.min'>;
}
declare module 'jss-plugin-default-unit/src/defaultUnits.js' {
  declare module.exports: $Exports<'jss-plugin-default-unit/src/defaultUnits'>;
}
declare module 'jss-plugin-default-unit/src/index' {
  declare module.exports: $Exports<'jss-plugin-default-unit/src'>;
}
declare module 'jss-plugin-default-unit/src/index.js' {
  declare module.exports: $Exports<'jss-plugin-default-unit/src'>;
}
declare module 'jss-plugin-default-unit/src/index.test.js' {
  declare module.exports: $Exports<'jss-plugin-default-unit/src/index.test'>;
}
