// flow-typed signature: 6fac4259aef43b8637eb925f81f4daf0
// flow-typed version: <<STUB>>/jss-plugin-rule-value-function_v10.1.1/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jss-plugin-rule-value-function'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jss-plugin-rule-value-function' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jss-plugin-rule-value-function/dist/jss-plugin-rule-value-function.bundle' {
  declare module.exports: any;
}

declare module 'jss-plugin-rule-value-function/dist/jss-plugin-rule-value-function.cjs' {
  declare module.exports: any;
}

declare module 'jss-plugin-rule-value-function/dist/jss-plugin-rule-value-function.esm' {
  declare module.exports: any;
}

declare module 'jss-plugin-rule-value-function/dist/jss-plugin-rule-value-function' {
  declare module.exports: any;
}

declare module 'jss-plugin-rule-value-function/dist/jss-plugin-rule-value-function.min' {
  declare module.exports: any;
}

declare module 'jss-plugin-rule-value-function/src/function-rules.test' {
  declare module.exports: any;
}

declare module 'jss-plugin-rule-value-function/src/function-values.test' {
  declare module.exports: any;
}

declare module 'jss-plugin-rule-value-function/src' {
  declare module.exports: any;
}

declare module 'jss-plugin-rule-value-function/src/index.test' {
  declare module.exports: any;
}

declare module 'jss-plugin-rule-value-function/src/plugin-compose.test' {
  declare module.exports: any;
}

declare module 'jss-plugin-rule-value-function/src/plugin-expand.test' {
  declare module.exports: any;
}

declare module 'jss-plugin-rule-value-function/src/plugin-global.test' {
  declare module.exports: any;
}

declare module 'jss-plugin-rule-value-function/src/plugin-nested.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jss-plugin-rule-value-function/dist/jss-plugin-rule-value-function.bundle.js' {
  declare module.exports: $Exports<'jss-plugin-rule-value-function/dist/jss-plugin-rule-value-function.bundle'>;
}
declare module 'jss-plugin-rule-value-function/dist/jss-plugin-rule-value-function.cjs.js' {
  declare module.exports: $Exports<'jss-plugin-rule-value-function/dist/jss-plugin-rule-value-function.cjs'>;
}
declare module 'jss-plugin-rule-value-function/dist/jss-plugin-rule-value-function.esm.js' {
  declare module.exports: $Exports<'jss-plugin-rule-value-function/dist/jss-plugin-rule-value-function.esm'>;
}
declare module 'jss-plugin-rule-value-function/dist/jss-plugin-rule-value-function.js' {
  declare module.exports: $Exports<'jss-plugin-rule-value-function/dist/jss-plugin-rule-value-function'>;
}
declare module 'jss-plugin-rule-value-function/dist/jss-plugin-rule-value-function.min.js' {
  declare module.exports: $Exports<'jss-plugin-rule-value-function/dist/jss-plugin-rule-value-function.min'>;
}
declare module 'jss-plugin-rule-value-function/src/function-rules.test.js' {
  declare module.exports: $Exports<'jss-plugin-rule-value-function/src/function-rules.test'>;
}
declare module 'jss-plugin-rule-value-function/src/function-values.test.js' {
  declare module.exports: $Exports<'jss-plugin-rule-value-function/src/function-values.test'>;
}
declare module 'jss-plugin-rule-value-function/src/index' {
  declare module.exports: $Exports<'jss-plugin-rule-value-function/src'>;
}
declare module 'jss-plugin-rule-value-function/src/index.js' {
  declare module.exports: $Exports<'jss-plugin-rule-value-function/src'>;
}
declare module 'jss-plugin-rule-value-function/src/index.test.js' {
  declare module.exports: $Exports<'jss-plugin-rule-value-function/src/index.test'>;
}
declare module 'jss-plugin-rule-value-function/src/plugin-compose.test.js' {
  declare module.exports: $Exports<'jss-plugin-rule-value-function/src/plugin-compose.test'>;
}
declare module 'jss-plugin-rule-value-function/src/plugin-expand.test.js' {
  declare module.exports: $Exports<'jss-plugin-rule-value-function/src/plugin-expand.test'>;
}
declare module 'jss-plugin-rule-value-function/src/plugin-global.test.js' {
  declare module.exports: $Exports<'jss-plugin-rule-value-function/src/plugin-global.test'>;
}
declare module 'jss-plugin-rule-value-function/src/plugin-nested.test.js' {
  declare module.exports: $Exports<'jss-plugin-rule-value-function/src/plugin-nested.test'>;
}
