// flow-typed signature: a2fe3394a1fc58d1137cd1a24c1194c1
// flow-typed version: <<STUB>>/jss-plugin-nested_v10.1.1/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jss-plugin-nested'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jss-plugin-nested' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jss-plugin-nested/dist/jss-plugin-nested.bundle' {
  declare module.exports: any;
}

declare module 'jss-plugin-nested/dist/jss-plugin-nested.cjs' {
  declare module.exports: any;
}

declare module 'jss-plugin-nested/dist/jss-plugin-nested.esm' {
  declare module.exports: any;
}

declare module 'jss-plugin-nested/dist/jss-plugin-nested' {
  declare module.exports: any;
}

declare module 'jss-plugin-nested/dist/jss-plugin-nested.min' {
  declare module.exports: any;
}

declare module 'jss-plugin-nested/src' {
  declare module.exports: any;
}

declare module 'jss-plugin-nested/src/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jss-plugin-nested/dist/jss-plugin-nested.bundle.js' {
  declare module.exports: $Exports<'jss-plugin-nested/dist/jss-plugin-nested.bundle'>;
}
declare module 'jss-plugin-nested/dist/jss-plugin-nested.cjs.js' {
  declare module.exports: $Exports<'jss-plugin-nested/dist/jss-plugin-nested.cjs'>;
}
declare module 'jss-plugin-nested/dist/jss-plugin-nested.esm.js' {
  declare module.exports: $Exports<'jss-plugin-nested/dist/jss-plugin-nested.esm'>;
}
declare module 'jss-plugin-nested/dist/jss-plugin-nested.js' {
  declare module.exports: $Exports<'jss-plugin-nested/dist/jss-plugin-nested'>;
}
declare module 'jss-plugin-nested/dist/jss-plugin-nested.min.js' {
  declare module.exports: $Exports<'jss-plugin-nested/dist/jss-plugin-nested.min'>;
}
declare module 'jss-plugin-nested/src/index' {
  declare module.exports: $Exports<'jss-plugin-nested/src'>;
}
declare module 'jss-plugin-nested/src/index.js' {
  declare module.exports: $Exports<'jss-plugin-nested/src'>;
}
declare module 'jss-plugin-nested/src/index.test.js' {
  declare module.exports: $Exports<'jss-plugin-nested/src/index.test'>;
}
