// flow-typed signature: 4ca5d7c288ae0df52e0c54fe95c2fd0a
// flow-typed version: <<STUB>>/jss-plugin-camel-case_v10.1.1/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jss-plugin-camel-case'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jss-plugin-camel-case' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jss-plugin-camel-case/dist/jss-plugin-camel-case.bundle' {
  declare module.exports: any;
}

declare module 'jss-plugin-camel-case/dist/jss-plugin-camel-case.cjs' {
  declare module.exports: any;
}

declare module 'jss-plugin-camel-case/dist/jss-plugin-camel-case.esm' {
  declare module.exports: any;
}

declare module 'jss-plugin-camel-case/dist/jss-plugin-camel-case' {
  declare module.exports: any;
}

declare module 'jss-plugin-camel-case/dist/jss-plugin-camel-case.min' {
  declare module.exports: any;
}

declare module 'jss-plugin-camel-case/src' {
  declare module.exports: any;
}

declare module 'jss-plugin-camel-case/src/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jss-plugin-camel-case/dist/jss-plugin-camel-case.bundle.js' {
  declare module.exports: $Exports<'jss-plugin-camel-case/dist/jss-plugin-camel-case.bundle'>;
}
declare module 'jss-plugin-camel-case/dist/jss-plugin-camel-case.cjs.js' {
  declare module.exports: $Exports<'jss-plugin-camel-case/dist/jss-plugin-camel-case.cjs'>;
}
declare module 'jss-plugin-camel-case/dist/jss-plugin-camel-case.esm.js' {
  declare module.exports: $Exports<'jss-plugin-camel-case/dist/jss-plugin-camel-case.esm'>;
}
declare module 'jss-plugin-camel-case/dist/jss-plugin-camel-case.js' {
  declare module.exports: $Exports<'jss-plugin-camel-case/dist/jss-plugin-camel-case'>;
}
declare module 'jss-plugin-camel-case/dist/jss-plugin-camel-case.min.js' {
  declare module.exports: $Exports<'jss-plugin-camel-case/dist/jss-plugin-camel-case.min'>;
}
declare module 'jss-plugin-camel-case/src/index' {
  declare module.exports: $Exports<'jss-plugin-camel-case/src'>;
}
declare module 'jss-plugin-camel-case/src/index.js' {
  declare module.exports: $Exports<'jss-plugin-camel-case/src'>;
}
declare module 'jss-plugin-camel-case/src/index.test.js' {
  declare module.exports: $Exports<'jss-plugin-camel-case/src/index.test'>;
}
