// flow-typed signature: 5a186eac2e0a5da749a8c8649d551142
// flow-typed version: <<STUB>>/jss_v10.1.1/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jss/dist/jss.bundle' {
  declare module.exports: any;
}

declare module 'jss/dist/jss.cjs' {
  declare module.exports: any;
}

declare module 'jss/dist/jss.esm' {
  declare module.exports: any;
}

declare module 'jss/dist/jss' {
  declare module.exports: any;
}

declare module 'jss/dist/jss.min' {
  declare module.exports: any;
}

declare module 'jss/src/DomRenderer' {
  declare module.exports: any;
}

declare module 'jss/src' {
  declare module.exports: any;
}

declare module 'jss/src/Jss' {
  declare module.exports: any;
}

declare module 'jss/src/plugins/conditionalRule' {
  declare module.exports: any;
}

declare module 'jss/src/plugins/fontFaceRule' {
  declare module.exports: any;
}

declare module 'jss/src/plugins' {
  declare module.exports: any;
}

declare module 'jss/src/plugins/keyframeRule' {
  declare module.exports: any;
}

declare module 'jss/src/plugins/keyframesRule' {
  declare module.exports: any;
}

declare module 'jss/src/plugins/simpleRule' {
  declare module.exports: any;
}

declare module 'jss/src/plugins/styleRule' {
  declare module.exports: any;
}

declare module 'jss/src/plugins/viewportRule' {
  declare module.exports: any;
}

declare module 'jss/src/PluginsRegistry' {
  declare module.exports: any;
}

declare module 'jss/src/RuleList' {
  declare module.exports: any;
}

declare module 'jss/src/sheets' {
  declare module.exports: any;
}

declare module 'jss/src/SheetsManager' {
  declare module.exports: any;
}

declare module 'jss/src/SheetsRegistry' {
  declare module.exports: any;
}

declare module 'jss/src/StyleSheet' {
  declare module.exports: any;
}

declare module 'jss/src/types/cssom' {
  declare module.exports: any;
}

declare module 'jss/src/types/dom' {
  declare module.exports: any;
}

declare module 'jss/src/types' {
  declare module.exports: any;
}

declare module 'jss/src/types/jss' {
  declare module.exports: any;
}

declare module 'jss/src/utils/cloneStyle' {
  declare module.exports: any;
}

declare module 'jss/src/utils/createGenerateId' {
  declare module.exports: any;
}

declare module 'jss/src/utils/createRule' {
  declare module.exports: any;
}

declare module 'jss/src/utils/escape' {
  declare module.exports: any;
}

declare module 'jss/src/utils/getDynamicStyles' {
  declare module.exports: any;
}

declare module 'jss/src/utils/globalThis' {
  declare module.exports: any;
}

declare module 'jss/src/utils/moduleId' {
  declare module.exports: any;
}

declare module 'jss/src/utils/toCss' {
  declare module.exports: any;
}

declare module 'jss/src/utils/toCssValue' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jss/dist/jss.bundle.js' {
  declare module.exports: $Exports<'jss/dist/jss.bundle'>;
}
declare module 'jss/dist/jss.cjs.js' {
  declare module.exports: $Exports<'jss/dist/jss.cjs'>;
}
declare module 'jss/dist/jss.esm.js' {
  declare module.exports: $Exports<'jss/dist/jss.esm'>;
}
declare module 'jss/dist/jss.js' {
  declare module.exports: $Exports<'jss/dist/jss'>;
}
declare module 'jss/dist/jss.min.js' {
  declare module.exports: $Exports<'jss/dist/jss.min'>;
}
declare module 'jss/src/DomRenderer.js' {
  declare module.exports: $Exports<'jss/src/DomRenderer'>;
}
declare module 'jss/src/index' {
  declare module.exports: $Exports<'jss/src'>;
}
declare module 'jss/src/index.js' {
  declare module.exports: $Exports<'jss/src'>;
}
declare module 'jss/src/Jss.js' {
  declare module.exports: $Exports<'jss/src/Jss'>;
}
declare module 'jss/src/plugins/conditionalRule.js' {
  declare module.exports: $Exports<'jss/src/plugins/conditionalRule'>;
}
declare module 'jss/src/plugins/fontFaceRule.js' {
  declare module.exports: $Exports<'jss/src/plugins/fontFaceRule'>;
}
declare module 'jss/src/plugins/index' {
  declare module.exports: $Exports<'jss/src/plugins'>;
}
declare module 'jss/src/plugins/index.js' {
  declare module.exports: $Exports<'jss/src/plugins'>;
}
declare module 'jss/src/plugins/keyframeRule.js' {
  declare module.exports: $Exports<'jss/src/plugins/keyframeRule'>;
}
declare module 'jss/src/plugins/keyframesRule.js' {
  declare module.exports: $Exports<'jss/src/plugins/keyframesRule'>;
}
declare module 'jss/src/plugins/simpleRule.js' {
  declare module.exports: $Exports<'jss/src/plugins/simpleRule'>;
}
declare module 'jss/src/plugins/styleRule.js' {
  declare module.exports: $Exports<'jss/src/plugins/styleRule'>;
}
declare module 'jss/src/plugins/viewportRule.js' {
  declare module.exports: $Exports<'jss/src/plugins/viewportRule'>;
}
declare module 'jss/src/PluginsRegistry.js' {
  declare module.exports: $Exports<'jss/src/PluginsRegistry'>;
}
declare module 'jss/src/RuleList.js' {
  declare module.exports: $Exports<'jss/src/RuleList'>;
}
declare module 'jss/src/sheets.js' {
  declare module.exports: $Exports<'jss/src/sheets'>;
}
declare module 'jss/src/SheetsManager.js' {
  declare module.exports: $Exports<'jss/src/SheetsManager'>;
}
declare module 'jss/src/SheetsRegistry.js' {
  declare module.exports: $Exports<'jss/src/SheetsRegistry'>;
}
declare module 'jss/src/StyleSheet.js' {
  declare module.exports: $Exports<'jss/src/StyleSheet'>;
}
declare module 'jss/src/types/cssom.js' {
  declare module.exports: $Exports<'jss/src/types/cssom'>;
}
declare module 'jss/src/types/dom.js' {
  declare module.exports: $Exports<'jss/src/types/dom'>;
}
declare module 'jss/src/types/index' {
  declare module.exports: $Exports<'jss/src/types'>;
}
declare module 'jss/src/types/index.js' {
  declare module.exports: $Exports<'jss/src/types'>;
}
declare module 'jss/src/types/jss.js' {
  declare module.exports: $Exports<'jss/src/types/jss'>;
}
declare module 'jss/src/utils/cloneStyle.js' {
  declare module.exports: $Exports<'jss/src/utils/cloneStyle'>;
}
declare module 'jss/src/utils/createGenerateId.js' {
  declare module.exports: $Exports<'jss/src/utils/createGenerateId'>;
}
declare module 'jss/src/utils/createRule.js' {
  declare module.exports: $Exports<'jss/src/utils/createRule'>;
}
declare module 'jss/src/utils/escape.js' {
  declare module.exports: $Exports<'jss/src/utils/escape'>;
}
declare module 'jss/src/utils/getDynamicStyles.js' {
  declare module.exports: $Exports<'jss/src/utils/getDynamicStyles'>;
}
declare module 'jss/src/utils/globalThis.js' {
  declare module.exports: $Exports<'jss/src/utils/globalThis'>;
}
declare module 'jss/src/utils/moduleId.js' {
  declare module.exports: $Exports<'jss/src/utils/moduleId'>;
}
declare module 'jss/src/utils/toCss.js' {
  declare module.exports: $Exports<'jss/src/utils/toCss'>;
}
declare module 'jss/src/utils/toCssValue.js' {
  declare module.exports: $Exports<'jss/src/utils/toCssValue'>;
}
