// flow-typed signature: cedd783847fb09e94b5db5ed84a300e0
// flow-typed version: <<STUB>>/node-fetch_v2.6.0/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-fetch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-fetch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-fetch/browser' {
  declare module.exports: any;
}

declare module 'node-fetch/lib/index.es' {
  declare module.exports: any;
}

declare module 'node-fetch/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-fetch/browser.js' {
  declare module.exports: $Exports<'node-fetch/browser'>;
}
declare module 'node-fetch/lib/index.es.js' {
  declare module.exports: $Exports<'node-fetch/lib/index.es'>;
}
declare module 'node-fetch/lib/index' {
  declare module.exports: $Exports<'node-fetch/lib'>;
}
declare module 'node-fetch/lib/index.js' {
  declare module.exports: $Exports<'node-fetch/lib'>;
}
