// flow-typed signature: 5ac888a221f01c3dc593f513fdb73059
// flow-typed version: <<STUB>>/pptr-testing-library_v0.6.0/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pptr-testing-library'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pptr-testing-library' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pptr-testing-library/dist/extend' {
  declare module.exports: any;
}

declare module 'pptr-testing-library/dist' {
  declare module.exports: any;
}

declare module 'pptr-testing-library/dist/typedefs' {
  declare module.exports: any;
}

declare module 'pptr-testing-library/dom-testing-library' {
  declare module.exports: any;
}

declare module 'pptr-testing-library/extend' {
  declare module.exports: any;
}

declare module 'pptr-testing-library/jest.config' {
  declare module.exports: any;
}

declare module 'pptr-testing-library/rollup.config' {
  declare module.exports: any;
}

declare module 'pptr-testing-library/rollup.input' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pptr-testing-library/dist/extend.js' {
  declare module.exports: $Exports<'pptr-testing-library/dist/extend'>;
}
declare module 'pptr-testing-library/dist/index' {
  declare module.exports: $Exports<'pptr-testing-library/dist'>;
}
declare module 'pptr-testing-library/dist/index.js' {
  declare module.exports: $Exports<'pptr-testing-library/dist'>;
}
declare module 'pptr-testing-library/dist/typedefs.js' {
  declare module.exports: $Exports<'pptr-testing-library/dist/typedefs'>;
}
declare module 'pptr-testing-library/dom-testing-library.js' {
  declare module.exports: $Exports<'pptr-testing-library/dom-testing-library'>;
}
declare module 'pptr-testing-library/extend.js' {
  declare module.exports: $Exports<'pptr-testing-library/extend'>;
}
declare module 'pptr-testing-library/jest.config.js' {
  declare module.exports: $Exports<'pptr-testing-library/jest.config'>;
}
declare module 'pptr-testing-library/rollup.config.js' {
  declare module.exports: $Exports<'pptr-testing-library/rollup.config'>;
}
declare module 'pptr-testing-library/rollup.input.js' {
  declare module.exports: $Exports<'pptr-testing-library/rollup.input'>;
}
