// flow-typed signature: b008254784f9edc3cc84767b2463e715
// flow-typed version: <<STUB>>/react-jss_v10.1.1/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-jss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-jss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-jss/dist/react-jss.bundle' {
  declare module.exports: any;
}

declare module 'react-jss/dist/react-jss.cjs' {
  declare module.exports: any;
}

declare module 'react-jss/dist/react-jss.esm' {
  declare module.exports: any;
}

declare module 'react-jss/dist/react-jss' {
  declare module.exports: any;
}

declare module 'react-jss/dist/react-jss.min' {
  declare module.exports: any;
}

declare module 'react-jss/src/createUseStyles' {
  declare module.exports: any;
}

declare module 'react-jss/src/createUseStyles.test' {
  declare module.exports: any;
}

declare module 'react-jss/src/getDisplayName' {
  declare module.exports: any;
}

declare module 'react-jss/src' {
  declare module.exports: any;
}

declare module 'react-jss/src/index.test' {
  declare module.exports: any;
}

declare module 'react-jss/src/jss' {
  declare module.exports: any;
}

declare module 'react-jss/src/JssContext' {
  declare module.exports: any;
}

declare module 'react-jss/src/JssProvider' {
  declare module.exports: any;
}

declare module 'react-jss/src/JssProvider.test' {
  declare module.exports: any;
}

declare module 'react-jss/src/jsx' {
  declare module.exports: any;
}

declare module 'react-jss/src/jsx.test' {
  declare module.exports: any;
}

declare module 'react-jss/src/styled-props-filter.test' {
  declare module.exports: any;
}

declare module 'react-jss/src/styled' {
  declare module.exports: any;
}

declare module 'react-jss/src/styled.test' {
  declare module.exports: any;
}

declare module 'react-jss/src/types' {
  declare module.exports: any;
}

declare module 'react-jss/src/utils/getSheetClasses' {
  declare module.exports: any;
}

declare module 'react-jss/src/utils/getSheetIndex' {
  declare module.exports: any;
}

declare module 'react-jss/src/utils/managers' {
  declare module.exports: any;
}

declare module 'react-jss/src/utils/memoizeOne' {
  declare module.exports: any;
}

declare module 'react-jss/src/utils/mergeClasses' {
  declare module.exports: any;
}

declare module 'react-jss/src/utils/mergeClasses.test' {
  declare module.exports: any;
}

declare module 'react-jss/src/utils/sheets' {
  declare module.exports: any;
}

declare module 'react-jss/src/utils/sheetsMeta' {
  declare module.exports: any;
}

declare module 'react-jss/src/withStyles' {
  declare module.exports: any;
}

declare module 'react-jss/src/withStyles.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-jss/dist/react-jss.bundle.js' {
  declare module.exports: $Exports<'react-jss/dist/react-jss.bundle'>;
}
declare module 'react-jss/dist/react-jss.cjs.js' {
  declare module.exports: $Exports<'react-jss/dist/react-jss.cjs'>;
}
declare module 'react-jss/dist/react-jss.esm.js' {
  declare module.exports: $Exports<'react-jss/dist/react-jss.esm'>;
}
declare module 'react-jss/dist/react-jss.js' {
  declare module.exports: $Exports<'react-jss/dist/react-jss'>;
}
declare module 'react-jss/dist/react-jss.min.js' {
  declare module.exports: $Exports<'react-jss/dist/react-jss.min'>;
}
declare module 'react-jss/src/createUseStyles.js' {
  declare module.exports: $Exports<'react-jss/src/createUseStyles'>;
}
declare module 'react-jss/src/createUseStyles.test.js' {
  declare module.exports: $Exports<'react-jss/src/createUseStyles.test'>;
}
declare module 'react-jss/src/getDisplayName.js' {
  declare module.exports: $Exports<'react-jss/src/getDisplayName'>;
}
declare module 'react-jss/src/index' {
  declare module.exports: $Exports<'react-jss/src'>;
}
declare module 'react-jss/src/index.js' {
  declare module.exports: $Exports<'react-jss/src'>;
}
declare module 'react-jss/src/index.test.js' {
  declare module.exports: $Exports<'react-jss/src/index.test'>;
}
declare module 'react-jss/src/jss.js' {
  declare module.exports: $Exports<'react-jss/src/jss'>;
}
declare module 'react-jss/src/JssContext.js' {
  declare module.exports: $Exports<'react-jss/src/JssContext'>;
}
declare module 'react-jss/src/JssProvider.js' {
  declare module.exports: $Exports<'react-jss/src/JssProvider'>;
}
declare module 'react-jss/src/JssProvider.test.js' {
  declare module.exports: $Exports<'react-jss/src/JssProvider.test'>;
}
declare module 'react-jss/src/jsx.js' {
  declare module.exports: $Exports<'react-jss/src/jsx'>;
}
declare module 'react-jss/src/jsx.test.js' {
  declare module.exports: $Exports<'react-jss/src/jsx.test'>;
}
declare module 'react-jss/src/styled-props-filter.test.js' {
  declare module.exports: $Exports<'react-jss/src/styled-props-filter.test'>;
}
declare module 'react-jss/src/styled.js' {
  declare module.exports: $Exports<'react-jss/src/styled'>;
}
declare module 'react-jss/src/styled.test.js' {
  declare module.exports: $Exports<'react-jss/src/styled.test'>;
}
declare module 'react-jss/src/types.js' {
  declare module.exports: $Exports<'react-jss/src/types'>;
}
declare module 'react-jss/src/utils/getSheetClasses.js' {
  declare module.exports: $Exports<'react-jss/src/utils/getSheetClasses'>;
}
declare module 'react-jss/src/utils/getSheetIndex.js' {
  declare module.exports: $Exports<'react-jss/src/utils/getSheetIndex'>;
}
declare module 'react-jss/src/utils/managers.js' {
  declare module.exports: $Exports<'react-jss/src/utils/managers'>;
}
declare module 'react-jss/src/utils/memoizeOne.js' {
  declare module.exports: $Exports<'react-jss/src/utils/memoizeOne'>;
}
declare module 'react-jss/src/utils/mergeClasses.js' {
  declare module.exports: $Exports<'react-jss/src/utils/mergeClasses'>;
}
declare module 'react-jss/src/utils/mergeClasses.test.js' {
  declare module.exports: $Exports<'react-jss/src/utils/mergeClasses.test'>;
}
declare module 'react-jss/src/utils/sheets.js' {
  declare module.exports: $Exports<'react-jss/src/utils/sheets'>;
}
declare module 'react-jss/src/utils/sheetsMeta.js' {
  declare module.exports: $Exports<'react-jss/src/utils/sheetsMeta'>;
}
declare module 'react-jss/src/withStyles.js' {
  declare module.exports: $Exports<'react-jss/src/withStyles'>;
}
declare module 'react-jss/src/withStyles.test.js' {
  declare module.exports: $Exports<'react-jss/src/withStyles.test'>;
}
