// flow-typed signature: 141910814a860fb9cbe152944911a681
// flow-typed version: <<STUB>>/semver-compare_v1.0.0/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'semver-compare'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'semver-compare' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'semver-compare/example/cmp' {
  declare module.exports: any;
}

declare module 'semver-compare/example/lex' {
  declare module.exports: any;
}

declare module 'semver-compare/test/cmp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'semver-compare/example/cmp.js' {
  declare module.exports: $Exports<'semver-compare/example/cmp'>;
}
declare module 'semver-compare/example/lex.js' {
  declare module.exports: $Exports<'semver-compare/example/lex'>;
}
declare module 'semver-compare/index' {
  declare module.exports: $Exports<'semver-compare'>;
}
declare module 'semver-compare/index.js' {
  declare module.exports: $Exports<'semver-compare'>;
}
declare module 'semver-compare/test/cmp.js' {
  declare module.exports: $Exports<'semver-compare/test/cmp'>;
}
