import fs from 'fs';
import path from 'path';
// eslint-disable-next-line import/extensions
import {generateSkinCssSrc, buildRadius, generateCommonCssSrc} from './css-generator.js';
import prettier from 'prettier';

/*
By default, this script will look for the design tokens inside .github folder but you may want to clone the mistica-design repo elsewhere.

To run this script locally using a custom path for the tokens, you can do the following:

1. Clone this repo:
    https://github.com/Telefonica/mistica-design

2. Run:
    DESIGN_TOKENS_FOLDER="/path/to/mistica-design/tokens" node index.js
*/

const DESIGN_TOKENS_FOLDER =
    process.env.DESIGN_TOKENS_FOLDER ||
    path.join(import.meta.dirname, '../../.github/mistica-design/tokens/');

console.log('Using design tokens from:', DESIGN_TOKENS_FOLDER);

const SKINS_FOLDER = path.join(import.meta.dirname, '..', '..', 'src', 'skins');
const CSS_FOLDER = path.join(import.meta.dirname, '..', '..', 'css');
const COMMUNITY_SKINS_FOLDER = path.join(import.meta.dirname, '..', '..', 'src', 'community', 'skins');
const COMMUNITY_CSS_FOLDER = path.join(import.meta.dirname, '..', '..', 'css', 'community');

const OFFICIAL_SKINS = ['blau', 'movistar', 'o2', 'telefonica', 'vivo', 'vivo-evolution', 'esimflag'];
const COMMUNITY_SKINS = ['cyber'];

const GENERATED_BANNER = `/**
 * @generated
 * This file was automatically generated by the generate-design-tokens script.
 * Do not edit it by hand: your changes will be overwritten the next time the script runs.
 */
`;

const capitalize = (str) => str.charAt(0).toUpperCase() + str.slice(1);
const toCamelCase = (str) => str.replace(/-([a-z])/g, (g) => g[1].toUpperCase());
const toPascalCase = (str) => capitalize(toCamelCase(str));

const jsonSort = (obj) => {
    if (Array.isArray(obj)) {
        return obj.map(jsonSort);
    }

    if (typeof obj !== 'object' || obj === null) {
        return obj;
    }

    return Object.keys(obj)
        .sort((a, b) => a.localeCompare(b, undefined, {numeric: true, sensitivity: 'base'}))
        .reduce((acc, key) => {
            acc[key] = jsonSort(obj[key]);
            return acc;
        }, {});
};

/**
 * @param {{angle: number, colors: Array<{
 *     value: string,
 *     stop: number, // value from 0 to 1
 * }>}} gradientDescription
 * @returns {string}
 */
const buildGradient = (gradientDescription) => {
    const stops = gradientDescription.colors.map((color) => {
        // eslint-disable-next-line no-use-before-define
        const formattedColor = '${' + buildColor(color) + '}';
        return `${formattedColor} ${color.stop * 100}%`;
    });
    return '`' + `linear-gradient(${gradientDescription.angle}deg, ${stops.join(', ')})` + '`';
};

const buildColor = (colorDescription) => {
    if (colorDescription.type === 'linear-gradient') {
        return buildGradient(colorDescription.value);
    }

    if (typeof colorDescription.value !== 'string') {
        console.error('Unexpected color description:', JSON.stringify(colorDescription, null, 2));
        process.exit(1);
    }

    if (colorDescription.value.startsWith('{') && colorDescription.value.endsWith('}')) {
        return colorDescription.value.replace('{', '').replace('}', '');
    }

    // https://regexper.com/#%2Frgba%5C%28%5C%7B%28.%2B%29%5C%7D%2C%20%28%5B01%5D%28%3F%3A%5C.%5Cd%2B%29%3F%29%5C%29%2F
    const colorWithAlphaRegExp = /rgba\(\{(.+)\}, ([01](?:\.\d+)?)\)/;
    const colorWithAlphaMatches = colorDescription.value.match(colorWithAlphaRegExp);

    if (colorWithAlphaMatches) {
        const colorName = colorWithAlphaMatches[1];
        const alpha = colorWithAlphaMatches[2];
        return `applyAlpha(${colorName}, ${alpha})`;
    }

    throw new Error(`Unknown color format: ${colorDescription.value}`);
};

/**
 * @param {string} skinName
 * @param {SkinFamily} family
 */
const generateSkinSrc = (skinName, family) => {
    const designTokensFile = fs.readFileSync(path.join(family.tokensFolder, `${skinName}.json`), 'utf8');
    const needsApplyAlphaImport = designTokensFile.includes('rgba');
    const designTokens = JSON.parse(designTokensFile);
    const skinConstantName = `${skinName.toUpperCase().replace(/-/g, '_')}_SKIN`;

    const textTokens = {};
    Object.entries(designTokens.text).forEach(([textAttribute, textAttributeConfig]) => {
        Object.entries(textAttributeConfig).forEach(([textPresetName, {value}]) => {
            if (!textTokens[textPresetName]) {
                textTokens[textPresetName] = {};
            }
            textTokens[textPresetName][textAttribute] = value;
        });
    });

    const {
        constantsImport,
        skinTypeImport,
        skinConstantDeclaration,
        skinType,
        functionSignature,
        applyAlphaImportPath,
    } = family.skinModule(skinName, skinConstantName);

    return `

${constantsImport}${needsApplyAlphaImport ? `import {applyAlpha} from '${applyAlphaImportPath}';\n` : ''}
${skinTypeImport}

${skinConstantDeclaration}export const palette = {
    ${Object.entries(designTokens.global.palette)
        .map(([colorName, colorDescription]) => `'${colorName}':'${colorDescription.value}'`)
        .join(',')}
};

${functionSignature}
    const skin: ${skinType} = {
        name: ${skinConstantName},
        colors: {
            ${Object.entries(designTokens.light)
                .map(([colorName, colorDescription]) => `'${colorName}': ${buildColor(colorDescription)}`)
                .join(',')}
        },
        darkModeColors: {
            ${Object.entries(designTokens.dark)
                .map(([colorName, colorDescription]) => `'${colorName}': ${buildColor(colorDescription)}`)
                .join(',')}
        },
        borderRadii: {
            ${Object.entries(designTokens.radius)
                .map(
                    ([radiusName, radiusDescription]) =>
                        `'${radiusName}': '${buildRadius(radiusDescription)}'`
                )
                .join(',')}
        },
        textPresets: ${JSON.stringify(jsonSort(textTokens))},
        themeVariants: {
            ${Object.entries(designTokens.themeVariant)
                .map(
                    ([componentName, variantDescription]) =>
                        `'${componentName}': '${variantDescription.value}'`
                )
                .join(',')},
        },
        spacing: ${JSON.stringify(
            Object.fromEntries(Object.entries(designTokens.spacing).map(([name, {value}]) => [name, value]))
        )},
    };
    return skin;
};
`;
};

const generateColorTypesSrc = (skinName, tokensFolder) => {
    const designTokensFile = fs.readFileSync(path.join(tokensFolder, `${skinName}.json`), 'utf8');
    const designTokens = JSON.parse(designTokensFile);

    return `
export type Colors = {
    ${Object.keys(designTokens.light)
        .map((colorName) => `'${colorName}': string`)
        .join(';')}
};`;
};

const formatCss = async (source) =>
    prettier.format(`${GENERATED_BANNER}\n${source}`, {
        ...(await prettier.resolveConfig('.')),
        parser: 'css',
    });

const formatTs = async (source) =>
    prettier.format(`${GENERATED_BANNER}\n${source}`, {
        ...(await prettier.resolveConfig('.')),
        parser: 'typescript',
    });

/**
 * The variant-specific parts of a generated skin module: its imports, the exported skin type,
 * the optional skin-name constant declaration, and the generated function signature.
 *
 * @typedef {{
 *     constantsImport: string,
 *     skinTypeImport: string,
 *     skinConstantDeclaration: string,
 *     skinType: string,
 *     functionSignature: string,
 *     applyAlphaImportPath: string,
 * }} SkinModule
 */

/**
 * A skin family describes where its tokens live, where the generated files go, how each skin
 * module is shaped, and which skins it contains. Known and community skins share the same
 * generation pipeline and differ only in this descriptor.
 *
 * @typedef {{
 *     tokensFolder: string,
 *     skinsFolder: string,
 *     cssFolder: string,
 *     skins: Array<string>,
 *     skinFileName: (skinName: string) => string,
 *     skinModule: (skinName: string, skinConstantName: string) => SkinModule,
 *     generateSharedFiles?: (skinNames: Array<string>) => Promise<void>,
 * }} SkinFamily
 */

/**
 * Returns the family's skins whose token file exists, logging an error for any that are missing.
 *
 * @param {SkinFamily} family
 * @returns {Array<string>}
 */
const listExistingSkins = (family) =>
    family.skins.filter((skinName) => {
        const exists = fs.existsSync(path.join(family.tokensFolder, `${skinName}.json`));
        if (!exists) {
            console.error(`Missing ${skinName}.json file`);
        }
        return exists;
    });

/** @type {SkinFamily} */
const OFFICIAL_SKINS_FAMILY = {
    tokensFolder: DESIGN_TOKENS_FOLDER,
    skinsFolder: SKINS_FOLDER,
    cssFolder: CSS_FOLDER,
    skins: OFFICIAL_SKINS,
    skinFileName: (skinName) => `${skinName}.tsx`,
    skinModule: (skinName, skinConstantName) => ({
        constantsImport: `import {${skinConstantName}} from './constants';\n`,
        skinTypeImport: `import type {GetKnownSkin, KnownSkin} from './types';`,
        skinConstantDeclaration: '',
        skinType: 'KnownSkin',
        functionSignature: `export const get${toPascalCase(skinName)}Skin: GetKnownSkin = () => {`,
        applyAlphaImportPath: '../utils/color',
    }),
    async generateSharedFiles(skinNames) {
        const [referenceSkin] = skinNames;
        if (!referenceSkin) {
            return;
        }

        const typesSrc = await formatTs(generateColorTypesSrc(referenceSkin, this.tokensFolder));
        fs.writeFileSync(path.join(this.skinsFolder, 'types', 'colors.tsx'), typesSrc);

        const commonCssSrc = await formatCss(generateCommonCssSrc(this.tokensFolder));
        fs.writeFileSync(path.join(this.cssFolder, 'mistica-common.css'), commonCssSrc);
    },
};

/** @type {SkinFamily} */
const COMMUNITY_SKINS_FAMILY = {
    tokensFolder: path.join(DESIGN_TOKENS_FOLDER, 'community'),
    skinsFolder: COMMUNITY_SKINS_FOLDER,
    cssFolder: COMMUNITY_CSS_FOLDER,
    skins: COMMUNITY_SKINS,
    skinFileName: (skinName) => `${skinName}-skin.tsx`,
    skinModule: (skinName, skinConstantName) => ({
        constantsImport: '',
        skinTypeImport: `import type {Skin} from '../../skins/types';`,
        skinConstantDeclaration: `export const ${skinConstantName} = '${toPascalCase(skinName)}';\n\n`,
        skinType: 'Skin',
        functionSignature: `export const get${toPascalCase(skinName)}Skin = (): Skin => {`,
        applyAlphaImportPath: '../../utils/color',
    }),
};

/** @param {SkinFamily} family */
const generateSkinFamily = async (family) => {
    const skinNames = listExistingSkins(family);
    if (skinNames.length === 0) {
        return;
    }

    fs.mkdirSync(family.skinsFolder, {recursive: true});
    fs.mkdirSync(family.cssFolder, {recursive: true});

    for (const skinName of skinNames) {
        console.log('Generating tokens for skin', skinName);

        const skinSrc = await formatTs(generateSkinSrc(skinName, family));
        fs.writeFileSync(path.join(family.skinsFolder, family.skinFileName(skinName)), skinSrc);

        const skinCssSrc = await formatCss(generateSkinCssSrc(skinName, family.tokensFolder));
        fs.writeFileSync(path.join(family.cssFolder, `${skinName}.css`), skinCssSrc);
    }

    await family.generateSharedFiles?.(skinNames);
};

const main = async () => {
    await generateSkinFamily(OFFICIAL_SKINS_FAMILY);
    await generateSkinFamily(COMMUNITY_SKINS_FAMILY);
};

main();
