# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: 'Audit accessibility'
description: 'This action runs `axe` over Storybook pages'
inputs:
    github-token:
        description: 'GitHub token, required to comment on PRs'
        required: true
    azure-account-name:
        description: 'Azure Account Name'
        required: true
    azure-account-key:
        description: 'Azure Account Key'
        required: true
    fork-pr:
        description: 'Set to true when running on a fork PR to skip Azure upload and PR comment'
        required: false
        default: 'false'
runs:
    using: 'node16'
    main: 'main.js'
