import {BLAU_SKIN} from './constants';
import {applyAlpha} from '../utils/color';

import type {GetKnownSkin, KnownSkin} from './types';

export const palette = {
    blauBluePrimary: '#00B6F1',
    blauBluePrimary50: '#E9F8FE',
    blauBluePrimary100: '#BCEAFA',
    blauBluePrimary200: '#78D4F5',
    blauBlueSecondary: '#0072BC',
    blauBlueSecondary100: '#E8F1F9',
    blauBlueSecondary200: '#B8D6EA',
    blauBlueSecondary300: '#91C2E2',
    blauBlueSecondary700: '#0062A2',
    blauPurple: '#7814B3',
    blauPurple100: '#F3EBF8',
    blauPurple400: '#C193DC',
    blauYellow: '#FFA922',
    blauYellow100: '#FFF9F0',
    blauYellow200: '#FFCC7C',
    blauYellow400: '#E0941E',
    blauYellow600: '#9C6715',
    blauGreen: '#29BF12',
    blauGreen50: '#F5FCF4',
    blauGreen200: '#A5E49C',
    blauGreen600: '#1C840C',
    blauRed: '#F64420',
    blauRed100: '#FEE9E5',
    blauRed200: '#FCC8BE',
    blauRed300: '#FBA796',
    blauRed400: '#F9826A',
    blauRed700: '#AF3017',
    grey1: '#F2F2F2',
    grey2: '#E6E6E6',
    grey3: '#B3B3B3',
    grey4: '#A4A4A4',
    grey5: '#8B8B8B',
    grey6: '#666666',
    white: '#FFFFFF',
    black: '#000000',
    darkModeBlack: '#191919',
    darkModeGrey: '#242424',
    darkModeGrey6: '#313235',
};

export const getBlauSkin: GetKnownSkin = () => {
    const skin: KnownSkin = {
        name: BLAU_SKIN,
        colors: {
            backgroundBrand: palette.blauBluePrimary,
            backgroundBrandSecondary: palette.blauBluePrimary,
            appBarBackground: palette.white,
            background: palette.white,
            backgroundContainer: palette.grey1,
            backgroundContainerHover: applyAlpha(palette.grey6, 0.04),
            backgroundContainerPressed: applyAlpha(palette.grey6, 0.08),
            backgroundContainerBrand: palette.blauBluePrimary,
            backgroundContainerBrandHover: applyAlpha(palette.darkModeBlack, 0.2),
            backgroundContainerBrandPressed: applyAlpha(palette.darkModeBlack, 0.4),
            backgroundContainerBrandOverInverse: palette.blauBlueSecondary,
            backgroundContainerAlternative: palette.blauBluePrimary50,
            backgroundOverlay: applyAlpha(palette.blauBlueSecondary, 0.75),
            backgroundSkeleton: palette.grey2,
            backgroundSkeletonInverse: palette.blauBlueSecondary,
            navigationBarBackground: palette.blauBluePrimary,
            backgroundAlternative: palette.blauBluePrimary100,
            backgroundFeedbackBottom: palette.blauBluePrimary,
            skeletonWave: palette.grey2,
            borderLow: palette.grey1,
            border: palette.grey1,
            borderHigh: palette.grey5,
            borderSelected: palette.blauBlueSecondary700,
            coverBackgroundHover: applyAlpha(palette.darkModeBlack, 0.25),
            coverBackgroundPressed: applyAlpha(palette.darkModeBlack, 0.35),
            buttonDangerBackground: palette.blauRed,
            buttonDangerBackgroundSelected: palette.blauRed700,
            buttonDangerBackgroundHover: palette.blauRed700,
            buttonLinkDangerBackgroundSelected: palette.blauRed100,
            buttonLinkDangerBackgroundInverse: palette.white,
            buttonLinkDangerBackgroundInverseSelected: palette.blauRed100,
            buttonLinkBackgroundSelected: palette.blauPurple100,
            buttonLinkBackgroundInverseSelected: applyAlpha(palette.white, 0.15),
            buttonPrimaryBackground: palette.blauBlueSecondary,
            buttonPrimaryBackgroundInverse: palette.white,
            buttonPrimaryBackgroundSelected: palette.blauBlueSecondary700,
            buttonPrimaryBackgroundHover: palette.blauBlueSecondary700,
            buttonPrimaryBackgroundInverseSelected: palette.blauBluePrimary200,
            buttonSecondaryBorder: palette.blauBlueSecondary,
            buttonSecondaryBorderSelected: palette.blauBlueSecondary700,
            buttonSecondaryBorderInverse: palette.white,
            buttonSecondaryBackgroundHover: palette.blauBlueSecondary100,
            buttonSecondaryBackgroundSelected: palette.blauBlueSecondary100,
            buttonSecondaryBorderInverseSelected: palette.white,
            buttonSecondaryBackgroundInverseHover: applyAlpha(palette.white, 0.2),
            buttonSecondaryBackgroundInverseSelected: applyAlpha(palette.white, 0.2),
            textButtonPrimary: palette.white,
            textButtonPrimaryInverse: palette.blauBlueSecondary,
            textButtonPrimaryInverseSelected: palette.blauBlueSecondary700,
            textButtonSecondary: palette.blauBlueSecondary,
            textButtonSecondarySelected: palette.blauBlueSecondary700,
            textButtonSecondaryInverse: palette.white,
            textButtonSecondaryInverseSelected: palette.white,
            textLink: palette.blauPurple,
            textLinkInverse: palette.white,
            textLinkDanger: palette.blauRed,
            textLinkSnackbar: palette.blauPurple400,
            control: palette.grey2,
            controlActivated: palette.blauBlueSecondary,
            controlInverse: palette.white,
            controlActivatedInverse: palette.white,
            controlError: palette.blauRed,
            barTrack: palette.blauBluePrimary100,
            loadingBar: palette.blauBlueSecondary,
            loadingBarBackground: palette.blauBlueSecondary100,
            toggleAndroidInactive: palette.grey2,
            toggleAndroidBackgroundActive: palette.blauBlueSecondary100,
            iosControlKnob: palette.white,
            divider: palette.grey2,
            dividerInverse: applyAlpha(palette.white, 0.2),
            navigationBarDivider: palette.blauBluePrimary,
            badge: palette.blauRed,
            feedbackErrorBackground: palette.blauRed,
            feedbackInfoBackground: palette.black,
            brand: palette.blauBluePrimary,
            brandHigh: palette.blauBlueSecondary,
            inverse: palette.white,
            neutralHigh: palette.black,
            neutralMedium: palette.grey5,
            neutralMediumInverse: palette.grey5,
            neutralLow: palette.grey1,
            neutralLowAlternative: palette.grey2,
            textPrimary: palette.blauBlueSecondary,
            textPrimaryInverse: palette.white,
            textSecondary: palette.blauBlueSecondary,
            textSecondaryInverse: palette.blauBluePrimary100,
            error: palette.blauRed,
            success: palette.blauGreen,
            warning: palette.blauYellow,
            promo: palette.blauPurple,
            highlight: palette.blauBluePrimary,
            successLow: palette.blauGreen50,
            warningLow: palette.blauYellow100,
            errorLow: palette.blauRed100,
            promoLow: palette.blauPurple100,
            brandLow: palette.blauBlueSecondary100,
            successHigh: palette.blauGreen600,
            warningHigh: palette.blauYellow600,
            errorHigh: palette.blauRed700,
            promoHigh: palette.blauPurple,
            successHighInverse: palette.blauGreen600,
            warningHighInverse: palette.blauYellow600,
            errorHighInverse: palette.blauRed700,
            promoHighInverse: palette.blauPurple,
            textNavigationBarPrimary: palette.white,
            textNavigationBarSecondary: palette.blauBlueSecondary200,
            textNavigationSearchBarHint: palette.blauBlueSecondary200,
            textNavigationSearchBarText: palette.white,
            textAppBar: palette.grey5,
            textAppBarSelected: palette.blauBlueSecondary700,
            customTabsBackground: palette.blauBluePrimary,
        },
        darkModeColors: {
            background: palette.darkModeBlack,
            backgroundAlternative: palette.darkModeBlack,
            backgroundBrand: palette.darkModeBlack,
            backgroundBrandSecondary: palette.darkModeBlack,
            backgroundContainer: palette.darkModeGrey,
            backgroundContainerHover: applyAlpha(palette.white, 0.03),
            backgroundContainerPressed: applyAlpha(palette.white, 0.05),
            backgroundContainerBrand: palette.darkModeGrey,
            backgroundContainerBrandHover: applyAlpha(palette.white, 0.03),
            backgroundContainerBrandPressed: applyAlpha(palette.white, 0.05),
            backgroundContainerBrandOverInverse: palette.darkModeGrey,
            backgroundContainerAlternative: palette.darkModeGrey,
            backgroundOverlay: applyAlpha(palette.darkModeGrey, 0.8),
            backgroundSkeleton: palette.darkModeGrey,
            backgroundSkeletonInverse: palette.darkModeGrey,
            backgroundFeedbackBottom: palette.darkModeBlack,
            appBarBackground: palette.darkModeGrey,
            navigationBarBackground: palette.darkModeBlack,
            skeletonWave: palette.grey5,
            borderLow: palette.darkModeBlack,
            border: palette.darkModeGrey,
            borderHigh: palette.grey5,
            borderSelected: palette.blauBlueSecondary700,
            coverBackgroundHover: applyAlpha(palette.darkModeBlack, 0.25),
            coverBackgroundPressed: applyAlpha(palette.darkModeBlack, 0.35),
            buttonDangerBackground: palette.blauRed,
            buttonDangerBackgroundSelected: palette.blauRed700,
            buttonDangerBackgroundHover: palette.blauRed700,
            buttonLinkDangerBackgroundSelected: applyAlpha(palette.blauPurple, 0.3),
            buttonLinkDangerBackgroundInverse: applyAlpha(palette.white, 0.01),
            buttonLinkDangerBackgroundInverseSelected: applyAlpha(palette.blauPurple, 0.3),
            buttonLinkBackgroundSelected: applyAlpha(palette.blauPurple, 0.3),
            buttonLinkBackgroundInverseSelected: applyAlpha(palette.blauPurple, 0.3),
            buttonPrimaryBackground: palette.blauBlueSecondary,
            buttonPrimaryBackgroundInverse: palette.blauBluePrimary,
            buttonPrimaryBackgroundSelected: palette.blauBlueSecondary700,
            buttonPrimaryBackgroundHover: palette.blauBlueSecondary700,
            buttonPrimaryBackgroundInverseSelected: palette.blauBlueSecondary700,
            buttonSecondaryBorder: palette.white,
            buttonSecondaryBorderSelected: palette.white,
            buttonSecondaryBackgroundHover: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundSelected: applyAlpha(palette.white, 0.15),
            buttonSecondaryBorderInverse: palette.white,
            buttonSecondaryBorderInverseSelected: palette.white,
            buttonSecondaryBackgroundInverseHover: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundInverseSelected: applyAlpha(palette.white, 0.15),
            textButtonPrimary: palette.grey2,
            textButtonPrimaryInverse: palette.grey2,
            textButtonPrimaryInverseSelected: palette.grey2,
            textButtonSecondary: palette.grey2,
            textButtonSecondarySelected: palette.grey2,
            textButtonSecondaryInverse: palette.grey2,
            textButtonSecondaryInverseSelected: palette.grey2,
            textLink: palette.blauPurple400,
            textLinkInverse: palette.blauPurple400,
            textLinkDanger: palette.blauRed,
            textLinkSnackbar: palette.blauPurple400,
            control: palette.darkModeGrey6,
            controlActivated: palette.blauBlueSecondary,
            controlInverse: palette.darkModeGrey6,
            controlActivatedInverse: palette.blauBlueSecondary,
            controlError: palette.blauRed,
            barTrack: palette.darkModeGrey6,
            loadingBar: palette.blauBluePrimary,
            loadingBarBackground: palette.darkModeGrey,
            toggleAndroidInactive: palette.grey5,
            toggleAndroidBackgroundActive: palette.blauBlueSecondary300,
            iosControlKnob: palette.grey2,
            divider: applyAlpha(palette.white, 0.05),
            dividerInverse: applyAlpha(palette.white, 0.05),
            navigationBarDivider: palette.darkModeBlack,
            badge: palette.blauRed,
            feedbackErrorBackground: palette.blauRed,
            feedbackInfoBackground: palette.darkModeGrey,
            brand: palette.blauBluePrimary,
            brandHigh: applyAlpha(palette.white, 0.05),
            inverse: palette.grey2,
            neutralHigh: palette.grey2,
            neutralMedium: palette.grey5,
            neutralMediumInverse: palette.grey5,
            neutralLow: palette.darkModeGrey6,
            neutralLowAlternative: palette.darkModeGrey6,
            textPrimary: palette.grey2,
            textPrimaryInverse: palette.grey2,
            textSecondary: palette.grey4,
            textSecondaryInverse: palette.grey4,
            error: palette.blauRed,
            success: palette.blauGreen,
            warning: palette.blauYellow,
            promo: palette.blauPurple,
            highlight: palette.blauBluePrimary,
            successLow: palette.darkModeGrey6,
            warningLow: palette.darkModeGrey6,
            errorLow: palette.darkModeGrey6,
            promoLow: palette.darkModeGrey6,
            brandLow: palette.darkModeGrey6,
            successHigh: palette.blauGreen200,
            warningHigh: palette.blauYellow200,
            errorHigh: palette.blauRed400,
            promoHigh: palette.blauPurple400,
            successHighInverse: palette.blauGreen600,
            warningHighInverse: palette.blauYellow600,
            errorHighInverse: palette.blauRed700,
            promoHighInverse: palette.blauPurple,
            textNavigationBarPrimary: palette.grey2,
            textNavigationBarSecondary: palette.grey4,
            textNavigationSearchBarHint: palette.grey4,
            textNavigationSearchBarText: palette.grey2,
            textAppBar: palette.grey5,
            textAppBarSelected: palette.grey2,
            customTabsBackground: palette.darkModeBlack,
        },
        borderRadii: {
            button: '2px',
            input: '2px',
            container: '0px',
            legacyDisplay: '2px',
            popup: '0px',
            checkbox: '2px',
            indicator: '2px',
            sheet: '2px',
            bar: '2px',
            avatar: '50%',
            mediaSmall: '8px',
        },
        textPresets: {
            cardTitle: {weight: 'bold'},
            button: {weight: 'medium'},
            tabsLabel: {
                weight: 'medium',
                size: {mobile: 16, desktop: 18},
                lineHeight: {mobile: 24, desktop: 24},
            },
            link: {weight: 'medium'},
            title1: {weight: 'medium'},
            title2: {weight: 'bold', size: {mobile: 20, desktop: 28}, lineHeight: {mobile: 24, desktop: 32}},
            indicator: {weight: 'medium'},
            navigationBar: {weight: 'medium'},
            text5: {weight: 'bold'},
            text6: {weight: 'bold'},
            text7: {weight: 'bold'},
            text8: {weight: 'bold'},
            text9: {weight: 'bold'},
            text10: {weight: 'bold'},
        },
    };
    return skin;
};
