import {MOVISTAR_NEW_SKIN} from './constants';
import {applyAlpha} from '../utils/color';

import type {GetKnownSkin, KnownSkin} from './types';

export const palette = {
    movistarBlue: '#0066FF',
    movistarWhite: '#FEFAF5',
    movistarBlack: '#262423',
    blueLight: '#D3EEFF',
    blue100: '#E5F0FF',
    blue300: '#80B3FF',
    blue500: '#E8F4FA',
    blue600: '#4DBAF7',
    blue800: '#0149B3',
    blueHigh: '#005EEB',
    blueDark: '#022D67',
    red: '#C10000',
    red350: '#FF6767',
    redHigh: '#AD0000',
    salmon100: '#FEEEE6',
    salmon200: '#FDE5D7',
    green200: '#EBF9DF',
    yellow: '#EDB800',
    yellow200: '#FFF3D1',
    yellow400: '#FFCB11',
    yellow500: '#C59A00',
    yellow600: '#BFA960',
    yellowHigh: '#5E4A09',
    yellowLight: '#FFE99C',
    emerald: '#048239',
    emeraldHigh: '#036D30',
    green700: '#407F0F',
    pink45: '#EB5F99',
    pink55: '#C42F6D',
    grey100: '#F8F4F0',
    grey200: '#F3EEEA',
    grey300: '#DFDBD6',
    grey400: '#9F9C99',
    grey500: '#807D7B',
    grey600: '#605E5C',
    white: '#FFFFFF',
    white100: '#FFFAF5',
    black: '#000000',
    darkModeBlack: '#061824',
    darkModeGrey: '#081F2E',
    darkModeGrey2: '#EAEBEE',
    darkModeGrey3: '#CED4D7',
    darkModeGrey4: '#89969F',
    darkModeGrey5: '#6D7D88',
    darkModeGrey6: '#3C5261',
    darkModeGrey7: '#032F46',
};

export const getMovistarNewSkin: GetKnownSkin = () => {
    const skin: KnownSkin = {
        name: MOVISTAR_NEW_SKIN,
        colors: {
            background: palette.white,
            backgroundAlternative: palette.movistarWhite,
            backgroundBrand: palette.movistarBlue,
            backgroundBrandSecondary: palette.movistarBlack,
            backgroundContainer: palette.white,
            backgroundContainerError: palette.salmon100,
            backgroundContainerHover: applyAlpha(palette.movistarBlack, 0.05),
            backgroundContainerPressed: applyAlpha(palette.movistarBlack, 0.02),
            backgroundContainerBrand: palette.movistarBlue,
            backgroundContainerBrandHover: applyAlpha(palette.movistarBlack, 0.1),
            backgroundContainerBrandPressed: applyAlpha(palette.movistarBlack, 0.2),
            backgroundContainerBrandOverInverse: palette.blue800,
            backgroundContainerAlternative: palette.grey100,
            backgroundOverlay: applyAlpha(palette.movistarBlack, 0.6),
            backgroundSkeleton: palette.grey200,
            backgroundSkeletonInverse: palette.blue500,
            backgroundBrandTop: palette.movistarBlue,
            backgroundBrandBottom: palette.movistarBlue,
            appBarBackground: palette.white,
            navigationBarBackground: palette.movistarBlue,
            skeletonWave: palette.grey200,
            borderLow: palette.grey100,
            border: palette.grey300,
            borderHigh: palette.grey600,
            borderSelected: palette.blue800,
            coverBackgroundHover: applyAlpha(palette.movistarBlack, 0.25),
            coverBackgroundPressed: applyAlpha(palette.movistarBlack, 0.35),
            buttonDangerBackground: palette.red,
            buttonDangerBackgroundPressed: palette.redHigh,
            buttonDangerBackgroundHover: palette.redHigh,
            buttonLinkDangerBackgroundInverse: palette.white,
            buttonLinkDangerBackgroundMedia: palette.white,
            buttonLinkDangerBackgroundPressed: palette.salmon100,
            buttonLinkDangerBackgroundInversePressed: palette.salmon100,
            buttonLinkDangerBackgroundMediaPressed: palette.salmon100,
            buttonLinkBackgroundPressed: palette.blue100,
            buttonLinkBackgroundInversePressed: applyAlpha(palette.white, 0.2),
            buttonLinkBackgroundMediaPressed: applyAlpha(palette.white, 0.2),
            buttonPrimaryBackground: palette.movistarBlue,
            buttonPrimaryBackgroundInverse: palette.white,
            buttonPrimaryBackgroundMedia: palette.white,
            buttonPrimaryBackgroundHover: palette.blueHigh,
            buttonPrimaryBackgroundInverseHover: palette.blue100,
            buttonPrimaryBackgroundMediaHover: palette.blue100,
            buttonPrimaryBackgroundPressed: palette.blueHigh,
            buttonPrimaryBackgroundInversePressed: palette.blue100,
            buttonPrimaryBackgroundMediaPressed: palette.blue100,
            buttonSecondaryBorder: palette.movistarBlue,
            buttonSecondaryBorderInverse: palette.white,
            buttonSecondaryBorderMedia: palette.white,
            buttonSecondaryBorderPressed: palette.blue800,
            buttonSecondaryBorderInversePressed: palette.white,
            buttonSecondaryBorderMediaPressed: palette.white,
            buttonSecondaryBackgroundHover: palette.blue100,
            buttonSecondaryBackgroundInverseHover: applyAlpha(palette.white, 0.2),
            buttonSecondaryBackgroundMediaHover: applyAlpha(palette.white, 0.2),
            buttonSecondaryBackgroundPressed: palette.blue100,
            buttonSecondaryBackgroundInversePressed: applyAlpha(palette.white, 0.3),
            buttonSecondaryBackgroundMediaPressed: applyAlpha(palette.white, 0.3),
            textButtonPrimary: palette.white,
            textButtonPrimaryInverse: palette.blue800,
            textButtonPrimaryMedia: palette.movistarBlue,
            textButtonPrimaryInversePressed: palette.blue800,
            textButtonPrimaryMediaPressed: palette.blueHigh,
            textButtonSecondary: palette.movistarBlue,
            textButtonSecondaryInverse: palette.white,
            textButtonSecondaryMedia: palette.white,
            textButtonSecondaryPressed: palette.blue800,
            textButtonSecondaryInversePressed: palette.white,
            textButtonSecondaryMediaPressed: palette.white,
            textLink: palette.movistarBlue,
            textLinkInverse: palette.white,
            textLinkMedia: palette.white,
            textLinkDanger: palette.red,
            textLinkDangerMedia: palette.red,
            textLinkSnackbar: palette.blue300,
            textActivated: palette.blueHigh,
            textBrand: palette.blueHigh,
            inputBorder: palette.grey400,
            inputBorderInverse: palette.white,
            completedStep: palette.movistarBlue,
            completedStepInverse: palette.blue500,
            control: palette.grey400,
            controlActivated: palette.movistarBlue,
            controlInverse: palette.blueLight,
            controlActivatedInverse: palette.white,
            controlError: palette.red,
            barTrack: palette.grey300,
            barTrackInverse: applyAlpha(palette.movistarBlack, 0.14),
            loadingBar: palette.movistarBlue,
            loadingBarBackground: palette.blueHigh,
            toggleAndroidInactive: palette.grey200,
            toggleAndroidBackgroundActive: palette.blue300,
            iosControlKnob: palette.white,
            controlKnobInverse: palette.movistarBlue,
            divider: palette.grey300,
            dividerInverse: applyAlpha(palette.white, 0.2),
            navigationBarDivider: palette.movistarBlue,
            badge: palette.red,
            feedbackErrorBackground: palette.red,
            feedbackInfoBackground: palette.blueDark,
            brand: palette.movistarBlue,
            brandHigh: palette.blue800,
            inverse: palette.white,
            neutralHigh: palette.movistarBlack,
            neutralMedium: palette.grey600,
            neutralMediumInverse: palette.grey600,
            neutralLow: palette.grey100,
            neutralLowAlternative: palette.grey200,
            textPrimary: palette.movistarBlack,
            textPrimaryInverse: palette.white,
            textSecondary: palette.grey600,
            textSecondaryInverse: palette.blue100,
            success: palette.emerald,
            warning: palette.yellow600,
            error: palette.red,
            textError: palette.red,
            textErrorInverse: palette.white,
            promo: palette.redHigh,
            highlight: palette.pink55,
            successLow: palette.green200,
            warningLow: palette.yellow200,
            errorLow: palette.salmon100,
            promoLow: palette.salmon100,
            brandLow: palette.blueLight,
            successHigh: palette.green700,
            warningHigh: palette.yellowHigh,
            errorHigh: palette.redHigh,
            promoHigh: palette.redHigh,
            successHighInverse: palette.emeraldHigh,
            warningHighInverse: palette.yellowHigh,
            errorHighInverse: palette.redHigh,
            promoHighInverse: palette.redHigh,
            textNavigationBarPrimary: palette.white,
            textNavigationBarSecondary: palette.blue300,
            textNavigationSearchBarHint: palette.blue300,
            textNavigationSearchBarText: palette.white,
            textAppBar: palette.grey600,
            textAppBarSelected: palette.blue800,
            customTabsBackground: palette.white,
            tagTextPromo: palette.white,
            tagTextActive: palette.blueHigh,
            tagTextInactive: palette.movistarBlack,
            tagTextInfo: palette.white,
            tagTextSuccess: palette.emeraldHigh,
            tagTextWarning: palette.yellowHigh,
            tagTextError: palette.redHigh,
            tagBackgroundPromo: palette.redHigh,
            tagBackgroundActive: palette.blue100,
            tagBackgroundInactive: palette.grey300,
            tagBackgroundInfo: palette.movistarBlack,
            tagBackgroundSuccess: palette.green200,
            tagBackgroundWarning: palette.yellowLight,
            tagBackgroundError: palette.grey100,
            tagTextPromoInverse: palette.redHigh,
            tagTextActiveInverse: palette.blueHigh,
            tagTextInactiveInverse: palette.grey500,
            tagTextInfoInverse: palette.blueHigh,
            tagTextSuccessInverse: palette.green700,
            tagTextWarningInverse: palette.yellowHigh,
            tagTextErrorInverse: palette.redHigh,
            tagBackgroundPromoInverse: palette.white,
            tagBackgroundActiveInverse: palette.white,
            tagBackgroundInactiveInverse: palette.white,
            tagBackgroundInfoInverse: palette.white,
            tagBackgroundSuccessInverse: palette.white,
            tagBackgroundWarningInverse: palette.white,
            tagBackgroundErrorInverse: palette.white,
            cardContentOverlay: `linear-gradient(180deg, ${applyAlpha(palette.black, 0)} 0%, ${applyAlpha(palette.black, 0.4)} 30%, ${applyAlpha(palette.black, 0.7)} 100%)`,
            cardFooterOverlay: applyAlpha(palette.black, 0.7),
        },
        darkModeColors: {
            background: palette.darkModeBlack,
            backgroundAlternative: palette.darkModeBlack,
            backgroundBrand: palette.darkModeBlack,
            backgroundBrandSecondary: palette.darkModeBlack,
            backgroundContainer: palette.darkModeGrey,
            backgroundContainerError: palette.darkModeGrey,
            backgroundContainerHover: applyAlpha(palette.blueHigh, 0.05),
            backgroundContainerPressed: applyAlpha(palette.blueHigh, 0.08),
            backgroundContainerBrand: palette.darkModeGrey,
            backgroundContainerBrandHover: applyAlpha(palette.white, 0.03),
            backgroundContainerBrandPressed: applyAlpha(palette.white, 0.05),
            backgroundContainerBrandOverInverse: palette.darkModeGrey,
            backgroundContainerAlternative: palette.darkModeGrey,
            backgroundOverlay: applyAlpha(palette.darkModeGrey, 0.8),
            backgroundSkeleton: palette.darkModeGrey6,
            backgroundSkeletonInverse: palette.darkModeGrey6,
            backgroundBrandTop: palette.darkModeBlack,
            backgroundBrandBottom: palette.darkModeBlack,
            appBarBackground: palette.darkModeGrey,
            navigationBarBackground: palette.darkModeBlack,
            skeletonWave: palette.darkModeGrey6,
            borderLow: palette.darkModeBlack,
            border: palette.darkModeGrey,
            borderHigh: palette.darkModeGrey5,
            borderSelected: palette.movistarBlue,
            coverBackgroundHover: applyAlpha(palette.darkModeBlack, 0.25),
            coverBackgroundPressed: applyAlpha(palette.darkModeBlack, 0.35),
            buttonDangerBackground: palette.red,
            buttonDangerBackgroundPressed: palette.redHigh,
            buttonDangerBackgroundHover: palette.redHigh,
            buttonLinkDangerBackgroundInverse: applyAlpha(palette.white, 0),
            buttonLinkDangerBackgroundMedia: palette.white,
            buttonLinkDangerBackgroundPressed: applyAlpha(palette.white, 0.08),
            buttonLinkDangerBackgroundInversePressed: applyAlpha(palette.white, 0.08),
            buttonLinkDangerBackgroundMediaPressed: palette.salmon100,
            buttonLinkBackgroundPressed: applyAlpha(palette.white, 0.08),
            buttonLinkBackgroundInversePressed: applyAlpha(palette.white, 0.08),
            buttonLinkBackgroundMediaPressed: applyAlpha(palette.white, 0.2),
            buttonPrimaryBackground: palette.movistarBlue,
            buttonPrimaryBackgroundInverse: palette.movistarBlue,
            buttonPrimaryBackgroundMedia: palette.white,
            buttonPrimaryBackgroundHover: palette.blue800,
            buttonPrimaryBackgroundInverseHover: palette.blue800,
            buttonPrimaryBackgroundMediaHover: palette.blue100,
            buttonPrimaryBackgroundPressed: palette.blue800,
            buttonPrimaryBackgroundInversePressed: palette.blue800,
            buttonPrimaryBackgroundMediaPressed: palette.blue100,
            buttonSecondaryBorder: palette.white,
            buttonSecondaryBorderInverse: palette.darkModeGrey2,
            buttonSecondaryBorderMedia: palette.white,
            buttonSecondaryBorderPressed: palette.white,
            buttonSecondaryBorderInversePressed: palette.darkModeGrey2,
            buttonSecondaryBorderMediaPressed: palette.white,
            buttonSecondaryBackgroundHover: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundInverseHover: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundMediaHover: applyAlpha(palette.white, 0.2),
            buttonSecondaryBackgroundPressed: applyAlpha(palette.white, 0.25),
            buttonSecondaryBackgroundInversePressed: applyAlpha(palette.white, 0.25),
            buttonSecondaryBackgroundMediaPressed: applyAlpha(palette.white, 0.3),
            textButtonPrimary: palette.white,
            textButtonPrimaryInverse: palette.white,
            textButtonPrimaryMedia: palette.blue600,
            textButtonPrimaryInversePressed: palette.blueHigh,
            textButtonPrimaryMediaPressed: palette.blueHigh,
            textButtonSecondary: palette.darkModeGrey2,
            textButtonSecondaryInverse: palette.darkModeGrey2,
            textButtonSecondaryMedia: palette.white,
            textButtonSecondaryPressed: palette.darkModeGrey2,
            textButtonSecondaryInversePressed: palette.darkModeGrey2,
            textButtonSecondaryMediaPressed: palette.white,
            textLink: palette.movistarBlue,
            textLinkInverse: palette.movistarBlue,
            textLinkMedia: palette.white,
            textLinkDanger: palette.red,
            textLinkDangerMedia: palette.red,
            textLinkSnackbar: palette.movistarBlue,
            textActivated: palette.movistarBlue,
            textBrand: palette.blue800,
            inputBorder: palette.darkModeGrey4,
            inputBorderInverse: palette.darkModeGrey4,
            completedStep: palette.blue800,
            completedStepInverse: palette.blue500,
            control: palette.darkModeGrey4,
            controlActivated: palette.movistarBlue,
            controlInverse: palette.darkModeGrey4,
            controlActivatedInverse: palette.movistarBlue,
            controlError: palette.red,
            barTrack: palette.darkModeGrey6,
            barTrackInverse: palette.darkModeGrey6,
            loadingBar: palette.movistarBlue,
            loadingBarBackground: palette.darkModeGrey6,
            toggleAndroidInactive: palette.darkModeGrey2,
            toggleAndroidBackgroundActive: palette.blue300,
            iosControlKnob: palette.darkModeGrey2,
            controlKnobInverse: palette.darkModeGrey2,
            divider: applyAlpha(palette.white, 0.1),
            dividerInverse: applyAlpha(palette.white, 0.1),
            navigationBarDivider: palette.darkModeBlack,
            badge: palette.red,
            feedbackErrorBackground: palette.red,
            feedbackInfoBackground: palette.blueDark,
            brand: palette.movistarBlue,
            brandHigh: palette.blue300,
            inverse: palette.darkModeGrey2,
            neutralHigh: palette.darkModeGrey2,
            neutralMedium: palette.darkModeGrey5,
            neutralMediumInverse: palette.grey500,
            neutralLow: palette.darkModeGrey7,
            neutralLowAlternative: palette.darkModeGrey7,
            textPrimary: palette.darkModeGrey2,
            textPrimaryInverse: palette.darkModeGrey2,
            textSecondary: palette.darkModeGrey4,
            textSecondaryInverse: palette.darkModeGrey4,
            success: palette.emerald,
            warning: palette.yellow,
            error: palette.red350,
            textError: palette.red350,
            textErrorInverse: palette.red350,
            promo: palette.redHigh,
            highlight: palette.pink45,
            successLow: palette.darkModeGrey7,
            warningLow: palette.darkModeGrey7,
            errorLow: palette.darkModeGrey7,
            promoLow: palette.darkModeGrey7,
            brandLow: palette.darkModeGrey7,
            successHigh: palette.emeraldHigh,
            warningHigh: palette.yellow400,
            errorHigh: palette.redHigh,
            promoHigh: palette.redHigh,
            successHighInverse: palette.green700,
            warningHighInverse: palette.yellowHigh,
            errorHighInverse: palette.redHigh,
            promoHighInverse: palette.redHigh,
            textNavigationBarPrimary: palette.darkModeGrey2,
            textNavigationBarSecondary: palette.darkModeGrey4,
            textNavigationSearchBarHint: palette.darkModeGrey4,
            textNavigationSearchBarText: palette.darkModeGrey2,
            textAppBar: palette.darkModeGrey4,
            textAppBarSelected: palette.movistarBlue,
            customTabsBackground: palette.darkModeBlack,
            tagTextPromo: palette.white,
            tagTextActive: palette.blueHigh,
            tagTextInactive: palette.darkModeGrey3,
            tagTextInfo: palette.white,
            tagTextSuccess: palette.emeraldHigh,
            tagTextWarning: palette.yellow400,
            tagTextError: palette.red350,
            tagBackgroundPromo: palette.salmon200,
            tagBackgroundActive: palette.blueDark,
            tagBackgroundInactive: palette.darkModeGrey7,
            tagBackgroundInfo: palette.blue800,
            tagBackgroundSuccess: palette.darkModeGrey7,
            tagBackgroundWarning: palette.darkModeGrey7,
            tagBackgroundError: palette.darkModeGrey7,
            tagTextPromoInverse: palette.white,
            tagTextActiveInverse: palette.movistarBlue,
            tagTextInactiveInverse: palette.darkModeGrey3,
            tagTextInfoInverse: palette.white,
            tagTextSuccessInverse: palette.green200,
            tagTextWarningInverse: palette.yellow400,
            tagTextErrorInverse: palette.red350,
            tagBackgroundPromoInverse: palette.salmon200,
            tagBackgroundActiveInverse: palette.blueDark,
            tagBackgroundInactiveInverse: palette.darkModeGrey7,
            tagBackgroundInfoInverse: palette.blueDark,
            tagBackgroundSuccessInverse: palette.darkModeGrey7,
            tagBackgroundWarningInverse: palette.darkModeGrey7,
            tagBackgroundErrorInverse: palette.darkModeGrey7,
            cardContentOverlay: `linear-gradient(180deg, ${applyAlpha(palette.black, 0)} 0%, ${applyAlpha(palette.black, 0.4)} 30%, ${applyAlpha(palette.black, 0.7)} 100%)`,
            cardFooterOverlay: applyAlpha(palette.black, 0.7),
        },
        borderRadii: {
            avatar: '50%',
            bar: '999px',
            button: '4px',
            checkbox: '4px',
            container: '16px',
            indicator: '0px',
            chip: '4px',
            input: '12px',
            legacyDisplay: '16px',
            popup: '8px',
            sheet: '16px',
            mediaSmall: '8px',
        },
        textPresets: {
            button: {weight: 'medium'},
            cardTitle: {weight: 'bold'},
            indicator: {weight: 'medium'},
            link: {weight: 'medium'},
            navigationBar: {weight: 'medium'},
            tabsLabel: {
                lineHeight: {desktop: 24, mobile: 24},
                size: {desktop: 18, mobile: 16},
                weight: 'medium',
            },
            text1: {lineHeight: {desktop: 20, mobile: 16}, size: {desktop: 14, mobile: 12}},
            text2: {lineHeight: {desktop: 22, mobile: 20}, size: {desktop: 16, mobile: 14}},
            text3: {lineHeight: {desktop: 24, mobile: 22}, size: {desktop: 18, mobile: 16}},
            text4: {lineHeight: {desktop: 26, mobile: 24}, size: {desktop: 20, mobile: 18}},
            text5: {lineHeight: {desktop: 28, mobile: 26}, size: {desktop: 24, mobile: 20}, weight: 'bold'},
            text6: {lineHeight: {desktop: 32, mobile: 28}, size: {desktop: 28, mobile: 24}, weight: 'bold'},
            text7: {lineHeight: {desktop: 38, mobile: 32}, size: {desktop: 32, mobile: 28}, weight: 'bold'},
            text8: {lineHeight: {desktop: 48, mobile: 38}, size: {desktop: 40, mobile: 32}, weight: 'bold'},
            text9: {lineHeight: {desktop: 56, mobile: 48}, size: {desktop: 48, mobile: 40}, weight: 'bold'},
            text10: {lineHeight: {desktop: 64, mobile: 56}, size: {desktop: 56, mobile: 48}, weight: 'bold'},
            title1: {weight: 'medium'},
            title2: {weight: 'bold'},
            title3: {lineHeight: {desktop: 28, mobile: 26}, size: {desktop: 24, mobile: 20}, weight: 'bold'},
        },
        themeVariants: {
            successFeedback: 'default',
            brandLoadingScreen: 'default',
        },
    };
    return skin;
};
