import {MOVISTAR_SKIN} from './constants';
import {applyAlpha} from '../utils/color';

import type {GetKnownSkin, KnownSkin} from './types';

export const palette = {
    movistarBlue: '#0B9CEA',
    movistarBlue10: '#E6F5FD',
    movistarBlue15: '#CEEBFB',
    movistarBlue20: '#B3E1FB',
    movistarBlue30: '#80CEF9',
    movistarBlue40: '#4DBAF7',
    movistarBlue55: '#008EDD',
    movistarBlueHC: '#066FCB',
    movistarBlueHC55: '#055EAC',
    movistarBlueHC65: '#055398',
    movistarGreen: '#5CB615',
    movistarGreen10: '#EFF8E8',
    movistarGreen30: '#ADDA8A',
    movistarGreen40: '#8DCC5B',
    movistarGreen55: '#52A413',
    movistarGreen60: '#499110',
    movistarGreen70: '#407F0F',
    pepper: '#FF374A',
    pepper10: '#FFEBED',
    pepper40: '#FF7380',
    pepper45: '#FF5F6E',
    pepper55: '#D73241',
    pepper60: '#CC2C3B',
    pepper65: '#BF2937',
    pepper70: '#B22634',
    egg: '#F28D15',
    egg10: '#FEF4E8',
    egg40: '#F6AF5B',
    egg55: '#D97D0D',
    egg80: '#6D3F09',
    pink: '#E63780',
    pink45: '#EB5F99',
    pink55: '#C42F6D',
    purple: '#A13EA1',
    purple10: '#F6ECF6',
    purple35: '#C78BC7',
    purple40: '#BD78BD',
    purple70: '#712B71',
    grey1: '#F6F6F6',
    grey2: '#EEEEEE',
    grey3: '#DDDDDD',
    grey4: '#949494',
    grey5: '#6B6C6F',
    grey6: '#313235',
    white: '#FFFFFF',
    black: '#000000',
    movistarBlueDark: '#0B2739',
    darkModeBlack: '#061824',
    darkModeGrey: '#081F2E',
    darkModeGrey2: '#EAEBEE',
    darkModeGrey3: '#CED4D7',
    darkModeGrey4: '#85939C',
    darkModeGrey5: '#6D7D88',
    darkModeGrey6: '#3C5261',
    darkModeGrey7: '#032F46',
};

export const getMovistarSkin: GetKnownSkin = () => {
    const skin: KnownSkin = {
        name: MOVISTAR_SKIN,
        colors: {
            background: palette.white,
            backgroundAlternative: palette.grey1,
            backgroundBrand: palette.movistarBlue,
            backgroundBrandSecondary: palette.movistarBlueDark,
            backgroundContainer: palette.white,
            backgroundContainerError: palette.pepper10,
            backgroundContainerHover: applyAlpha(palette.black, 0.03),
            backgroundContainerPressed: applyAlpha(palette.black, 0.05),
            backgroundContainerBrand: palette.movistarBlue,
            backgroundContainerBrandHover: applyAlpha(palette.black, 0.1),
            backgroundContainerBrandPressed: applyAlpha(palette.black, 0.2),
            backgroundContainerBrandOverInverse: palette.movistarBlue55,
            backgroundContainerAlternative: palette.grey1,
            backgroundOverlay: applyAlpha(palette.movistarBlueDark, 0.6),
            backgroundSkeleton: palette.grey2,
            backgroundSkeletonInverse: palette.movistarBlue55,
            backgroundBrandTop: palette.movistarBlue,
            backgroundBrandBottom: palette.movistarBlue,
            appBarBackground: palette.white,
            navigationBarBackground: palette.movistarBlue,
            skeletonWave: palette.grey2,
            borderLow: palette.grey1,
            border: palette.grey3,
            borderHigh: palette.grey5,
            borderSelected: palette.movistarBlue,
            coverBackgroundHover: applyAlpha(palette.black, 0.25),
            coverBackgroundPressed: applyAlpha(palette.black, 0.35),
            buttonDangerBackground: palette.pepper55,
            buttonDangerBackgroundPressed: palette.pepper70,
            buttonDangerBackgroundHover: palette.pepper65,
            buttonLinkDangerBackgroundPressed: palette.pepper10,
            buttonLinkDangerBackgroundInverse: palette.white,
            buttonLinkDangerBackgroundInversePressed: palette.pepper10,
            buttonLinkBackgroundPressed: palette.movistarBlue10,
            buttonLinkBackgroundInversePressed: applyAlpha(palette.white, 0.2),
            buttonPrimaryBackground: palette.movistarBlueHC,
            buttonPrimaryBackgroundInverse: palette.white,
            buttonPrimaryBackgroundPressed: palette.movistarBlueHC65,
            buttonPrimaryBackgroundHover: palette.movistarBlueHC55,
            buttonPrimaryBackgroundInversePressed: palette.movistarBlue10,
            buttonSecondaryBorder: palette.movistarBlueHC,
            buttonSecondaryBorderPressed: palette.movistarBlueHC65,
            buttonSecondaryBackgroundHover: palette.movistarBlue10,
            buttonSecondaryBackgroundPressed: palette.movistarBlue15,
            buttonSecondaryBorderInverse: palette.white,
            buttonSecondaryBorderInversePressed: palette.white,
            buttonSecondaryBackgroundInverseHover: applyAlpha(palette.white, 0.2),
            buttonSecondaryBackgroundInversePressed: applyAlpha(palette.white, 0.3),
            textButtonPrimary: palette.white,
            textButtonPrimaryInverse: palette.movistarBlueHC,
            textButtonPrimaryInversePressed: palette.movistarBlueHC,
            textButtonSecondary: palette.movistarBlueHC,
            textButtonSecondaryPressed: palette.movistarBlueHC55,
            textButtonSecondaryInverse: palette.white,
            textButtonSecondaryInversePressed: palette.white,
            textLink: palette.movistarBlueHC,
            textLinkInverse: palette.white,
            textLinkDanger: palette.pepper60,
            textLinkSnackbar: palette.movistarBlue30,
            textActivated: palette.movistarBlueHC,
            textBrand: palette.movistarBlueHC,
            control: palette.grey4,
            controlActivated: palette.movistarBlue,
            controlInverse: palette.movistarBlue20,
            controlActivatedInverse: palette.white,
            controlError: palette.pepper55,
            barTrack: palette.grey3,
            barTrackInverse: applyAlpha(palette.black, 0.14),
            loadingBar: palette.movistarBlue,
            loadingBarBackground: palette.grey2,
            toggleAndroidInactive: palette.grey2,
            toggleAndroidBackgroundActive: palette.movistarBlue20,
            iosControlKnob: palette.white,
            controlKnobInverse: palette.movistarBlue,
            divider: palette.grey3,
            dividerInverse: applyAlpha(palette.white, 0.2),
            navigationBarDivider: palette.movistarBlue,
            badge: palette.pepper55,
            feedbackErrorBackground: palette.pepper55,
            feedbackInfoBackground: palette.movistarBlueDark,
            brand: palette.movistarBlue,
            brandHigh: palette.movistarBlue55,
            inverse: palette.white,
            neutralHigh: palette.movistarBlueDark,
            neutralMedium: palette.grey5,
            neutralMediumInverse: palette.grey5,
            neutralLow: palette.grey1,
            neutralLowAlternative: palette.grey2,
            textPrimary: palette.movistarBlueDark,
            textPrimaryInverse: palette.white,
            textSecondary: palette.grey5,
            textSecondaryInverse: palette.movistarBlue10,
            success: palette.movistarGreen55,
            warning: palette.egg55,
            error: palette.pepper55,
            textError: palette.pepper55,
            textErrorInverse: palette.white,
            promo: palette.purple,
            highlight: palette.pink55,
            successLow: palette.movistarGreen10,
            warningLow: palette.egg10,
            errorLow: palette.pepper10,
            promoLow: palette.purple10,
            brandLow: palette.movistarBlue10,
            successHigh: palette.movistarGreen70,
            warningHigh: palette.egg80,
            errorHigh: palette.pepper70,
            promoHigh: palette.purple70,
            successHighInverse: palette.movistarGreen70,
            warningHighInverse: palette.egg80,
            errorHighInverse: palette.pepper70,
            promoHighInverse: palette.purple70,
            textNavigationBarPrimary: palette.white,
            textNavigationBarSecondary: palette.movistarBlue20,
            textNavigationSearchBarHint: palette.movistarBlue20,
            textNavigationSearchBarText: palette.white,
            textAppBar: palette.grey5,
            textAppBarSelected: palette.movistarBlueHC,
            customTabsBackground: palette.white,
            tagTextPromo: palette.purple70,
            tagTextActive: palette.movistarBlueHC,
            tagTextInactive: palette.grey5,
            tagTextSuccess: palette.movistarGreen70,
            tagTextWarning: palette.egg80,
            tagTextError: palette.pepper70,
            tagBackgroundPromo: palette.purple10,
            tagBackgroundActive: palette.movistarBlue10,
            tagBackgroundInactive: palette.grey1,
            tagBackgroundSuccess: palette.movistarGreen10,
            tagBackgroundWarning: palette.egg10,
            tagBackgroundError: palette.pepper10,
            cardContentOverlay: `linear-gradient(180deg, ${applyAlpha(palette.black, 0)} 0%, ${applyAlpha(palette.black, 0.4)} 30%, ${applyAlpha(palette.black, 0.7)} 100%)`,
        },
        darkModeColors: {
            background: palette.darkModeBlack,
            backgroundAlternative: palette.darkModeBlack,
            backgroundBrand: palette.darkModeBlack,
            backgroundBrandSecondary: palette.darkModeBlack,
            backgroundContainer: palette.darkModeGrey,
            backgroundContainerError: palette.darkModeGrey,
            backgroundContainerHover: applyAlpha(palette.white, 0.03),
            backgroundContainerPressed: applyAlpha(palette.white, 0.05),
            backgroundContainerBrand: palette.darkModeGrey,
            backgroundContainerBrandHover: applyAlpha(palette.white, 0.03),
            backgroundContainerBrandPressed: applyAlpha(palette.white, 0.05),
            backgroundContainerBrandOverInverse: palette.darkModeGrey,
            backgroundContainerAlternative: palette.darkModeGrey,
            backgroundOverlay: applyAlpha(palette.darkModeGrey, 0.8),
            backgroundSkeleton: palette.darkModeGrey6,
            backgroundSkeletonInverse: palette.darkModeGrey6,
            backgroundBrandTop: palette.darkModeBlack,
            backgroundBrandBottom: palette.darkModeBlack,
            appBarBackground: palette.darkModeGrey,
            navigationBarBackground: palette.darkModeBlack,
            skeletonWave: palette.darkModeGrey6,
            borderLow: palette.darkModeBlack,
            border: palette.darkModeGrey,
            borderHigh: palette.darkModeGrey5,
            borderSelected: palette.movistarBlue,
            coverBackgroundHover: applyAlpha(palette.darkModeBlack, 0.25),
            coverBackgroundPressed: applyAlpha(palette.darkModeBlack, 0.35),
            buttonDangerBackground: palette.pepper55,
            buttonDangerBackgroundPressed: palette.pepper70,
            buttonDangerBackgroundHover: palette.pepper65,
            buttonLinkDangerBackgroundPressed: applyAlpha(palette.white, 0.08),
            buttonLinkDangerBackgroundInverse: applyAlpha(palette.white, 0),
            buttonLinkDangerBackgroundInversePressed: applyAlpha(palette.white, 0.08),
            buttonLinkBackgroundPressed: applyAlpha(palette.white, 0.08),
            buttonLinkBackgroundInversePressed: applyAlpha(palette.white, 0.08),
            buttonPrimaryBackground: palette.movistarBlueHC,
            buttonPrimaryBackgroundInverse: palette.movistarBlueHC,
            buttonPrimaryBackgroundPressed: palette.movistarBlueHC65,
            buttonPrimaryBackgroundHover: palette.movistarBlueHC55,
            buttonPrimaryBackgroundInversePressed: palette.movistarBlueHC65,
            buttonSecondaryBackgroundHover: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundPressed: applyAlpha(palette.white, 0.25),
            buttonSecondaryBorder: palette.white,
            buttonSecondaryBorderPressed: palette.white,
            buttonSecondaryBorderInverse: palette.darkModeGrey2,
            buttonSecondaryBorderInversePressed: palette.darkModeGrey2,
            buttonSecondaryBackgroundInverseHover: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundInversePressed: applyAlpha(palette.white, 0.25),
            textButtonPrimary: palette.white,
            textButtonPrimaryInverse: palette.white,
            textButtonPrimaryInversePressed: palette.white,
            textButtonSecondary: palette.darkModeGrey2,
            textButtonSecondaryPressed: palette.darkModeGrey2,
            textButtonSecondaryInverse: palette.darkModeGrey2,
            textButtonSecondaryInversePressed: palette.darkModeGrey2,
            textLink: palette.movistarBlue,
            textLinkInverse: palette.movistarBlue,
            textLinkDanger: palette.pepper45,
            textLinkSnackbar: palette.movistarBlue,
            textActivated: palette.movistarBlue,
            textBrand: palette.movistarBlue,
            control: palette.darkModeGrey4,
            controlActivated: palette.movistarBlue,
            controlInverse: palette.darkModeGrey4,
            controlActivatedInverse: palette.movistarBlue,
            controlError: palette.pepper45,
            barTrack: palette.darkModeGrey6,
            barTrackInverse: palette.darkModeGrey6,
            loadingBar: palette.movistarBlue,
            loadingBarBackground: palette.darkModeGrey6,
            toggleAndroidInactive: palette.darkModeGrey2,
            toggleAndroidBackgroundActive: palette.movistarBlue20,
            iosControlKnob: palette.darkModeGrey2,
            controlKnobInverse: palette.darkModeGrey2,
            divider: applyAlpha(palette.white, 0.1),
            dividerInverse: applyAlpha(palette.white, 0.1),
            navigationBarDivider: palette.darkModeBlack,
            badge: palette.pepper55,
            feedbackErrorBackground: palette.pepper55,
            feedbackInfoBackground: palette.movistarBlueDark,
            brand: palette.movistarBlue,
            brandHigh: palette.movistarBlue40,
            inverse: palette.darkModeGrey2,
            neutralHigh: palette.darkModeGrey2,
            neutralMedium: palette.darkModeGrey5,
            neutralMediumInverse: palette.grey5,
            neutralLow: palette.darkModeGrey6,
            neutralLowAlternative: palette.darkModeGrey6,
            textPrimary: palette.darkModeGrey2,
            textPrimaryInverse: palette.darkModeGrey2,
            textSecondary: palette.darkModeGrey4,
            textSecondaryInverse: palette.darkModeGrey4,
            success: palette.movistarGreen,
            warning: palette.egg,
            error: palette.pepper45,
            textError: palette.pepper45,
            textErrorInverse: palette.pepper45,
            promo: palette.purple40,
            highlight: palette.pink45,
            successLow: palette.darkModeGrey7,
            warningLow: palette.darkModeGrey7,
            errorLow: palette.darkModeGrey7,
            promoLow: palette.darkModeGrey7,
            brandLow: palette.darkModeGrey7,
            successHigh: palette.movistarGreen40,
            warningHigh: palette.egg40,
            errorHigh: palette.pepper45,
            promoHigh: palette.purple35,
            successHighInverse: palette.movistarGreen70,
            warningHighInverse: palette.egg80,
            errorHighInverse: palette.pepper70,
            promoHighInverse: palette.purple70,
            textNavigationBarPrimary: palette.darkModeGrey2,
            textNavigationBarSecondary: palette.darkModeGrey4,
            textNavigationSearchBarHint: palette.darkModeGrey4,
            textNavigationSearchBarText: palette.darkModeGrey2,
            textAppBar: palette.darkModeGrey4,
            textAppBarSelected: palette.movistarBlue,
            customTabsBackground: palette.darkModeBlack,
            tagTextPromo: palette.purple35,
            tagTextActive: palette.movistarBlue,
            tagTextInactive: palette.darkModeGrey3,
            tagTextSuccess: palette.movistarGreen40,
            tagTextWarning: palette.egg40,
            tagTextError: palette.pepper45,
            tagBackgroundPromo: palette.darkModeGrey7,
            tagBackgroundActive: palette.darkModeGrey7,
            tagBackgroundInactive: palette.darkModeGrey7,
            tagBackgroundSuccess: palette.darkModeGrey7,
            tagBackgroundWarning: palette.darkModeGrey7,
            tagBackgroundError: palette.darkModeGrey7,
            cardContentOverlay: `linear-gradient(180deg, ${applyAlpha(palette.black, 0)} 0%, ${applyAlpha(palette.black, 0.4)} 30%, ${applyAlpha(palette.black, 0.7)} 100%)`,
        },
        borderRadii: {
            avatar: '50%',
            bar: '999px',
            button: '999px',
            checkbox: '4px',
            container: '16px',
            indicator: '999px',
            input: '12px',
            legacyDisplay: '16px',
            popup: '8px',
            sheet: '16px',
            mediaSmall: '8px',
        },
        textPresets: {
            button: {weight: 'medium'},
            cardTitle: {weight: 'bold'},
            indicator: {weight: 'medium'},
            link: {weight: 'medium'},
            navigationBar: {weight: 'medium'},
            tabsLabel: {
                lineHeight: {desktop: 24, mobile: 24},
                size: {desktop: 18, mobile: 16},
                weight: 'medium',
            },
            text1: {lineHeight: {desktop: 20, mobile: 16}, size: {desktop: 14, mobile: 12}},
            text2: {lineHeight: {desktop: 24, mobile: 20}, size: {desktop: 16, mobile: 14}},
            text3: {lineHeight: {desktop: 24, mobile: 24}, size: {desktop: 18, mobile: 16}},
            text4: {lineHeight: {desktop: 28, mobile: 24}, size: {desktop: 20, mobile: 18}},
            text5: {lineHeight: {desktop: 32, mobile: 24}, size: {desktop: 28, mobile: 20}, weight: 'bold'},
            text6: {lineHeight: {desktop: 40, mobile: 32}, size: {desktop: 32, mobile: 24}, weight: 'bold'},
            text7: {lineHeight: {desktop: 48, mobile: 32}, size: {desktop: 40, mobile: 28}, weight: 'bold'},
            text8: {lineHeight: {desktop: 56, mobile: 40}, size: {desktop: 48, mobile: 32}, weight: 'bold'},
            text9: {lineHeight: {desktop: 64, mobile: 48}, size: {desktop: 56, mobile: 40}, weight: 'bold'},
            text10: {lineHeight: {desktop: 72, mobile: 56}, size: {desktop: 64, mobile: 48}, weight: 'bold'},
            title1: {weight: 'medium'},
            title2: {weight: 'bold'},
            title3: {lineHeight: {desktop: 32, mobile: 24}, size: {desktop: 28, mobile: 20}, weight: 'bold'},
        },
    };
    return skin;
};
