import {O2_NEW_SKIN} from './constants';
import {applyAlpha} from '../utils/color';

import type {GetKnownSkin, KnownSkin} from './types';

export const palette = {
    o2BluePrimary: '#0050FF',
    o2BluePrimary70: '#0038B2',
    o2BluePrimary90: '#001033',
    o2BluePrimary30: '#80A7FF',
    o2BluePrimary15: '#CCDCFF',
    o2BluePrimary10: '#E5EDFF',
    o2BlueLight: '#82DCFA',
    o2BlueLight30: '#C0EEFD',
    o2BlueLight35: '#B4EAFC',
    o2Green: '#00DC7D',
    o2Green10: '#E5FBF2',
    o2Green40: '#4CE7A4',
    o2Green80: '#006338',
    o2Yellow: '#FADC00',
    o2Orange: '#FFA55A',
    o2Orange10: '#FFF6EE',
    o2Orange40: '#FFC08B',
    o2Orange75: '#996336',
    o2Pink: '#FA96FF',
    o2Pink15: '#FEEAFF',
    o2Pink30: '#FDCAFF',
    o2Pink80: '#704373',
    o2Red: '#FF5A5A',
    o2Red10: '#FFEEEE',
    o2Red20: '#FFCDCD',
    o2Red40: '#FF8B8B',
    o2Red65: '#BF4343',
    grey20: '#F3F3F5',
    grey30: '#D9D9DD', // nuevo para skeletons y otros
    grey40: '#B4B4BE',
    grey45: '#8C8C9A', // nuevo para controles
    grey60: '#6E6E77', // tocado para pasar AA sobre grey20
    grey80: '#3C3C46',
    black: '#00001E',
    white: '#FFFFFF',
    darkModeBlack: '#191919',
    darkModeGrey: '#242424',
    darkModeGrey6: '#313235',
    darkModeO2BluePrimary: '#0020D6',
    darkModeO2BluePrimaryDark: '#000099',
    o2GradientFirst: '#02028E',
    o2GradientSecond: '#0050FF',
    o2GradientThird: '#82DCFA',
};

export const getO2NewSkin: GetKnownSkin = () => {
    const skin: KnownSkin = {
        name: O2_NEW_SKIN,
        colors: {
            background: palette.white,
            backgroundAlternative: palette.grey20,
            backgroundBrand: `linear-gradient(164deg, ${palette.o2GradientFirst} 43.6%, ${palette.o2GradientSecond} 75.12%, ${palette.o2GradientThird} 106.64%)`,
            backgroundBrandSecondary: palette.o2BluePrimary,
            backgroundContainer: palette.white,
            backgroundContainerHover: applyAlpha(palette.darkModeBlack, 0.03),
            backgroundContainerPressed: applyAlpha(palette.darkModeBlack, 0.05),
            backgroundContainerBrand: `linear-gradient(164deg, ${palette.o2GradientFirst} 43.6%, ${palette.o2GradientSecond} 75.12%, ${palette.o2GradientThird} 106.64%)`,
            backgroundContainerBrandHover: applyAlpha(palette.darkModeBlack, 0.2),
            backgroundContainerBrandPressed: applyAlpha(palette.darkModeBlack, 0.4),
            backgroundContainerBrandOverInverse: palette.o2BluePrimary70,
            backgroundContainerAlternative: palette.grey20,
            backgroundOverlay: applyAlpha(palette.black, 0.6),
            backgroundSkeleton: palette.grey30,
            backgroundSkeletonInverse: palette.o2BluePrimary70,
            backgroundFeedbackBottom: palette.o2BluePrimary,
            appBarBackground: palette.white,
            navigationBarBackground: palette.o2GradientFirst,
            skeletonWave: palette.grey30,
            borderLow: palette.grey20,
            border: palette.grey30,
            borderHigh: palette.grey80,
            borderSelected: palette.o2BluePrimary,
            coverBackgroundHover: applyAlpha(palette.darkModeBlack, 0.25),
            coverBackgroundPressed: applyAlpha(palette.darkModeBlack, 0.35),
            buttonDangerBackground: palette.o2Red65,
            buttonDangerBackgroundSelected: palette.o2Red65,
            buttonDangerBackgroundHover: palette.o2Red65,
            buttonLinkDangerBackgroundSelected: palette.o2Red10,
            buttonLinkDangerBackgroundInverse: palette.white,
            buttonLinkDangerBackgroundInverseSelected: palette.o2Red10,
            buttonLinkBackgroundSelected: palette.o2BluePrimary10,
            buttonLinkBackgroundInverseSelected: applyAlpha(palette.white, 0.08),
            buttonPrimaryBackground: palette.o2BluePrimary,
            buttonPrimaryBackgroundInverse: palette.white,
            buttonPrimaryBackgroundSelected: palette.o2BluePrimary70,
            buttonPrimaryBackgroundHover: palette.o2BluePrimary70,
            buttonPrimaryBackgroundInverseSelected: palette.o2BluePrimary30,
            buttonSecondaryBorder: palette.o2BluePrimary,
            buttonSecondaryBorderSelected: palette.o2BluePrimary70,
            buttonSecondaryBackgroundHover: palette.o2BluePrimary10,
            buttonSecondaryBackgroundSelected: palette.o2BluePrimary10,
            buttonSecondaryBorderInverse: palette.white,
            buttonSecondaryBorderInverseSelected: palette.o2BluePrimary30,
            buttonSecondaryBackgroundInverseHover: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundInverseSelected: applyAlpha(palette.white, 0.15),
            textButtonPrimary: palette.white,
            textButtonPrimaryInverse: palette.o2BluePrimary,
            textButtonPrimaryInverseSelected: palette.o2BluePrimary70,
            textButtonSecondary: palette.o2BluePrimary,
            textButtonSecondarySelected: palette.o2BluePrimary70,
            textButtonSecondaryInverse: palette.white,
            textButtonSecondaryInverseSelected: palette.white,
            textLink: palette.o2BluePrimary,
            textLinkInverse: palette.white,
            textLinkDanger: palette.o2Red65,
            textLinkSnackbar: palette.o2BluePrimary30,
            control: palette.grey45,
            controlActivated: palette.o2BluePrimary,
            controlInverse: palette.white,
            controlActivatedInverse: palette.white,
            controlError: palette.o2Red,
            barTrack: palette.grey30,
            loadingBar: palette.o2BluePrimary,
            loadingBarBackground: palette.grey20,
            toggleAndroidInactive: palette.grey30,
            toggleAndroidBackgroundActive: palette.o2BluePrimary15,
            iosControlKnob: palette.white,
            divider: palette.grey30,
            dividerInverse: applyAlpha(palette.white, 0.2),
            navigationBarDivider: palette.o2BluePrimary,
            badge: palette.o2Red65,
            feedbackErrorBackground: palette.o2Red65,
            feedbackInfoBackground: palette.black,
            brand: palette.o2BluePrimary,
            brandHigh: palette.o2BluePrimary70,
            inverse: palette.white,
            neutralHigh: palette.black,
            neutralMedium: palette.grey60,
            neutralMediumInverse: palette.grey60,
            neutralLow: palette.grey20,
            neutralLowAlternative: palette.grey30,
            textPrimary: palette.black,
            textPrimaryInverse: palette.white,
            textSecondary: palette.grey60,
            textSecondaryInverse: palette.o2BluePrimary15,
            success: palette.o2Green,
            warning: palette.o2Orange,
            error: palette.o2Red,
            promo: palette.o2Pink,
            highlight: palette.o2Pink,
            successLow: palette.o2Green10,
            warningLow: palette.o2Orange10,
            errorLow: palette.o2Red10,
            promoLow: palette.o2Pink15,
            brandLow: palette.o2BluePrimary10,
            successHigh: palette.o2Green80,
            warningHigh: palette.o2Orange75,
            errorHigh: palette.o2Red65,
            promoHigh: palette.o2Pink80,
            successHighInverse: palette.o2Green80,
            warningHighInverse: palette.o2Orange75,
            errorHighInverse: palette.o2Red65,
            promoHighInverse: palette.o2Pink80,
            textNavigationBarPrimary: palette.white,
            textNavigationBarSecondary: palette.o2BluePrimary30,
            textNavigationSearchBarHint: palette.o2BluePrimary30,
            textNavigationSearchBarText: palette.white,
            textAppBar: palette.grey60,
            textAppBarSelected: palette.o2BluePrimary,
            customTabsBackground: palette.o2BluePrimary,
        },
        darkModeColors: {
            background: palette.darkModeBlack,
            backgroundAlternative: palette.darkModeBlack,
            backgroundBrand: palette.darkModeBlack,
            backgroundBrandSecondary: palette.darkModeBlack,
            backgroundContainer: palette.darkModeGrey,
            backgroundContainerHover: applyAlpha(palette.white, 0.03),
            backgroundContainerPressed: applyAlpha(palette.white, 0.05),
            backgroundContainerBrand: palette.darkModeGrey,
            backgroundContainerBrandHover: applyAlpha(palette.white, 0.03),
            backgroundContainerBrandPressed: applyAlpha(palette.white, 0.05),
            backgroundContainerBrandOverInverse: palette.darkModeGrey,
            backgroundContainerAlternative: palette.darkModeGrey,
            backgroundOverlay: applyAlpha(palette.darkModeGrey, 0.8),
            backgroundSkeleton: palette.darkModeGrey6,
            backgroundSkeletonInverse: palette.darkModeGrey6,
            backgroundFeedbackBottom: palette.darkModeBlack,
            appBarBackground: palette.darkModeGrey,
            navigationBarBackground: palette.darkModeBlack,
            skeletonWave: palette.grey80,
            borderLow: palette.darkModeBlack,
            border: palette.darkModeGrey,
            borderHigh: palette.grey80,
            borderSelected: palette.o2BluePrimary30,
            coverBackgroundHover: applyAlpha(palette.darkModeBlack, 0.25),
            coverBackgroundPressed: applyAlpha(palette.darkModeBlack, 0.35),
            buttonDangerBackground: palette.o2Red,
            buttonDangerBackgroundSelected: palette.o2Red65,
            buttonDangerBackgroundHover: palette.o2Red65,
            buttonLinkDangerBackgroundSelected: applyAlpha(palette.white, 0.08),
            buttonLinkDangerBackgroundInverse: applyAlpha(palette.white, 0.01),
            buttonLinkDangerBackgroundInverseSelected: applyAlpha(palette.white, 0.08),
            buttonLinkBackgroundSelected: applyAlpha(palette.white, 0.08),
            buttonLinkBackgroundInverseSelected: applyAlpha(palette.white, 0.08),
            buttonPrimaryBackground: palette.darkModeO2BluePrimary,
            buttonPrimaryBackgroundInverse: palette.darkModeO2BluePrimary,
            buttonPrimaryBackgroundSelected: palette.darkModeO2BluePrimaryDark,
            buttonPrimaryBackgroundHover: palette.darkModeO2BluePrimaryDark,
            buttonPrimaryBackgroundInverseSelected: palette.darkModeO2BluePrimaryDark,
            buttonSecondaryBackgroundSelected: applyAlpha(palette.white, 0.15),
            buttonSecondaryBorder: palette.white,
            buttonSecondaryBorderSelected: palette.white,
            buttonSecondaryBorderInverse: palette.white,
            buttonSecondaryBorderInverseSelected: palette.white,
            buttonSecondaryBackgroundHover: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundInverseHover: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundInverseSelected: applyAlpha(palette.white, 0.15),
            textButtonPrimary: palette.grey30,
            textButtonPrimaryInverse: palette.grey30,
            textButtonPrimaryInverseSelected: palette.grey30,
            textButtonSecondary: palette.grey30,
            textButtonSecondarySelected: palette.grey30,
            textButtonSecondaryInverse: palette.grey30,
            textButtonSecondaryInverseSelected: palette.grey30,
            textLink: palette.o2BluePrimary30,
            textLinkInverse: palette.o2BluePrimary30,
            textLinkDanger: palette.o2Red,
            textLinkSnackbar: palette.o2BluePrimary30,
            control: palette.darkModeGrey6,
            controlActivated: palette.o2BluePrimary30,
            controlInverse: palette.darkModeGrey6,
            controlActivatedInverse: palette.o2BluePrimary30,
            controlError: palette.o2Red,
            loadingBar: palette.darkModeO2BluePrimary,
            loadingBarBackground: palette.darkModeGrey6,
            toggleAndroidInactive: palette.grey60,
            toggleAndroidBackgroundActive: palette.o2BlueLight30,
            iosControlKnob: palette.grey30,
            badge: palette.o2Red65,
            feedbackErrorBackground: palette.o2Red,
            feedbackInfoBackground: palette.darkModeGrey6,
            divider: applyAlpha(palette.white, 0.05),
            dividerInverse: applyAlpha(palette.white, 0.05),
            navigationBarDivider: palette.darkModeBlack,
            brand: palette.o2BluePrimary30,
            brandHigh: applyAlpha(palette.white, 0.05),
            inverse: palette.grey30,
            neutralHigh: palette.grey30,
            neutralMedium: palette.grey60,
            neutralMediumInverse: palette.grey60,
            neutralLow: palette.darkModeGrey6,
            neutralLowAlternative: palette.darkModeGrey6,
            textPrimary: palette.grey30,
            textPrimaryInverse: palette.grey30,
            textSecondary: palette.grey60,
            textSecondaryInverse: palette.grey60,
            success: palette.o2Green,
            warning: palette.o2Orange,
            error: palette.o2Red,
            promo: palette.o2Pink,
            highlight: palette.o2Pink,
            successLow: palette.darkModeGrey6,
            warningLow: palette.darkModeGrey6,
            errorLow: palette.darkModeGrey6,
            promoLow: palette.darkModeGrey6,
            brandLow: palette.darkModeGrey6,
            successHigh: palette.o2Green40,
            warningHigh: palette.o2Orange40,
            errorHigh: palette.o2Red40,
            promoHigh: palette.o2Pink30,
            successHighInverse: palette.o2Green80,
            warningHighInverse: palette.o2Orange75,
            errorHighInverse: palette.o2Red65,
            promoHighInverse: palette.o2Pink,
            textNavigationBarPrimary: palette.grey30,
            textNavigationBarSecondary: palette.grey60,
            textNavigationSearchBarHint: palette.grey60,
            textNavigationSearchBarText: palette.grey30,
            textAppBar: palette.grey80,
            textAppBarSelected: palette.grey30,
            customTabsBackground: palette.darkModeBlack,
        },
        borderRadii: {
            avatar: '50%',
            bar: '999px',
            button: '999px',
            checkbox: '2px',
            container: '16px',
            indicator: '999px',
            input: '12px',
            legacyDisplay: '16px',
            popup: '8px',
            sheet: '16px',
            mediaSmall: '8px',
        },
        textPresets: {
            cardTitle: {weight: 'medium'},
            button: {weight: 'medium'},
            tabsLabel: {
                weight: 'medium',
                size: {mobile: 16, desktop: 18},
                lineHeight: {mobile: 24, desktop: 24},
            },
            link: {weight: 'medium'},
            title1: {weight: 'medium'},
            title2: {weight: 'bold', size: {mobile: 20, desktop: 28}, lineHeight: {mobile: 24, desktop: 32}},
            indicator: {weight: 'medium'},
            navigationBar: {weight: 'medium'},
            text5: {weight: 'bold'},
            text6: {weight: 'bold'},
            text7: {weight: 'bold'},
            text8: {weight: 'bold'},
            text9: {weight: 'bold'},
            text10: {weight: 'bold'},
        },
    };
    return skin;
};
