import {O2_NEW_SKIN} from './constants';
import {applyAlpha} from '../utils/color';

import type {GetKnownSkin, KnownSkin} from './types';

export const palette = {
    beyondBlue: '#0050FF',
    beyondBlue90: '#001033',
    beyondBlue70: '#0038B2',
    beyondBlue45: '#0A73EB',
    beyondBlue40: '#4C84FF',
    beyondBlue30: '#80A7FF',
    beyondBlue15: '#CCDCFF',
    beyondBlue10: '#E5EDFF',
    darkBlue: '#00008C',
    o2BlueLight: '#82DCFA',
    o2BlueLight30: '#C0EEFD',
    o2BlueLight35: '#B4EAFC',
    o2Green: '#00DC7D',
    o2Green10: '#E5FBF2',
    o2Green40: '#4CE7A4',
    o2Green80: '#006338',
    o2Yellow: '#FADC00',
    o2Orange: '#FFA55A',
    o2Orange10: '#FFF6EE',
    o2Orange40: '#FFC08B',
    o2Orange75: '#996336',
    o2Pink: '#FA96FF',
    o2Pink15: '#FEEAFF',
    o2Pink30: '#FDCAFF',
    o2Pink80: '#704373',
    o2Red: '#FF5A5A',
    o2Red10: '#FFEEEE',
    o2Red20: '#FFCDCD',
    o2Red40: '#FF8B8B',
    o2Red55: 'EB0000',
    o2Red65: '#BF4343',
    grey20: '#F3F3F5',
    grey30: '#D9D9DD',
    grey40: '#B4B4BE',
    grey45: '#8C8C9A',
    grey60: '#6E6E77',
    grey80: '#3C3C46',
    black: '#00001E',
    white: '#FFFFFF',
    darkModeBlack: '#121212',
    darkModeGrey: '#1E1E1E',
    darkModeGrey6: '#2B2C2E',
    darkModeBeyondBlue: '#1A62FF',
    darkModeBeyondBlueDark: '#0048E5',
};

export const getO2NewSkin: GetKnownSkin = () => {
    const skin: KnownSkin = {
        name: O2_NEW_SKIN,
        colors: {
            background: palette.white,
            backgroundAlternative: palette.grey20,
            backgroundBrand: `linear-gradient(180deg, ${palette.darkBlue} 0%, ${palette.beyondBlue} 64%, ${palette.beyondBlue45} 100%)`,
            backgroundBrandSecondary: palette.beyondBlue,
            backgroundContainer: palette.white,
            backgroundContainerHover: applyAlpha(palette.darkModeBlack, 0.03),
            backgroundContainerPressed: applyAlpha(palette.darkModeBlack, 0.05),
            backgroundContainerBrand: `linear-gradient(180deg, ${palette.darkBlue} 0%, ${palette.beyondBlue} 64%, ${palette.beyondBlue45} 100%)`,
            backgroundContainerBrandHover: applyAlpha(palette.darkModeBlack, 0.2),
            backgroundContainerBrandPressed: applyAlpha(palette.darkModeBlack, 0.4),
            backgroundContainerBrandOverInverse: palette.beyondBlue70,
            backgroundContainerAlternative: palette.grey20,
            backgroundOverlay: applyAlpha(palette.black, 0.6),
            backgroundSkeleton: palette.grey30,
            backgroundSkeletonInverse: palette.beyondBlue70,
            backgroundBrandTop: palette.darkBlue,
            backgroundBrandBottom: palette.beyondBlue45,
            appBarBackground: palette.white,
            navigationBarBackground: palette.darkBlue,
            skeletonWave: palette.grey30,
            borderLow: palette.grey20,
            border: palette.grey30,
            borderHigh: palette.grey80,
            borderSelected: palette.beyondBlue,
            coverBackgroundHover: applyAlpha(palette.darkModeBlack, 0.25),
            coverBackgroundPressed: applyAlpha(palette.darkModeBlack, 0.35),
            buttonDangerBackground: palette.o2Red65,
            buttonDangerBackgroundSelected: palette.o2Red65,
            buttonDangerBackgroundHover: palette.o2Red65,
            buttonLinkDangerBackgroundSelected: palette.o2Red10,
            buttonLinkDangerBackgroundInverse: palette.white,
            buttonLinkDangerBackgroundInverseSelected: palette.o2Red10,
            buttonLinkBackgroundSelected: palette.beyondBlue10,
            buttonLinkBackgroundInverseSelected: applyAlpha(palette.white, 0.08),
            buttonPrimaryBackground: palette.beyondBlue,
            buttonPrimaryBackgroundInverse: palette.white,
            buttonPrimaryBackgroundSelected: palette.beyondBlue70,
            buttonPrimaryBackgroundHover: palette.beyondBlue70,
            buttonPrimaryBackgroundInverseSelected: palette.beyondBlue30,
            buttonSecondaryBorder: palette.beyondBlue,
            buttonSecondaryBorderSelected: palette.beyondBlue70,
            buttonSecondaryBackgroundHover: palette.beyondBlue10,
            buttonSecondaryBackgroundSelected: palette.beyondBlue10,
            buttonSecondaryBorderInverse: palette.white,
            buttonSecondaryBorderInverseSelected: palette.beyondBlue30,
            buttonSecondaryBackgroundInverseHover: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundInverseSelected: applyAlpha(palette.white, 0.15),
            textButtonPrimary: palette.white,
            textButtonPrimaryInverse: palette.beyondBlue,
            textButtonPrimaryInverseSelected: palette.beyondBlue70,
            textButtonSecondary: palette.beyondBlue,
            textButtonSecondarySelected: palette.beyondBlue70,
            textButtonSecondaryInverse: palette.white,
            textButtonSecondaryInverseSelected: palette.white,
            textLink: palette.beyondBlue,
            textLinkInverse: palette.white,
            textLinkDanger: palette.o2Red65,
            textLinkSnackbar: palette.beyondBlue30,
            control: palette.grey45,
            controlActivated: palette.beyondBlue,
            controlInverse: palette.white,
            controlActivatedInverse: palette.white,
            controlError: palette.o2Red65,
            barTrack: palette.grey30,
            loadingBar: palette.beyondBlue,
            loadingBarBackground: palette.grey20,
            toggleAndroidInactive: palette.grey30,
            toggleAndroidBackgroundActive: palette.beyondBlue15,
            iosControlKnob: palette.white,
            divider: palette.grey30,
            dividerInverse: applyAlpha(palette.white, 0.2),
            navigationBarDivider: palette.beyondBlue,
            badge: palette.o2Red65,
            feedbackErrorBackground: palette.o2Red65,
            feedbackInfoBackground: palette.black,
            brand: palette.beyondBlue,
            brandHigh: palette.beyondBlue70,
            inverse: palette.white,
            neutralHigh: palette.black,
            neutralMedium: palette.grey60,
            neutralMediumInverse: palette.grey60,
            neutralLow: palette.grey20,
            neutralLowAlternative: palette.grey30,
            textPrimary: palette.black,
            textPrimaryInverse: palette.white,
            textSecondary: palette.grey60,
            textSecondaryInverse: palette.beyondBlue10,
            success: palette.o2Green,
            warning: palette.o2Orange,
            error: palette.o2Red65,
            promo: palette.o2Pink,
            highlight: palette.o2Pink,
            successLow: palette.o2Green10,
            warningLow: palette.o2Orange10,
            errorLow: palette.o2Red10,
            promoLow: palette.o2Pink15,
            brandLow: palette.beyondBlue10,
            successHigh: palette.o2Green80,
            warningHigh: palette.o2Orange75,
            errorHigh: palette.o2Red65,
            promoHigh: palette.o2Pink80,
            successHighInverse: palette.o2Green80,
            warningHighInverse: palette.o2Orange75,
            errorHighInverse: palette.o2Red65,
            promoHighInverse: palette.o2Pink80,
            textNavigationBarPrimary: palette.white,
            textNavigationBarSecondary: palette.beyondBlue30,
            textNavigationSearchBarHint: palette.beyondBlue30,
            textNavigationSearchBarText: palette.white,
            textAppBar: palette.grey60,
            textAppBarSelected: palette.beyondBlue,
            customTabsBackground: palette.beyondBlue,
            tagTextPromo: palette.o2Pink80,
            tagTextActive: palette.beyondBlue,
            tagTextInactive: palette.grey60,
            tagTextSuccess: palette.o2Green80,
            tagTextWarning: palette.o2Orange75,
            tagTextError: palette.o2Red65,
            tagBackgroundPromo: palette.o2Pink15,
            tagBackgroundActive: palette.beyondBlue10,
            tagBackgroundInactive: palette.grey20,
            tagBackgroundSuccess: palette.o2Green10,
            tagBackgroundWarning: palette.o2Orange10,
            tagBackgroundError: palette.o2Red10,
        },
        darkModeColors: {
            background: palette.darkModeBlack,
            backgroundAlternative: palette.darkModeBlack,
            backgroundBrand: palette.darkModeBlack,
            backgroundBrandSecondary: palette.darkModeBlack,
            backgroundContainer: palette.darkModeGrey,
            backgroundContainerHover: applyAlpha(palette.white, 0.03),
            backgroundContainerPressed: applyAlpha(palette.white, 0.05),
            backgroundContainerBrand: palette.darkModeGrey,
            backgroundContainerBrandHover: applyAlpha(palette.white, 0.03),
            backgroundContainerBrandPressed: applyAlpha(palette.white, 0.05),
            backgroundContainerBrandOverInverse: palette.darkModeGrey,
            backgroundContainerAlternative: palette.darkModeGrey,
            backgroundOverlay: applyAlpha(palette.darkModeGrey, 0.8),
            backgroundSkeleton: palette.darkModeGrey6,
            backgroundSkeletonInverse: palette.darkModeGrey6,
            backgroundBrandTop: palette.darkModeBlack,
            backgroundBrandBottom: palette.darkModeBlack,
            appBarBackground: palette.darkModeGrey,
            navigationBarBackground: palette.darkModeBlack,
            skeletonWave: palette.grey80,
            borderLow: palette.darkModeBlack,
            border: palette.darkModeGrey,
            borderHigh: palette.grey80,
            borderSelected: palette.beyondBlue40,
            coverBackgroundHover: applyAlpha(palette.darkModeBlack, 0.25),
            coverBackgroundPressed: applyAlpha(palette.darkModeBlack, 0.35),
            buttonDangerBackground: palette.o2Red,
            buttonDangerBackgroundSelected: palette.o2Red65,
            buttonDangerBackgroundHover: palette.o2Red65,
            buttonLinkDangerBackgroundSelected: applyAlpha(palette.white, 0.08),
            buttonLinkDangerBackgroundInverse: applyAlpha(palette.white, 0.01),
            buttonLinkDangerBackgroundInverseSelected: applyAlpha(palette.white, 0.08),
            buttonLinkBackgroundSelected: applyAlpha(palette.white, 0.08),
            buttonLinkBackgroundInverseSelected: applyAlpha(palette.white, 0.08),
            buttonPrimaryBackground: palette.darkModeBeyondBlue,
            buttonPrimaryBackgroundInverse: palette.darkModeBeyondBlue,
            buttonPrimaryBackgroundSelected: palette.darkModeBeyondBlueDark,
            buttonPrimaryBackgroundHover: palette.darkModeBeyondBlueDark,
            buttonPrimaryBackgroundInverseSelected: palette.darkModeBeyondBlueDark,
            buttonSecondaryBackgroundSelected: applyAlpha(palette.white, 0.15),
            buttonSecondaryBorder: palette.white,
            buttonSecondaryBorderSelected: palette.white,
            buttonSecondaryBorderInverse: palette.white,
            buttonSecondaryBorderInverseSelected: palette.white,
            buttonSecondaryBackgroundHover: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundInverseHover: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundInverseSelected: applyAlpha(palette.white, 0.15),
            textButtonPrimary: palette.white,
            textButtonPrimaryInverse: palette.white,
            textButtonPrimaryInverseSelected: palette.white,
            textButtonSecondary: palette.grey30,
            textButtonSecondarySelected: palette.grey30,
            textButtonSecondaryInverse: palette.grey30,
            textButtonSecondaryInverseSelected: palette.grey30,
            textLink: palette.beyondBlue40,
            textLinkInverse: palette.beyondBlue40,
            textLinkDanger: palette.o2Red,
            textLinkSnackbar: palette.beyondBlue40,
            control: palette.grey60,
            controlActivated: palette.beyondBlue30,
            controlInverse: palette.darkModeGrey6,
            controlActivatedInverse: palette.beyondBlue30,
            controlError: palette.o2Red,
            barTrack: palette.darkModeGrey6,
            loadingBar: palette.darkModeBeyondBlue,
            loadingBarBackground: palette.darkModeGrey6,
            toggleAndroidInactive: palette.grey20,
            toggleAndroidBackgroundActive: palette.o2BlueLight30,
            iosControlKnob: palette.grey30,
            badge: palette.o2Red65,
            feedbackErrorBackground: palette.o2Red,
            feedbackInfoBackground: palette.darkModeGrey6,
            divider: applyAlpha(palette.white, 0.05),
            dividerInverse: applyAlpha(palette.white, 0.05),
            navigationBarDivider: palette.darkModeBlack,
            brand: palette.beyondBlue30,
            brandHigh: applyAlpha(palette.white, 0.05),
            inverse: palette.grey30,
            neutralHigh: palette.grey30,
            neutralMedium: palette.grey60,
            neutralMediumInverse: palette.grey60,
            neutralLow: palette.darkModeGrey6,
            neutralLowAlternative: palette.darkModeGrey6,
            textPrimary: palette.grey30,
            textPrimaryInverse: palette.grey30,
            textSecondary: palette.grey45,
            textSecondaryInverse: palette.grey45,
            success: palette.o2Green,
            warning: palette.o2Orange,
            error: palette.o2Red,
            promo: palette.o2Pink,
            highlight: palette.o2Pink,
            successLow: palette.darkModeGrey6,
            warningLow: palette.darkModeGrey6,
            errorLow: palette.darkModeGrey6,
            promoLow: palette.darkModeGrey6,
            brandLow: palette.darkModeGrey6,
            successHigh: palette.o2Green40,
            warningHigh: palette.o2Orange40,
            errorHigh: palette.o2Red40,
            promoHigh: palette.o2Pink30,
            successHighInverse: palette.o2Green80,
            warningHighInverse: palette.o2Orange75,
            errorHighInverse: palette.o2Red65,
            promoHighInverse: palette.o2Pink,
            textNavigationBarPrimary: palette.grey30,
            textNavigationBarSecondary: palette.grey45,
            textNavigationSearchBarHint: palette.grey45,
            textNavigationSearchBarText: palette.grey30,
            textAppBar: palette.grey45,
            textAppBarSelected: palette.grey30,
            customTabsBackground: palette.darkModeBlack,
            tagTextPromo: palette.o2Pink,
            tagTextActive: palette.beyondBlue30,
            tagTextInactive: palette.grey40,
            tagTextSuccess: palette.o2Green,
            tagTextWarning: palette.o2Orange,
            tagTextError: palette.o2Red,
            tagBackgroundPromo: palette.darkModeGrey6,
            tagBackgroundActive: palette.darkModeGrey6,
            tagBackgroundInactive: palette.darkModeGrey6,
            tagBackgroundSuccess: palette.darkModeGrey6,
            tagBackgroundWarning: palette.darkModeGrey6,
            tagBackgroundError: palette.darkModeGrey6,
        },
        borderRadii: {
            avatar: '50%',
            bar: '999px',
            button: '999px',
            checkbox: '2px',
            container: '16px',
            indicator: '999px',
            input: '12px',
            legacyDisplay: '16px',
            popup: '8px',
            sheet: '16px',
            mediaSmall: '8px',
        },
        textPresets: {
            cardTitle: {weight: 'medium'},
            button: {weight: 'medium'},
            tabsLabel: {
                weight: 'medium',
                size: {mobile: 16, desktop: 18},
                lineHeight: {mobile: 24, desktop: 24},
            },
            link: {weight: 'medium'},
            title1: {weight: 'medium'},
            title2: {weight: 'bold', size: {mobile: 20, desktop: 28}, lineHeight: {mobile: 24, desktop: 32}},
            indicator: {weight: 'medium'},
            navigationBar: {weight: 'medium'},
            text5: {weight: 'bold'},
            text6: {weight: 'bold'},
            text7: {weight: 'bold'},
            text8: {weight: 'bold'},
            text9: {weight: 'bold'},
            text10: {weight: 'bold'},
        },
    };
    return skin;
};
