import {O2_SKIN} from './constants';
import {applyAlpha} from '../utils/color';

import type {GetKnownSkin, KnownSkin} from './types';

export const palette = {
    o2BluePrimary: '#0019A5',
    o2BluePrimary70: '#000066',
    o2BluePrimary90: '#000033',
    o2BluePrimary30: '#808CD2',
    o2BluePrimary15: '#CCD1ED',
    o2BluePrimary10: '#E5E8F6',
    o2BlueMid: '#0090D0',
    o2BlueLight: '#41B6E6',
    o2BlueLight30: '#C6E9F7',
    o2BlueLight35: '#8DD3F0',
    o2Teal: '#01B7B4',
    o2Green: '#91C90E',
    o2Green10: '#F4FAE7',
    o2Green40: '#B2D956',
    o2Green80: '#415A06',
    o2Yellow: '#FEDB00',
    o2Orange: '#FF7F41',
    o2Orange10: '#FFF2EC',
    o2Orange40: '#FFA57A',
    o2Orange75: '#A6522A',
    o2Pink: '#E45DBF',
    o2Purple: '#952D98',
    o2Purple10: '#F4EAF5',
    o2Purple30: '#CA9ACB',
    pepper: '#F4364C',
    pepper10: '#FEEBED',
    pepper20: '#FCC3C9',
    pepper40: '#FF7380',
    pepper60: '#C32B3D',
    grey1: '#F6F6F6',
    grey2: '#EEEEEE',
    grey3: '#DDDDDD',
    grey4: '#999999',
    grey5: '#707070',
    grey6: '#000033',
    white: '#FFFFFF',
    black: '#000000',
    darkModeBlack: '#191919',
    darkModeGrey: '#242424',
    darkModeGrey6: '#313235',
    darkModeO2BluePrimary: '#0020D6',
    darkModeO2BluePrimaryDark: '#000099',
};

export const getO2Skin: GetKnownSkin = () => {
    const skin: KnownSkin = {
        name: O2_SKIN,
        colors: {
            background: palette.white,
            backgroundAlternative: palette.grey1,
            backgroundBrand: palette.o2BluePrimary,
            backgroundNegative: palette.o2BluePrimary70,
            backgroundBrandSecondary: palette.o2BluePrimary,
            backgroundContainer: palette.white,
            backgroundContainerError: palette.pepper10,
            backgroundContainerHover: applyAlpha(palette.darkModeBlack, 0.05),
            backgroundContainerPressed: applyAlpha(palette.darkModeBlack, 0.08),
            backgroundContainerBrand: palette.o2BluePrimary,
            backgroundContainerBrandHover: applyAlpha(palette.darkModeBlack, 0.2),
            backgroundContainerBrandPressed: applyAlpha(palette.darkModeBlack, 0.4),
            backgroundContainerBrandOverInverse: palette.o2BluePrimary70,
            backgroundContainerNegative: applyAlpha(palette.darkModeBlack, 0.4),
            backgroundContainerBrandOverBrand: palette.o2BluePrimary70,
            backgroundContainerAlternative: palette.grey1,
            backgroundOverlay: applyAlpha(palette.grey6, 0.6),
            backgroundSkeleton: palette.grey2,
            backgroundSkeletonInverse: palette.o2BluePrimary70,
            backgroundSkeletonNegative: applyAlpha(palette.grey6, 0.2),
            backgroundSkeletonBrand: palette.o2BluePrimary70,
            backgroundBrandTop: palette.o2BluePrimary,
            backgroundBrandBottom: palette.o2BluePrimary,
            appBarBackground: palette.white,
            navigationBarBackground: palette.o2BluePrimary,
            skeletonWave: palette.grey2,
            borderLow: palette.grey1,
            border: palette.grey3,
            borderHigh: palette.grey5,
            borderSelected: palette.o2BluePrimary,
            coverBackgroundHover: applyAlpha(palette.darkModeBlack, 0.25),
            coverBackgroundPressed: applyAlpha(palette.darkModeBlack, 0.35),
            buttonDangerBackground: palette.pepper,
            buttonDangerBackgroundPressed: palette.pepper60,
            buttonDangerBackgroundHover: palette.pepper60,
            buttonLinkDangerBackgroundInverse: palette.white,
            buttonLinkDangerBackgroundNegative: palette.white,
            buttonLinkDangerBackgroundBrand: palette.white,
            buttonLinkDangerBackgroundMedia: palette.white,
            buttonLinkDangerBackgroundPressed: palette.pepper10,
            buttonLinkDangerBackgroundInversePressed: palette.pepper10,
            buttonLinkDangerBackgroundNegativePressed: palette.pepper10,
            buttonLinkDangerBackgroundBrandPressed: palette.pepper10,
            buttonLinkDangerBackgroundMediaPressed: palette.pepper10,
            buttonLinkBackgroundPressed: palette.o2BluePrimary10,
            buttonLinkBackgroundInversePressed: applyAlpha(palette.white, 0.08),
            buttonLinkBackgroundNegativePressed: applyAlpha(palette.white, 0.08),
            buttonLinkBackgroundBrandPressed: applyAlpha(palette.white, 0.08),
            buttonLinkBackgroundMediaPressed: applyAlpha(palette.white, 0.08),
            buttonPrimaryBackground: palette.o2BluePrimary,
            buttonPrimaryBackgroundInverse: palette.white,
            buttonPrimaryBackgroundNegative: palette.white,
            buttonPrimaryBackgroundBrand: palette.white,
            buttonPrimaryBackgroundMedia: palette.white,
            buttonPrimaryBackgroundHover: palette.o2BluePrimary70,
            buttonPrimaryBackgroundInverseHover: palette.o2BluePrimary30,
            buttonPrimaryBackgroundNegativeHover: palette.o2BluePrimary30,
            buttonPrimaryBackgroundBrandHover: palette.o2BluePrimary30,
            buttonPrimaryBackgroundMediaHover: palette.o2BluePrimary30,
            buttonPrimaryBackgroundPressed: palette.o2BluePrimary70,
            buttonPrimaryBackgroundInversePressed: palette.o2BluePrimary30,
            buttonPrimaryBackgroundNegativePressed: palette.o2BluePrimary30,
            buttonPrimaryBackgroundBrandPressed: palette.o2BluePrimary30,
            buttonPrimaryBackgroundMediaPressed: palette.o2BluePrimary30,
            buttonSecondaryBackgroundBrand: applyAlpha(palette.white, 0),
            buttonSecondaryBorder: palette.o2BluePrimary,
            buttonSecondaryBorderInverse: palette.white,
            buttonSecondaryBorderNegative: palette.white,
            buttonSecondaryBorderBrand: palette.white,
            buttonSecondaryBorderMedia: palette.white,
            buttonSecondaryBorderPressed: palette.o2BluePrimary70,
            buttonSecondaryBorderInversePressed: palette.o2BluePrimary30,
            buttonSecondaryBorderNegativePressed: palette.o2BluePrimary30,
            buttonSecondaryBorderBrandPressed: palette.o2BluePrimary30,
            buttonSecondaryBorderMediaPressed: palette.o2BluePrimary30,
            buttonSecondaryBackgroundHover: palette.o2BluePrimary10,
            buttonSecondaryBackgroundInverseHover: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundNegativeHover: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundBrandHover: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundMediaHover: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundPressed: palette.o2BluePrimary10,
            buttonSecondaryBackgroundInversePressed: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundNegativePressed: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundBrandPressed: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundMediaPressed: applyAlpha(palette.white, 0.15),
            textButtonPrimary: palette.white,
            textButtonPrimaryInverse: palette.o2BluePrimary,
            textButtonPrimaryNegative: palette.o2BluePrimary,
            textButtonPrimaryBrand: palette.o2BluePrimary,
            textButtonPrimaryMedia: palette.o2BluePrimary,
            textButtonPrimaryInversePressed: palette.o2BluePrimary70,
            textButtonPrimaryNegativePressed: palette.o2BluePrimary70,
            textButtonPrimaryBrandPressed: palette.o2BluePrimary70,
            textButtonPrimaryMediaPressed: palette.o2BluePrimary70,
            textButtonSecondary: palette.o2BluePrimary,
            textButtonSecondaryInverse: palette.white,
            textButtonSecondaryNegative: palette.white,
            textButtonSecondaryBrand: palette.white,
            textButtonSecondaryMedia: palette.white,
            textButtonSecondaryPressed: palette.o2BluePrimary70,
            textButtonSecondaryInversePressed: palette.white,
            textButtonSecondaryNegativePressed: palette.white,
            textButtonSecondaryBrandPressed: palette.white,
            textButtonSecondaryMediaPressed: palette.white,
            textLink: palette.o2BluePrimary,
            textLinkInverse: palette.white,
            textLinkNegative: palette.white,
            textLinkBrand: palette.white,
            textLinkMedia: palette.white,
            textLinkDanger: palette.pepper,
            textLinkDangerMedia: palette.pepper,
            textLinkSnackbar: palette.o2BluePrimary30,
            textActivated: palette.o2BluePrimary,
            textBrand: palette.o2BluePrimary,
            inputBorder: palette.grey3,
            inputBorderInverse: palette.white,
            inputBorderNegative: palette.white,
            inputBorderBrand: palette.white,
            completedStep: palette.o2BluePrimary,
            completedStepInverse: palette.o2BluePrimary70,
            completedStepNegative: palette.o2BluePrimary70,
            completedStepBrand: palette.o2BluePrimary70,
            control: palette.grey3,
            controlActivated: palette.o2BluePrimary,
            controlInverse: palette.o2BluePrimary30,
            controlNegative: palette.o2BluePrimary30,
            controlBrand: palette.o2BluePrimary30,
            controlActivatedInverse: palette.white,
            controlActivatedNegative: palette.white,
            controlActivatedBrand: palette.white,
            controlError: palette.pepper,
            chevronIndicator: palette.grey5,
            barTrack: palette.grey3,
            barTrackInverse: applyAlpha(palette.white, 0.3),
            barTrackNegative: applyAlpha(palette.white, 0.3),
            barTrackBrand: applyAlpha(palette.white, 0.3),
            loadingBar: palette.o2BluePrimary,
            loadingBarBackground: palette.grey1,
            toggleAndroidInactive: palette.grey2,
            toggleAndroidBackgroundActive: palette.o2BluePrimary15,
            toggleAndroidActiveBrand: palette.white,
            toggleAndroidInactiveBrand: palette.grey2,
            toggleAndroidBackgroundActiveBrand: palette.o2BluePrimary15,
            toggleAndroidBackgroundInactiveBrand: palette.o2BluePrimary30,
            iosControlKnob: palette.white,
            controlKnobInverse: palette.o2BluePrimary,
            controlKnobNegative: palette.o2BluePrimary,
            controlKnobBrand: palette.o2BluePrimary,
            divider: palette.grey2,
            dividerInverse: applyAlpha(palette.white, 0.2),
            dividerNegative: applyAlpha(palette.white, 0.2),
            dividerBrand: applyAlpha(palette.white, 0.2),
            navigationBarDivider: palette.o2BluePrimary,
            badge: palette.pepper60,
            feedbackErrorBackground: palette.pepper,
            feedbackInfoBackground: palette.grey6,
            brand: palette.o2BluePrimary,
            brandHigh: palette.o2BluePrimary70,
            inverse: palette.white,
            negative: palette.white,
            neutralHigh: palette.grey6,
            neutralHighBrand: palette.white,
            neutralHighNegative: palette.white,
            neutralMedium: palette.grey5,
            neutralMediumInverse: palette.grey5,
            neutralMediumNegative: palette.grey5,
            neutralMediumBrand: palette.grey5,
            neutralLow: palette.grey1,
            neutralLowAlternative: palette.grey2,
            textPrimary: palette.grey6,
            textPrimaryInverse: palette.white,
            textPrimaryNegative: palette.white,
            textPrimaryBrand: palette.white,
            textPrimaryMedia: palette.white,
            textSecondary: palette.grey5,
            textSecondaryInverse: palette.o2BluePrimary15,
            textSecondaryNegative: palette.o2BluePrimary15,
            textSecondaryBrand: palette.o2BluePrimary15,
            textSecondaryMedia: palette.white,
            success: palette.o2Green,
            warning: palette.o2Orange,
            error: palette.pepper,
            textError: palette.pepper,
            textErrorInverse: palette.white,
            textErrorNegative: palette.white,
            textErrorBrand: palette.white,
            promo: palette.o2Purple,
            highlight: palette.o2Pink,
            successLow: palette.o2Green10,
            warningLow: palette.o2Orange10,
            errorLow: palette.pepper10,
            promoLow: palette.o2Purple10,
            brandLow: palette.o2BluePrimary10,
            successHigh: palette.o2Green80,
            warningHigh: palette.o2Orange75,
            errorHigh: palette.pepper60,
            promoHigh: palette.o2Purple,
            successHighInverse: palette.o2Green80,
            successHighNegative: palette.o2Green80,
            successHighBrand: palette.o2Green80,
            warningHighInverse: palette.o2Orange75,
            warningHighNegative: palette.o2Orange75,
            warningHighBrand: palette.o2Orange75,
            errorHighInverse: palette.pepper60,
            errorHighNegative: palette.pepper60,
            errorHighBrand: palette.pepper60,
            promoHighInverse: palette.o2Purple,
            promoHighNegative: palette.o2Purple,
            promoHighBrand: palette.o2Purple,
            textNavigationBarPrimary: palette.white,
            textNavigationBarSecondary: palette.o2BluePrimary30,
            textNavigationSearchBarHint: palette.o2BluePrimary30,
            textNavigationSearchBarText: palette.white,
            textAppBar: palette.grey4,
            textAppBarSelected: palette.o2BluePrimary,
            iosGlassAppBarSelected: palette.o2BluePrimary,
            customTabsBackground: palette.o2BluePrimary,
            tagTextPromo: palette.o2Purple,
            tagTextActive: palette.o2BluePrimary,
            tagTextInactive: palette.grey5,
            tagTextInfo: palette.o2BluePrimary,
            tagTextSuccess: palette.o2Green80,
            tagTextWarning: palette.o2Orange75,
            tagTextError: palette.pepper60,
            tagBackgroundPromo: palette.o2Purple10,
            tagBackgroundActive: palette.o2BluePrimary10,
            tagBackgroundInactive: palette.grey1,
            tagBackgroundInfo: palette.o2BluePrimary10,
            tagBackgroundSuccess: palette.o2Green10,
            tagBackgroundWarning: palette.o2Orange10,
            tagBackgroundError: palette.pepper10,
            tagTextPromoInverse: palette.o2Purple,
            tagTextPromoNegative: palette.o2Purple,
            tagTextPromoBrand: palette.o2Purple,
            tagTextActiveInverse: palette.o2BluePrimary,
            tagTextActiveNegative: palette.o2BluePrimary,
            tagTextActiveBrand: palette.o2BluePrimary,
            tagTextInactiveInverse: palette.grey5,
            tagTextInactiveNegative: palette.grey5,
            tagTextInactiveBrand: palette.grey5,
            tagTextInfoInverse: palette.o2BluePrimary,
            tagTextInfoNegative: palette.o2BluePrimary,
            tagTextInfoBrand: palette.o2BluePrimary,
            tagTextSuccessInverse: palette.o2Green80,
            tagTextSuccessNegative: palette.o2Green80,
            tagTextSuccessBrand: palette.o2Green80,
            tagTextWarningInverse: palette.o2Orange75,
            tagTextWarningNegative: palette.o2Orange75,
            tagTextWarningBrand: palette.o2Orange75,
            tagTextErrorInverse: palette.pepper60,
            tagTextErrorNegative: palette.pepper60,
            tagTextErrorBrand: palette.pepper60,
            tagBackgroundPromoInverse: palette.o2Purple10,
            tagBackgroundPromoNegative: palette.o2Purple10,
            tagBackgroundPromoBrand: palette.o2Purple10,
            tagBackgroundActiveInverse: palette.o2BluePrimary10,
            tagBackgroundActiveNegative: palette.o2BluePrimary10,
            tagBackgroundActiveBrand: palette.o2BluePrimary10,
            tagBackgroundInactiveInverse: palette.grey1,
            tagBackgroundInactiveNegative: palette.grey1,
            tagBackgroundInactiveBrand: palette.grey1,
            tagBackgroundInfoInverse: palette.o2BluePrimary10,
            tagBackgroundInfoNegative: palette.o2BluePrimary10,
            tagBackgroundInfoBrand: palette.o2BluePrimary10,
            tagBackgroundSuccessInverse: palette.o2Green10,
            tagBackgroundSuccessNegative: palette.o2Green10,
            tagBackgroundSuccessBrand: palette.o2Green10,
            tagBackgroundWarningInverse: palette.o2Orange10,
            tagBackgroundWarningNegative: palette.o2Orange10,
            tagBackgroundWarningBrand: palette.o2Orange10,
            tagBackgroundErrorInverse: palette.pepper10,
            tagBackgroundErrorNegative: palette.pepper10,
            tagBackgroundErrorBrand: palette.pepper10,
            cardContentOverlay: `linear-gradient(180deg, ${applyAlpha(palette.black, 0)} 0%, ${applyAlpha(palette.black, 0.4)} 30%, ${applyAlpha(palette.black, 0.7)} 100%)`,
            cardFooterOverlay: applyAlpha(palette.black, 0.7),
        },
        darkModeColors: {
            background: palette.darkModeBlack,
            backgroundAlternative: palette.darkModeBlack,
            backgroundBrand: palette.darkModeBlack,
            backgroundNegative: palette.darkModeBlack,
            backgroundBrandSecondary: palette.darkModeBlack,
            backgroundContainer: palette.darkModeGrey,
            backgroundContainerError: palette.darkModeGrey,
            backgroundContainerHover: applyAlpha(palette.white, 0.05),
            backgroundContainerPressed: applyAlpha(palette.white, 0.08),
            backgroundContainerBrand: palette.darkModeGrey,
            backgroundContainerBrandHover: applyAlpha(palette.white, 0.03),
            backgroundContainerBrandPressed: applyAlpha(palette.white, 0.05),
            backgroundContainerBrandOverInverse: palette.darkModeGrey,
            backgroundContainerNegative: palette.darkModeGrey,
            backgroundContainerBrandOverBrand: palette.darkModeGrey,
            backgroundContainerAlternative: palette.darkModeGrey,
            backgroundOverlay: applyAlpha(palette.darkModeGrey, 0.8),
            backgroundSkeleton: palette.darkModeGrey6,
            backgroundSkeletonInverse: palette.darkModeGrey6,
            backgroundSkeletonNegative: palette.darkModeGrey6,
            backgroundSkeletonBrand: palette.darkModeGrey6,
            backgroundBrandTop: palette.darkModeBlack,
            backgroundBrandBottom: palette.darkModeBlack,
            appBarBackground: palette.darkModeGrey,
            navigationBarBackground: palette.darkModeBlack,
            skeletonWave: palette.grey5,
            borderLow: palette.darkModeBlack,
            border: palette.darkModeGrey,
            borderHigh: palette.grey5,
            borderSelected: palette.o2BluePrimary30,
            coverBackgroundHover: applyAlpha(palette.darkModeBlack, 0.25),
            coverBackgroundPressed: applyAlpha(palette.darkModeBlack, 0.35),
            buttonDangerBackground: palette.pepper,
            buttonDangerBackgroundPressed: palette.pepper60,
            buttonDangerBackgroundHover: palette.pepper60,
            buttonLinkDangerBackgroundInverse: applyAlpha(palette.white, 0),
            buttonLinkDangerBackgroundNegative: applyAlpha(palette.white, 0),
            buttonLinkDangerBackgroundBrand: applyAlpha(palette.white, 0),
            buttonLinkDangerBackgroundMedia: palette.white,
            buttonLinkDangerBackgroundPressed: applyAlpha(palette.white, 0.08),
            buttonLinkDangerBackgroundInversePressed: applyAlpha(palette.white, 0.08),
            buttonLinkDangerBackgroundNegativePressed: applyAlpha(palette.white, 0.08),
            buttonLinkDangerBackgroundBrandPressed: applyAlpha(palette.white, 0.08),
            buttonLinkDangerBackgroundMediaPressed: palette.pepper10,
            buttonLinkBackgroundPressed: applyAlpha(palette.white, 0.08),
            buttonLinkBackgroundInversePressed: applyAlpha(palette.white, 0.08),
            buttonLinkBackgroundNegativePressed: applyAlpha(palette.white, 0.08),
            buttonLinkBackgroundBrandPressed: applyAlpha(palette.white, 0.08),
            buttonLinkBackgroundMediaPressed: applyAlpha(palette.white, 0.08),
            buttonPrimaryBackground: palette.darkModeO2BluePrimary,
            buttonPrimaryBackgroundInverse: palette.darkModeO2BluePrimary,
            buttonPrimaryBackgroundNegative: palette.darkModeO2BluePrimary,
            buttonPrimaryBackgroundBrand: palette.darkModeO2BluePrimary,
            buttonPrimaryBackgroundMedia: palette.white,
            buttonPrimaryBackgroundHover: palette.darkModeO2BluePrimaryDark,
            buttonPrimaryBackgroundInverseHover: palette.darkModeO2BluePrimaryDark,
            buttonPrimaryBackgroundNegativeHover: palette.darkModeO2BluePrimaryDark,
            buttonPrimaryBackgroundBrandHover: palette.darkModeO2BluePrimaryDark,
            buttonPrimaryBackgroundMediaHover: palette.o2BluePrimary30,
            buttonPrimaryBackgroundPressed: palette.darkModeO2BluePrimaryDark,
            buttonPrimaryBackgroundInversePressed: palette.darkModeO2BluePrimaryDark,
            buttonPrimaryBackgroundNegativePressed: palette.darkModeO2BluePrimaryDark,
            buttonPrimaryBackgroundBrandPressed: palette.darkModeO2BluePrimaryDark,
            buttonPrimaryBackgroundMediaPressed: palette.o2BluePrimary30,
            buttonSecondaryBackgroundBrand: applyAlpha(palette.white, 0),
            buttonSecondaryBorder: palette.white,
            buttonSecondaryBorderInverse: palette.white,
            buttonSecondaryBorderNegative: palette.white,
            buttonSecondaryBorderBrand: palette.white,
            buttonSecondaryBorderMedia: palette.white,
            buttonSecondaryBorderPressed: palette.white,
            buttonSecondaryBorderInversePressed: palette.white,
            buttonSecondaryBorderNegativePressed: palette.white,
            buttonSecondaryBorderBrandPressed: palette.white,
            buttonSecondaryBorderMediaPressed: palette.o2BluePrimary30,
            buttonSecondaryBackgroundHover: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundInverseHover: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundNegativeHover: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundBrandHover: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundMediaHover: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundPressed: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundInversePressed: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundNegativePressed: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundBrandPressed: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundMediaPressed: applyAlpha(palette.white, 0.15),
            textButtonPrimary: palette.grey2,
            textButtonPrimaryInverse: palette.grey2,
            textButtonPrimaryNegative: palette.grey2,
            textButtonPrimaryBrand: palette.grey2,
            textButtonPrimaryMedia: palette.o2BluePrimary,
            textButtonPrimaryInversePressed: palette.grey2,
            textButtonPrimaryNegativePressed: palette.grey2,
            textButtonPrimaryBrandPressed: palette.grey2,
            textButtonPrimaryMediaPressed: palette.o2BluePrimary70,
            textButtonSecondary: palette.grey2,
            textButtonSecondaryInverse: palette.grey2,
            textButtonSecondaryNegative: palette.grey2,
            textButtonSecondaryBrand: palette.grey2,
            textButtonSecondaryMedia: palette.white,
            textButtonSecondaryPressed: palette.grey2,
            textButtonSecondaryInversePressed: palette.grey2,
            textButtonSecondaryNegativePressed: palette.grey2,
            textButtonSecondaryBrandPressed: palette.grey2,
            textButtonSecondaryMediaPressed: palette.white,
            textLink: palette.o2BluePrimary30,
            textLinkInverse: palette.o2BluePrimary30,
            textLinkNegative: palette.o2BluePrimary30,
            textLinkBrand: palette.o2BluePrimary30,
            textLinkMedia: palette.white,
            textLinkDanger: palette.pepper,
            textLinkDangerMedia: palette.pepper,
            textLinkSnackbar: palette.o2BluePrimary30,
            textActivated: palette.o2BluePrimary30,
            textBrand: palette.o2BluePrimary30,
            inputBorder: palette.darkModeGrey6,
            inputBorderInverse: palette.darkModeGrey6,
            inputBorderNegative: palette.darkModeGrey6,
            inputBorderBrand: palette.darkModeGrey6,
            completedStep: palette.darkModeO2BluePrimary,
            completedStepInverse: palette.darkModeO2BluePrimary,
            completedStepNegative: palette.darkModeO2BluePrimary,
            completedStepBrand: palette.darkModeO2BluePrimary,
            control: palette.darkModeGrey6,
            controlActivated: palette.o2BluePrimary30,
            controlInverse: palette.darkModeGrey6,
            controlNegative: palette.darkModeGrey6,
            controlBrand: palette.darkModeGrey6,
            controlActivatedInverse: palette.o2BluePrimary30,
            controlActivatedNegative: palette.o2BluePrimary30,
            controlActivatedBrand: palette.o2BluePrimary30,
            controlError: palette.pepper,
            chevronIndicator: palette.grey5,
            barTrack: palette.darkModeGrey6,
            barTrackInverse: palette.darkModeGrey6,
            barTrackNegative: palette.darkModeGrey6,
            barTrackBrand: palette.darkModeGrey6,
            loadingBar: palette.darkModeO2BluePrimary,
            loadingBarBackground: palette.darkModeGrey6,
            toggleAndroidInactive: palette.grey4,
            toggleAndroidBackgroundActive: palette.o2BlueLight30,
            toggleAndroidActiveBrand: palette.o2BluePrimary30,
            toggleAndroidInactiveBrand: palette.grey4,
            toggleAndroidBackgroundActiveBrand: palette.o2BlueLight30,
            toggleAndroidBackgroundInactiveBrand: palette.darkModeGrey6,
            iosControlKnob: palette.grey2,
            controlKnobInverse: palette.grey2,
            controlKnobNegative: palette.grey2,
            controlKnobBrand: palette.grey2,
            badge: palette.pepper60,
            feedbackErrorBackground: palette.pepper,
            feedbackInfoBackground: palette.darkModeGrey6,
            divider: applyAlpha(palette.white, 0.05),
            dividerInverse: applyAlpha(palette.white, 0.05),
            dividerNegative: applyAlpha(palette.white, 0.05),
            dividerBrand: applyAlpha(palette.white, 0.05),
            navigationBarDivider: palette.darkModeBlack,
            brand: palette.o2BluePrimary30,
            brandHigh: applyAlpha(palette.white, 0.05),
            inverse: palette.grey2,
            negative: palette.grey2,
            neutralHigh: palette.grey2,
            neutralHighNegative: palette.grey2,
            neutralHighBrand: palette.grey2,
            neutralMedium: palette.grey5,
            neutralMediumInverse: palette.grey5,
            neutralMediumNegative: palette.grey5,
            neutralMediumBrand: palette.grey5,
            neutralLow: palette.darkModeGrey6,
            neutralLowAlternative: palette.darkModeGrey6,
            textPrimary: palette.grey2,
            textPrimaryInverse: palette.grey2,
            textPrimaryNegative: palette.grey2,
            textPrimaryBrand: palette.grey2,
            textPrimaryMedia: palette.white,
            textSecondary: palette.grey4,
            textSecondaryInverse: palette.grey4,
            textSecondaryNegative: palette.grey4,
            textSecondaryBrand: palette.grey4,
            textSecondaryMedia: palette.white,
            success: palette.o2Green,
            warning: palette.o2Orange,
            error: palette.pepper,
            textError: palette.pepper,
            textErrorInverse: palette.pepper,
            textErrorNegative: palette.pepper,
            textErrorBrand: palette.pepper,
            promo: palette.o2Purple,
            highlight: palette.o2Pink,
            successLow: palette.darkModeGrey6,
            warningLow: palette.darkModeGrey6,
            errorLow: palette.darkModeGrey6,
            promoLow: palette.darkModeGrey6,
            brandLow: palette.darkModeGrey6,
            successHigh: palette.o2Green40,
            warningHigh: palette.o2Orange40,
            errorHigh: palette.pepper40,
            promoHigh: palette.o2Purple30,
            successHighInverse: palette.o2Green80,
            successHighNegative: palette.o2Green80,
            successHighBrand: palette.o2Green80,
            warningHighInverse: palette.o2Orange75,
            warningHighNegative: palette.o2Orange75,
            warningHighBrand: palette.o2Orange75,
            errorHighInverse: palette.pepper60,
            errorHighNegative: palette.pepper60,
            errorHighBrand: palette.pepper60,
            promoHighInverse: palette.o2Purple,
            promoHighNegative: palette.o2Purple,
            promoHighBrand: palette.o2Purple,
            textNavigationBarPrimary: palette.grey2,
            textNavigationBarSecondary: palette.grey4,
            textNavigationSearchBarHint: palette.grey4,
            textNavigationSearchBarText: palette.grey2,
            textAppBar: palette.grey5,
            textAppBarSelected: palette.grey2,
            iosGlassAppBarSelected: palette.white,
            customTabsBackground: palette.darkModeBlack,
            tagTextPromo: palette.o2Purple30,
            tagTextActive: palette.o2BluePrimary30,
            tagTextInactive: palette.grey5,
            tagTextInfo: palette.o2BluePrimary30,
            tagTextSuccess: palette.o2Green40,
            tagTextWarning: palette.o2Orange40,
            tagTextError: palette.pepper40,
            tagBackgroundPromo: palette.darkModeGrey6,
            tagBackgroundActive: palette.darkModeGrey6,
            tagBackgroundInactive: palette.darkModeGrey6,
            tagBackgroundInfo: palette.darkModeGrey6,
            tagBackgroundSuccess: palette.darkModeGrey6,
            tagBackgroundWarning: palette.darkModeGrey6,
            tagBackgroundError: palette.darkModeGrey6,
            tagTextPromoInverse: palette.o2Purple30,
            tagTextPromoNegative: palette.o2Purple30,
            tagTextPromoBrand: palette.o2Purple30,
            tagTextActiveInverse: palette.o2BluePrimary30,
            tagTextActiveNegative: palette.o2BluePrimary30,
            tagTextActiveBrand: palette.o2BluePrimary30,
            tagTextInactiveInverse: palette.grey5,
            tagTextInactiveNegative: palette.grey5,
            tagTextInactiveBrand: palette.grey5,
            tagTextInfoInverse: palette.o2BluePrimary30,
            tagTextInfoNegative: palette.o2BluePrimary30,
            tagTextInfoBrand: palette.o2BluePrimary30,
            tagTextSuccessInverse: palette.o2Green40,
            tagTextSuccessNegative: palette.o2Green40,
            tagTextSuccessBrand: palette.o2Green40,
            tagTextWarningInverse: palette.o2Orange40,
            tagTextWarningNegative: palette.o2Orange40,
            tagTextWarningBrand: palette.o2Orange40,
            tagTextErrorInverse: palette.pepper40,
            tagTextErrorNegative: palette.pepper40,
            tagTextErrorBrand: palette.pepper40,
            tagBackgroundPromoInverse: palette.darkModeGrey6,
            tagBackgroundPromoNegative: palette.darkModeGrey6,
            tagBackgroundPromoBrand: palette.darkModeGrey6,
            tagBackgroundActiveInverse: palette.darkModeGrey6,
            tagBackgroundActiveNegative: palette.darkModeGrey6,
            tagBackgroundActiveBrand: palette.darkModeGrey6,
            tagBackgroundInactiveInverse: palette.darkModeGrey6,
            tagBackgroundInactiveNegative: palette.darkModeGrey6,
            tagBackgroundInactiveBrand: palette.darkModeGrey6,
            tagBackgroundInfoInverse: palette.darkModeGrey6,
            tagBackgroundInfoNegative: palette.darkModeGrey6,
            tagBackgroundInfoBrand: palette.darkModeGrey6,
            tagBackgroundSuccessInverse: palette.darkModeGrey6,
            tagBackgroundSuccessNegative: palette.darkModeGrey6,
            tagBackgroundSuccessBrand: palette.darkModeGrey6,
            tagBackgroundWarningInverse: palette.darkModeGrey6,
            tagBackgroundWarningNegative: palette.darkModeGrey6,
            tagBackgroundWarningBrand: palette.darkModeGrey6,
            tagBackgroundErrorInverse: palette.darkModeGrey6,
            tagBackgroundErrorNegative: palette.darkModeGrey6,
            tagBackgroundErrorBrand: palette.darkModeGrey6,
            cardContentOverlay: `linear-gradient(180deg, ${applyAlpha(palette.black, 0)} 0%, ${applyAlpha(palette.black, 0.4)} 30%, ${applyAlpha(palette.black, 0.7)} 100%)`,
            cardFooterOverlay: applyAlpha(palette.black, 0.7),
        },
        borderRadii: {
            avatar: '50%',
            bar: '999px',
            button: '4px',
            checkbox: '2px',
            container: '8px',
            indicator: '24px',
            chip: '24px',
            tag: '24px',
            input: '8px',
            legacyDisplay: '16px',
            popup: '8px',
            sheet: '8px',
            mediaSmall: '8px',
        },
        textPresets: {
            button: {weight: 'medium'},
            cardTitle: {weight: 'regular'},
            chipLabel: {
                lineHeight: {desktop: 24, mobile: 20},
                size: {desktop: 16, mobile: 14},
                weight: 'medium',
            },
            indicator: {weight: 'medium'},
            inputHelperText: {lineHeight: {desktop: 20, mobile: 16}, size: {desktop: 14, mobile: 12}},
            inputLabel: {lineHeight: {desktop: 20, mobile: 16}, size: {desktop: 14, mobile: 12}},
            inputValue: {lineHeight: {desktop: 24, mobile: 24}, size: {desktop: 18, mobile: 16}},
            link: {weight: 'medium'},
            loadingScreenTitle: {lineHeight: {desktop: 28, mobile: 24}, size: {desktop: 20, mobile: 18}},
            navigationBar: {weight: 'medium'},
            rowTitle: {weight: 'regular'},
            stepperStepLabel: {lineHeight: {desktop: 24, mobile: 20}, size: {desktop: 16, mobile: 14}},
            tabsLabel: {
                lineHeight: {desktop: 24, mobile: 24},
                size: {desktop: 18, mobile: 16},
                weight: 'medium',
            },
            text1: {lineHeight: {desktop: 20, mobile: 16}, size: {desktop: 14, mobile: 12}},
            text2: {lineHeight: {desktop: 24, mobile: 20}, size: {desktop: 16, mobile: 14}},
            text3: {lineHeight: {desktop: 24, mobile: 24}, size: {desktop: 18, mobile: 16}},
            text4: {lineHeight: {desktop: 28, mobile: 24}, size: {desktop: 20, mobile: 18}},
            text5: {lineHeight: {desktop: 32, mobile: 24}, size: {desktop: 28, mobile: 20}, weight: 'light'},
            text6: {lineHeight: {desktop: 40, mobile: 32}, size: {desktop: 32, mobile: 24}, weight: 'light'},
            text7: {lineHeight: {desktop: 48, mobile: 32}, size: {desktop: 40, mobile: 28}, weight: 'light'},
            text8: {lineHeight: {desktop: 56, mobile: 40}, size: {desktop: 48, mobile: 32}, weight: 'light'},
            text9: {lineHeight: {desktop: 64, mobile: 48}, size: {desktop: 56, mobile: 40}, weight: 'light'},
            text10: {lineHeight: {desktop: 72, mobile: 56}, size: {desktop: 64, mobile: 48}, weight: 'light'},
            title1: {
                lineHeight: {desktop: 20, mobile: 16},
                size: {desktop: 14, mobile: 12},
                weight: 'medium',
            },
            title2: {lineHeight: {desktop: 24, mobile: 24}, size: {desktop: 18, mobile: 16}, weight: 'light'},
            title3: {lineHeight: {desktop: 32, mobile: 24}, size: {desktop: 28, mobile: 20}, weight: 'light'},
            title4: {lineHeight: {desktop: 40, mobile: 32}, size: {desktop: 32, mobile: 24}, weight: 'light'},
        },
        themeVariants: {
            successFeedback: 'inverse',
            brandLoadingScreen: 'inverse',
        },
    };
    return skin;
};
