import {createThemeContract} from '@vanilla-extract/css';

import type {BorderRadiiConfig, Colors} from './types';

const colors: Colors = {
    appBarBackground: '',
    background: '',
    backgroundAlternative: '',
    backgroundBrand: '',
    backgroundBrandBottom: '',
    backgroundBrandSecondary: '',
    backgroundBrandTop: '',
    backgroundContainer: '',
    backgroundContainerAlternative: '',
    backgroundContainerBrand: '',
    backgroundContainerBrandHover: '',
    backgroundContainerBrandOverBrand: '',
    backgroundContainerBrandOverInverse: '',
    backgroundContainerBrandPressed: '',
    backgroundContainerError: '',
    backgroundContainerHover: '',
    backgroundContainerNegative: '',
    backgroundContainerPressed: '',
    backgroundNegative: '',
    backgroundOverlay: '',
    backgroundSkeleton: '',
    backgroundSkeletonBrand: '',
    backgroundSkeletonInverse: '',
    backgroundSkeletonNegative: '',
    badge: '',
    barTrack: '',
    barTrackBrand: '',
    barTrackInverse: '',
    barTrackNegative: '',
    border: '',
    borderHigh: '',
    borderLow: '',
    borderSelected: '',
    brand: '',
    brandHigh: '',
    brandLow: '',
    buttonDangerBackground: '',
    buttonDangerBackgroundHover: '',
    buttonDangerBackgroundPressed: '',
    buttonLinkBackgroundBrandPressed: '',
    buttonLinkBackgroundInversePressed: '',
    buttonLinkBackgroundMediaPressed: '',
    buttonLinkBackgroundNegativePressed: '',
    buttonLinkBackgroundPressed: '',
    buttonLinkDangerBackgroundBrand: '',
    buttonLinkDangerBackgroundBrandPressed: '',
    buttonLinkDangerBackgroundInverse: '',
    buttonLinkDangerBackgroundInversePressed: '',
    buttonLinkDangerBackgroundMedia: '',
    buttonLinkDangerBackgroundMediaPressed: '',
    buttonLinkDangerBackgroundNegative: '',
    buttonLinkDangerBackgroundNegativePressed: '',
    buttonLinkDangerBackgroundPressed: '',
    buttonPrimaryBackground: '',
    buttonPrimaryBackgroundBrand: '',
    buttonPrimaryBackgroundBrandHover: '',
    buttonPrimaryBackgroundBrandPressed: '',
    buttonPrimaryBackgroundHover: '',
    buttonPrimaryBackgroundInverse: '',
    buttonPrimaryBackgroundInverseHover: '',
    buttonPrimaryBackgroundInversePressed: '',
    buttonPrimaryBackgroundMedia: '',
    buttonPrimaryBackgroundMediaHover: '',
    buttonPrimaryBackgroundMediaPressed: '',
    buttonPrimaryBackgroundNegative: '',
    buttonPrimaryBackgroundNegativeHover: '',
    buttonPrimaryBackgroundNegativePressed: '',
    buttonPrimaryBackgroundPressed: '',
    buttonSecondaryBackgroundBrand: '',
    buttonSecondaryBackgroundBrandHover: '',
    buttonSecondaryBackgroundBrandPressed: '',
    buttonSecondaryBackgroundHover: '',
    buttonSecondaryBackgroundInverseHover: '',
    buttonSecondaryBackgroundInversePressed: '',
    buttonSecondaryBackgroundMediaHover: '',
    buttonSecondaryBackgroundMediaPressed: '',
    buttonSecondaryBackgroundNegativeHover: '',
    buttonSecondaryBackgroundNegativePressed: '',
    buttonSecondaryBackgroundPressed: '',
    buttonSecondaryBorder: '',
    buttonSecondaryBorderBrand: '',
    buttonSecondaryBorderBrandPressed: '',
    buttonSecondaryBorderInverse: '',
    buttonSecondaryBorderInversePressed: '',
    buttonSecondaryBorderMedia: '',
    buttonSecondaryBorderMediaPressed: '',
    buttonSecondaryBorderNegative: '',
    buttonSecondaryBorderNegativePressed: '',
    buttonSecondaryBorderPressed: '',
    cardContentOverlay: '',
    cardFooterOverlay: '',
    chevronIndicator: '',
    completedStep: '',
    completedStepBrand: '',
    completedStepInverse: '',
    completedStepNegative: '',
    control: '',
    controlActivated: '',
    controlActivatedBrand: '',
    controlActivatedInverse: '',
    controlActivatedNegative: '',
    controlBrand: '',
    controlError: '',
    controlInverse: '',
    controlKnobBrand: '',
    controlKnobInverse: '',
    controlKnobNegative: '',
    controlNegative: '',
    coverBackgroundHover: '',
    coverBackgroundPressed: '',
    customTabsBackground: '',
    divider: '',
    dividerBrand: '',
    dividerInverse: '',
    dividerNegative: '',
    error: '',
    errorHigh: '',
    errorHighBrand: '',
    errorHighInverse: '',
    errorHighNegative: '',
    errorLow: '',
    feedbackErrorBackground: '',
    feedbackInfoBackground: '',
    highlight: '',
    inputBorder: '',
    inputBorderBrand: '',
    inputBorderInverse: '',
    inputBorderNegative: '',
    inverse: '',
    iosControlKnob: '',
    loadingBar: '',
    loadingBarBackground: '',
    navigationBarBackground: '',
    navigationBarDivider: '',
    negative: '',
    neutralHigh: '',
    neutralLow: '',
    neutralLowAlternative: '',
    neutralMedium: '',
    neutralMediumBrand: '',
    neutralMediumInverse: '',
    neutralMediumNegative: '',
    promo: '',
    promoHigh: '',
    promoHighBrand: '',
    promoHighInverse: '',
    promoHighNegative: '',
    promoLow: '',
    skeletonWave: '',
    success: '',
    successHigh: '',
    successHighBrand: '',
    successHighInverse: '',
    successHighNegative: '',
    successLow: '',
    tagBackgroundActive: '',
    tagBackgroundActiveBrand: '',
    tagBackgroundActiveInverse: '',
    tagBackgroundActiveNegative: '',
    tagBackgroundError: '',
    tagBackgroundErrorBrand: '',
    tagBackgroundErrorInverse: '',
    tagBackgroundErrorNegative: '',
    tagBackgroundInactive: '',
    tagBackgroundInactiveBrand: '',
    tagBackgroundInactiveInverse: '',
    tagBackgroundInactiveNegative: '',
    tagBackgroundInfo: '',
    tagBackgroundInfoBrand: '',
    tagBackgroundInfoInverse: '',
    tagBackgroundInfoNegative: '',
    tagBackgroundPromo: '',
    tagBackgroundPromoBrand: '',
    tagBackgroundPromoInverse: '',
    tagBackgroundPromoNegative: '',
    tagBackgroundSuccess: '',
    tagBackgroundSuccessBrand: '',
    tagBackgroundSuccessInverse: '',
    tagBackgroundSuccessNegative: '',
    tagBackgroundWarning: '',
    tagBackgroundWarningBrand: '',
    tagBackgroundWarningInverse: '',
    tagBackgroundWarningNegative: '',
    tagTextActive: '',
    tagTextActiveBrand: '',
    tagTextActiveInverse: '',
    tagTextActiveNegative: '',
    tagTextError: '',
    tagTextErrorBrand: '',
    tagTextErrorInverse: '',
    tagTextErrorNegative: '',
    tagTextInactive: '',
    tagTextInactiveBrand: '',
    tagTextInactiveInverse: '',
    tagTextInactiveNegative: '',
    tagTextInfo: '',
    tagTextInfoBrand: '',
    tagTextInfoInverse: '',
    tagTextInfoNegative: '',
    tagTextPromo: '',
    tagTextPromoBrand: '',
    tagTextPromoInverse: '',
    tagTextPromoNegative: '',
    tagTextSuccess: '',
    tagTextSuccessBrand: '',
    tagTextSuccessInverse: '',
    tagTextSuccessNegative: '',
    tagTextWarning: '',
    tagTextWarningBrand: '',
    tagTextWarningInverse: '',
    tagTextWarningNegative: '',
    textActivated: '',
    textAppBar: '',
    textAppBarSelected: '',
    textBrand: '',
    textButtonPrimary: '',
    textButtonPrimaryBrand: '',
    textButtonPrimaryBrandPressed: '',
    textButtonPrimaryInverse: '',
    textButtonPrimaryInversePressed: '',
    textButtonPrimaryMedia: '',
    textButtonPrimaryMediaPressed: '',
    textButtonPrimaryNegative: '',
    textButtonPrimaryNegativePressed: '',
    textButtonSecondary: '',
    textButtonSecondaryBrand: '',
    textButtonSecondaryBrandPressed: '',
    textButtonSecondaryInverse: '',
    textButtonSecondaryInversePressed: '',
    textButtonSecondaryMedia: '',
    textButtonSecondaryMediaPressed: '',
    textButtonSecondaryNegative: '',
    textButtonSecondaryNegativePressed: '',
    textButtonSecondaryPressed: '',
    textError: '',
    textErrorBrand: '',
    textErrorInverse: '',
    textErrorNegative: '',
    textLink: '',
    textLinkBrand: '',
    textLinkDanger: '',
    textLinkDangerMedia: '',
    textLinkInverse: '',
    textLinkMedia: '',
    textLinkNegative: '',
    textLinkSnackbar: '',
    textNavigationBarPrimary: '',
    textNavigationBarSecondary: '',
    textNavigationSearchBarHint: '',
    textNavigationSearchBarText: '',
    textPrimary: '',
    textPrimaryBrand: '',
    textPrimaryInverse: '',
    textPrimaryMedia: '',
    textPrimaryNegative: '',
    textSecondary: '',
    textSecondaryBrand: '',
    textSecondaryInverse: '',
    textSecondaryMedia: '',
    textSecondaryNegative: '',
    toggleAndroidActiveBrand: '',
    toggleAndroidBackgroundActive: '',
    toggleAndroidBackgroundActiveBrand: '',
    toggleAndroidBackgroundInactiveBrand: '',
    toggleAndroidInactive: '',
    toggleAndroidInactiveBrand: '',
    warning: '',
    warningHigh: '',
    warningHighBrand: '',
    warningHighInverse: '',
    warningHighNegative: '',
    warningLow: '',
};

const borderRadii: BorderRadiiConfig = {
    button: '',
    input: '',
    container: '',
    legacyDisplay: '',
    popup: '',
    checkbox: '',
    indicator: '',
    chip: '',
    sheet: '',
    bar: '',
    avatar: '',
    mediaSmall: '',
    tag: '',
};

const textPresets = {
    cardTitle: {weight: ''},
    rowTitle: {weight: ''},
    button: {weight: ''},
    link: {weight: ''},
    title1: {weight: ''},
    title2: {weight: ''},
    title3: {weight: '', size: '', lineHeight: ''},
    indicator: {weight: ''},
    tabsLabel: {weight: '', size: '', lineHeight: ''},
    navigationBar: {weight: ''},
    text1: {size: '', lineHeight: ''},
    text2: {size: '', lineHeight: ''},
    text3: {size: '', lineHeight: ''},
    text4: {size: '', lineHeight: ''},
    text5: {weight: '', size: '', lineHeight: ''},
    text6: {weight: '', size: '', lineHeight: ''},
    text7: {weight: '', size: '', lineHeight: ''},
    text8: {weight: '', size: '', lineHeight: ''},
    text9: {weight: '', size: '', lineHeight: ''},
    text10: {weight: '', size: '', lineHeight: ''},
};

export const vars = createThemeContract({
    colors,
    /**
     * Raw colors are defined as rgb components to allow applying alpha channel when using the css var
     * See ThemeContextProvider, where the colors provided in the themeConfig are transformed into rgb components
     * See utils/color.tsx applyAlha, where the alpha channel is applied to the css var
     */
    rawColors: colors,
    borderRadii,
    textPresets,
});
