import {TELEFONICA_SKIN} from './constants';
import {applyAlpha} from '../utils/color';

import type {GetKnownSkin, KnownSkin} from './types';

export const palette = {
    telefonicaBlue: '#0066FF',
    telefonicaBlue10: '#E5F0FF',
    telefonicaBlue20: '#B2D1FF',
    telefonicaBlue30: '#80B3FF',
    telefonicaBlue70: '#0356C9',
    telefonicaBlue80: '#002E73',
    ambar: '#EAC344',
    ambar10: '#FDF9EC',
    ambar40: '#F0D57C',
    ambar70: '#69581F',
    yellow: '#e4c35c',
    yellow15: '#fcf7db',
    yellow40: '#f3e996',
    yellow70: '#a7863e',
    yellow80: '#473515',
    coral: '#d6786b',
    coral10: '#f9eeed',
    coral30: '#f2b1a5',
    coral60: '#D22A1E',
    coral65: '#C82C1E',
    coral80: '#843c34',
    coral90: '#491818',
    orchid: '#b86be8',
    orchid10: '#F8F0FD',
    orchid40: '#CD97EF',
    orchid70: '#7f258e',
    orchid80: '#471551',
    turquoise: '#75c0c7',
    turquoise10: '#ebffff',
    turquoise40: '#9ED3D8',
    turquoise70: '#528889',
    turquoise80: '#253d3c',
    grey1: '#F7F7FF',
    grey2: '#D1D5E4',
    grey3: '#B0B6CA',
    grey4: '#8f97af',
    grey5: '#6E7894',
    grey6: '#58617A',
    grey7: '#414B61',
    grey8: '#2B3447',
    grey9: '#031A34',
    white: '#FFFFFF',
    black: '#000000',
    darkModeBlack: '#000522',
    darkModeGrey: '#00182F',
    darkModeGrey6: '#00264D',
    darkModeTelefonicaBlue: '#227AFF',
};

export const getTelefonicaSkin: GetKnownSkin = () => {
    const skin: KnownSkin = {
        name: TELEFONICA_SKIN,
        colors: {
            appBarBackground: palette.white,
            background: palette.white,
            backgroundContainer: palette.white,
            backgroundContainerError: palette.coral10,
            backgroundContainerHover: applyAlpha(palette.telefonicaBlue70, 0.05),
            backgroundContainerPressed: applyAlpha(palette.telefonicaBlue70, 0.08),
            backgroundContainerBrand: palette.telefonicaBlue,
            backgroundContainerBrandHover: applyAlpha(palette.darkModeBlack, 0.2),
            backgroundContainerBrandPressed: applyAlpha(palette.darkModeBlack, 0.4),
            backgroundContainerBrandOverInverse: palette.telefonicaBlue70,
            backgroundContainerAlternative: palette.grey1,
            backgroundBrand: palette.telefonicaBlue,
            backgroundBrandSecondary: palette.telefonicaBlue,
            backgroundOverlay: applyAlpha(palette.grey6, 0.8),
            backgroundSkeleton: palette.grey2,
            backgroundSkeletonInverse: palette.telefonicaBlue70,
            navigationBarBackground: palette.telefonicaBlue,
            backgroundAlternative: palette.grey1,
            backgroundBrandTop: palette.telefonicaBlue,
            backgroundBrandBottom: palette.telefonicaBlue,
            skeletonWave: palette.grey2,
            borderLow: palette.grey1,
            border: palette.grey2,
            borderHigh: palette.grey5,
            borderSelected: palette.telefonicaBlue,
            coverBackgroundHover: applyAlpha(palette.darkModeBlack, 0.25),
            coverBackgroundPressed: applyAlpha(palette.darkModeBlack, 0.35),
            buttonDangerBackground: palette.coral60,
            buttonDangerBackgroundPressed: palette.coral65,
            buttonDangerBackgroundHover: palette.coral65,
            buttonLinkDangerBackgroundInverse: palette.white,
            buttonLinkDangerBackgroundMedia: palette.white,
            buttonLinkDangerBackgroundPressed: palette.coral10,
            buttonLinkDangerBackgroundInversePressed: palette.coral10,
            buttonLinkDangerBackgroundMediaPressed: palette.coral10,
            buttonLinkBackgroundPressed: palette.grey1,
            buttonLinkBackgroundInversePressed: applyAlpha(palette.white, 0.08),
            buttonLinkBackgroundMediaPressed: applyAlpha(palette.white, 0.08),
            buttonPrimaryBackground: palette.telefonicaBlue,
            buttonPrimaryBackgroundInverse: palette.white,
            buttonPrimaryBackgroundMedia: palette.white,
            buttonPrimaryBackgroundHover: palette.telefonicaBlue70,
            buttonPrimaryBackgroundInverseHover: palette.telefonicaBlue10,
            buttonPrimaryBackgroundMediaHover: palette.telefonicaBlue10,
            buttonPrimaryBackgroundPressed: palette.telefonicaBlue70,
            buttonPrimaryBackgroundInversePressed: palette.telefonicaBlue10,
            buttonPrimaryBackgroundMediaPressed: palette.telefonicaBlue10,
            buttonSecondaryBorder: palette.telefonicaBlue,
            buttonSecondaryBorderInverse: palette.white,
            buttonSecondaryBorderMedia: palette.white,
            buttonSecondaryBorderPressed: palette.telefonicaBlue70,
            buttonSecondaryBorderInversePressed: palette.white,
            buttonSecondaryBorderMediaPressed: palette.white,
            buttonSecondaryBackgroundHover: palette.telefonicaBlue10,
            buttonSecondaryBackgroundInverseHover: applyAlpha(palette.white, 0.1),
            buttonSecondaryBackgroundMediaHover: applyAlpha(palette.white, 0.1),
            buttonSecondaryBackgroundPressed: palette.telefonicaBlue10,
            buttonSecondaryBackgroundInversePressed: applyAlpha(palette.white, 0.1),
            buttonSecondaryBackgroundMediaPressed: applyAlpha(palette.white, 0.1),
            textButtonPrimary: palette.white,
            textButtonPrimaryInverse: palette.telefonicaBlue,
            textButtonPrimaryMedia: palette.telefonicaBlue,
            textButtonPrimaryInversePressed: palette.telefonicaBlue70,
            textButtonPrimaryMediaPressed: palette.telefonicaBlue70,
            textButtonSecondary: palette.telefonicaBlue,
            textButtonSecondaryInverse: palette.white,
            textButtonSecondaryMedia: palette.white,
            textButtonSecondaryPressed: palette.telefonicaBlue70,
            textButtonSecondaryInversePressed: palette.white,
            textButtonSecondaryMediaPressed: palette.white,
            textLink: palette.telefonicaBlue,
            textLinkInverse: palette.white,
            textLinkMedia: palette.white,
            textLinkDanger: palette.coral60,
            textLinkDangerMedia: palette.coral60,
            textLinkSnackbar: palette.telefonicaBlue30,
            textActivated: palette.telefonicaBlue70,
            textBrand: palette.telefonicaBlue70,
            inputBorder: palette.grey5,
            inputBorderInverse: palette.white,
            completedStep: palette.telefonicaBlue,
            completedStepInverse: palette.telefonicaBlue70,
            control: palette.grey5,
            controlActivated: palette.telefonicaBlue,
            controlInverse: palette.grey1,
            controlActivatedInverse: palette.white,
            controlError: palette.coral60,
            barTrack: palette.grey2,
            barTrackInverse: applyAlpha(palette.white, 0.3),
            loadingBar: palette.telefonicaBlue30,
            loadingBarBackground: palette.telefonicaBlue70,
            toggleAndroidInactive: palette.grey2,
            toggleAndroidBackgroundActive: palette.grey2,
            iosControlKnob: palette.white,
            controlKnobInverse: palette.telefonicaBlue,
            divider: palette.grey2,
            dividerInverse: applyAlpha(palette.white, 0.2),
            navigationBarDivider: palette.telefonicaBlue,
            badge: palette.coral60,
            feedbackErrorBackground: palette.coral60,
            feedbackInfoBackground: palette.grey9,
            brand: palette.telefonicaBlue,
            brandHigh: palette.telefonicaBlue70,
            inverse: palette.white,
            neutralHigh: palette.grey9,
            neutralMedium: palette.grey5,
            neutralMediumInverse: palette.grey5,
            neutralLow: palette.grey1,
            neutralLowAlternative: palette.grey2,
            textPrimary: palette.grey9,
            textPrimaryInverse: palette.white,
            textPrimaryMedia: palette.white,
            textSecondary: palette.grey6,
            textSecondaryInverse: palette.white,
            textSecondaryMedia: palette.white,
            error: palette.coral60,
            textError: palette.coral60,
            textErrorInverse: palette.white,
            success: palette.turquoise,
            warning: palette.yellow70,
            promo: palette.orchid,
            highlight: palette.coral30,
            successLow: palette.turquoise10,
            warningLow: palette.yellow15,
            errorLow: palette.coral10,
            promoLow: palette.orchid10,
            brandLow: palette.telefonicaBlue10,
            successHigh: palette.turquoise70,
            warningHigh: palette.yellow70,
            errorHigh: palette.coral65,
            promoHigh: palette.orchid70,
            successHighInverse: palette.turquoise70,
            warningHighInverse: palette.yellow70,
            errorHighInverse: palette.coral65,
            promoHighInverse: palette.orchid70,
            textNavigationBarPrimary: palette.white,
            textNavigationBarSecondary: palette.grey1,
            textNavigationSearchBarHint: palette.grey1,
            textNavigationSearchBarText: palette.white,
            textAppBar: palette.grey4,
            textAppBarSelected: palette.telefonicaBlue70,
            customTabsBackground: palette.telefonicaBlue70,
            tagTextPromo: palette.orchid80,
            tagTextActive: palette.telefonicaBlue70,
            tagTextInactive: palette.grey6,
            tagTextInfo: palette.telefonicaBlue70,
            tagTextSuccess: palette.turquoise80,
            tagTextWarning: palette.yellow80,
            tagTextError: palette.coral65,
            tagBackgroundPromo: palette.orchid10,
            tagBackgroundActive: palette.grey1,
            tagBackgroundInactive: palette.grey1,
            tagBackgroundInfo: palette.telefonicaBlue10,
            tagBackgroundSuccess: palette.turquoise10,
            tagBackgroundWarning: palette.yellow15,
            tagBackgroundError: palette.coral10,
            tagTextPromoInverse: palette.orchid80,
            tagTextActiveInverse: palette.telefonicaBlue70,
            tagTextInactiveInverse: palette.grey6,
            tagTextInfoInverse: palette.telefonicaBlue70,
            tagTextSuccessInverse: palette.turquoise80,
            tagTextWarningInverse: palette.yellow80,
            tagTextErrorInverse: palette.coral65,
            tagBackgroundPromoInverse: palette.orchid10,
            tagBackgroundActiveInverse: palette.grey1,
            tagBackgroundInactiveInverse: palette.grey1,
            tagBackgroundInfoInverse: palette.telefonicaBlue10,
            tagBackgroundSuccessInverse: palette.turquoise10,
            tagBackgroundWarningInverse: palette.yellow15,
            tagBackgroundErrorInverse: palette.coral10,
            cardContentOverlay: `linear-gradient(180deg, ${applyAlpha(palette.black, 0)} 0%, ${applyAlpha(palette.black, 0.4)} 30%, ${applyAlpha(palette.black, 0.7)} 100%)`,
            cardFooterOverlay: applyAlpha(palette.black, 0.7),
        },
        darkModeColors: {
            background: palette.darkModeBlack,
            backgroundAlternative: palette.darkModeBlack,
            backgroundBrand: palette.darkModeBlack,
            backgroundBrandSecondary: palette.darkModeBlack,
            backgroundContainer: palette.darkModeGrey,
            backgroundContainerError: palette.darkModeGrey,
            backgroundContainerHover: applyAlpha(palette.telefonicaBlue70, 0.05),
            backgroundContainerPressed: applyAlpha(palette.telefonicaBlue70, 0.08),
            backgroundContainerBrand: palette.darkModeGrey,
            backgroundContainerBrandHover: applyAlpha(palette.white, 0.03),
            backgroundContainerBrandPressed: applyAlpha(palette.white, 0.05),
            backgroundContainerBrandOverInverse: palette.darkModeGrey,
            backgroundContainerAlternative: palette.darkModeGrey,
            backgroundOverlay: applyAlpha(palette.darkModeGrey, 0.8),
            backgroundSkeleton: palette.grey8,
            backgroundSkeletonInverse: palette.grey8,
            backgroundBrandTop: palette.darkModeBlack,
            backgroundBrandBottom: palette.darkModeBlack,
            appBarBackground: palette.darkModeGrey,
            navigationBarBackground: palette.darkModeBlack,
            skeletonWave: palette.grey8,
            borderLow: palette.darkModeBlack,
            border: palette.darkModeGrey,
            borderHigh: palette.grey5,
            borderSelected: palette.darkModeTelefonicaBlue,
            coverBackgroundHover: applyAlpha(palette.darkModeBlack, 0.25),
            coverBackgroundPressed: applyAlpha(palette.darkModeBlack, 0.35),
            buttonDangerBackground: palette.coral60,
            buttonDangerBackgroundPressed: palette.coral65,
            buttonDangerBackgroundHover: palette.coral65,
            buttonLinkDangerBackgroundInverse: applyAlpha(palette.coral60, 0.16),
            buttonLinkDangerBackgroundMedia: palette.white,
            buttonLinkDangerBackgroundPressed: applyAlpha(palette.coral60, 0.16),
            buttonLinkDangerBackgroundInversePressed: applyAlpha(palette.coral60, 0.16),
            buttonLinkDangerBackgroundMediaPressed: palette.coral10,
            buttonLinkBackgroundPressed: applyAlpha(palette.telefonicaBlue30, 0.16),
            buttonLinkBackgroundInversePressed: applyAlpha(palette.telefonicaBlue30, 0.16),
            buttonLinkBackgroundMediaPressed: applyAlpha(palette.white, 0.08),
            buttonPrimaryBackground: palette.telefonicaBlue,
            buttonPrimaryBackgroundInverse: palette.white,
            buttonPrimaryBackgroundMedia: palette.white,
            buttonPrimaryBackgroundHover: palette.telefonicaBlue70,
            buttonPrimaryBackgroundInverseHover: palette.telefonicaBlue10,
            buttonPrimaryBackgroundMediaHover: palette.telefonicaBlue10,
            buttonPrimaryBackgroundPressed: palette.telefonicaBlue70,
            buttonPrimaryBackgroundInversePressed: palette.telefonicaBlue10,
            buttonPrimaryBackgroundMediaPressed: palette.telefonicaBlue10,
            buttonSecondaryBorder: palette.white,
            buttonSecondaryBorderInverse: palette.white,
            buttonSecondaryBorderMedia: palette.white,
            buttonSecondaryBorderPressed: palette.white,
            buttonSecondaryBorderInversePressed: palette.white,
            buttonSecondaryBorderMediaPressed: palette.white,
            buttonSecondaryBackgroundHover: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundInverseHover: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundMediaHover: applyAlpha(palette.white, 0.1),
            buttonSecondaryBackgroundPressed: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundInversePressed: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundMediaPressed: applyAlpha(palette.white, 0.1),
            textButtonPrimary: palette.white,
            textButtonPrimaryInverse: palette.telefonicaBlue,
            textButtonPrimaryMedia: palette.telefonicaBlue,
            textButtonPrimaryInversePressed: palette.telefonicaBlue70,
            textButtonPrimaryMediaPressed: palette.telefonicaBlue70,
            textButtonSecondary: palette.white,
            textButtonSecondaryInverse: palette.white,
            textButtonSecondaryMedia: palette.white,
            textButtonSecondaryPressed: palette.white,
            textButtonSecondaryInversePressed: palette.white,
            textButtonSecondaryMediaPressed: palette.white,
            textLink: palette.darkModeTelefonicaBlue,
            textLinkInverse: palette.darkModeTelefonicaBlue,
            textLinkMedia: palette.white,
            textLinkDanger: palette.coral,
            textLinkDangerMedia: palette.coral60,
            textLinkSnackbar: palette.darkModeTelefonicaBlue,
            textActivated: palette.telefonicaBlue30,
            textBrand: palette.telefonicaBlue30,
            inputBorder: palette.grey5,
            inputBorderInverse: palette.grey5,
            completedStep: palette.telefonicaBlue,
            completedStepInverse: palette.telefonicaBlue,
            control: palette.grey5,
            controlActivated: palette.darkModeTelefonicaBlue,
            controlInverse: palette.grey5,
            controlActivatedInverse: palette.darkModeTelefonicaBlue,
            controlError: palette.coral,
            barTrack: palette.darkModeGrey6,
            barTrackInverse: palette.darkModeGrey6,
            loadingBar: palette.darkModeTelefonicaBlue,
            loadingBarBackground: palette.grey6,
            toggleAndroidInactive: palette.grey2,
            toggleAndroidBackgroundActive: palette.telefonicaBlue20,
            iosControlKnob: palette.grey1,
            controlKnobInverse: palette.grey1,
            divider: applyAlpha(palette.white, 0.2),
            dividerInverse: applyAlpha(palette.white, 0.05),
            navigationBarDivider: palette.darkModeBlack,
            badge: palette.coral60,
            feedbackErrorBackground: palette.coral65,
            feedbackInfoBackground: palette.darkModeGrey,
            brand: palette.darkModeTelefonicaBlue,
            brandHigh: applyAlpha(palette.white, 0.05),
            inverse: palette.grey1,
            neutralHigh: palette.grey2,
            neutralMedium: palette.grey5,
            neutralMediumInverse: palette.grey5,
            neutralLow: palette.darkModeGrey6,
            neutralLowAlternative: palette.darkModeGrey6,
            textPrimary: palette.grey1,
            textPrimaryInverse: palette.grey1,
            textPrimaryMedia: palette.white,
            textSecondary: palette.grey3,
            textSecondaryInverse: palette.grey3,
            textSecondaryMedia: palette.white,
            error: palette.coral,
            textError: palette.coral,
            textErrorInverse: palette.coral,
            success: palette.turquoise,
            warning: palette.yellow,
            promo: palette.orchid,
            highlight: palette.coral30,
            successLow: palette.darkModeGrey6,
            warningLow: palette.darkModeGrey6,
            errorLow: palette.darkModeGrey6,
            promoLow: palette.darkModeGrey6,
            brandLow: palette.darkModeGrey6,
            successHigh: palette.turquoise40,
            warningHigh: palette.yellow40,
            errorHigh: palette.coral30,
            promoHigh: palette.orchid40,
            successHighInverse: palette.turquoise70,
            warningHighInverse: palette.yellow70,
            errorHighInverse: palette.coral65,
            promoHighInverse: palette.orchid70,
            textNavigationBarPrimary: palette.white,
            textNavigationBarSecondary: palette.grey4,
            textNavigationSearchBarHint: palette.grey4,
            textNavigationSearchBarText: palette.white,
            textAppBar: palette.grey2,
            textAppBarSelected: palette.white,
            customTabsBackground: palette.darkModeBlack,
            tagTextPromo: palette.orchid40,
            tagTextActive: palette.telefonicaBlue20,
            tagTextInactive: palette.grey3,
            tagTextInfo: palette.telefonicaBlue20,
            tagTextSuccess: palette.turquoise40,
            tagTextWarning: palette.yellow40,
            tagTextError: palette.coral30,
            tagBackgroundPromo: palette.orchid80,
            tagBackgroundActive: palette.telefonicaBlue80,
            tagBackgroundInactive: palette.grey8,
            tagBackgroundInfo: palette.telefonicaBlue80,
            tagBackgroundSuccess: palette.turquoise80,
            tagBackgroundWarning: palette.yellow80,
            tagBackgroundError: palette.coral90,
            tagTextPromoInverse: palette.orchid40,
            tagTextActiveInverse: palette.telefonicaBlue20,
            tagTextInactiveInverse: palette.grey3,
            tagTextInfoInverse: palette.telefonicaBlue20,
            tagTextSuccessInverse: palette.turquoise40,
            tagTextWarningInverse: palette.yellow40,
            tagTextErrorInverse: palette.coral30,
            tagBackgroundPromoInverse: palette.orchid80,
            tagBackgroundActiveInverse: palette.telefonicaBlue80,
            tagBackgroundInactiveInverse: palette.grey8,
            tagBackgroundInfoInverse: palette.telefonicaBlue80,
            tagBackgroundSuccessInverse: palette.turquoise80,
            tagBackgroundWarningInverse: palette.yellow80,
            tagBackgroundErrorInverse: palette.coral90,
            cardContentOverlay: `linear-gradient(180deg, ${applyAlpha(palette.black, 0)} 0%, ${applyAlpha(palette.black, 0.4)} 30%, ${applyAlpha(palette.black, 0.7)} 100%)`,
            cardFooterOverlay: applyAlpha(palette.black, 0.7),
        },
        borderRadii: {
            avatar: '50%',
            bar: '0px',
            button: '32px',
            checkbox: '0px',
            container: '0px',
            indicator: '24px',
            chip: '24px',
            tag: '24px',
            input: '0px',
            legacyDisplay: '0px',
            popup: '0px',
            sheet: '0px',
            mediaSmall: '0px',
        },
        textPresets: {
            button: {weight: 'medium'},
            cardTitle: {weight: 'regular'},
            indicator: {weight: 'medium'},
            link: {weight: 'medium'},
            navigationBar: {weight: 'medium'},
            rowTitle: {weight: 'regular'},
            tabsLabel: {
                lineHeight: {desktop: 24, mobile: 24},
                size: {desktop: 18, mobile: 16},
                weight: 'medium',
            },
            text1: {lineHeight: {desktop: 20, mobile: 16}, size: {desktop: 14, mobile: 12}},
            text2: {lineHeight: {desktop: 24, mobile: 20}, size: {desktop: 16, mobile: 14}},
            text3: {lineHeight: {desktop: 24, mobile: 24}, size: {desktop: 18, mobile: 16}},
            text4: {lineHeight: {desktop: 28, mobile: 24}, size: {desktop: 20, mobile: 18}},
            text5: {
                lineHeight: {desktop: 32, mobile: 24},
                size: {desktop: 28, mobile: 20},
                weight: 'regular',
            },
            text6: {
                lineHeight: {desktop: 40, mobile: 32},
                size: {desktop: 32, mobile: 24},
                weight: 'regular',
            },
            text7: {
                lineHeight: {desktop: 48, mobile: 32},
                size: {desktop: 40, mobile: 28},
                weight: 'regular',
            },
            text8: {
                lineHeight: {desktop: 56, mobile: 40},
                size: {desktop: 48, mobile: 32},
                weight: 'regular',
            },
            text9: {
                lineHeight: {desktop: 64, mobile: 48},
                size: {desktop: 56, mobile: 40},
                weight: 'regular',
            },
            text10: {
                lineHeight: {desktop: 72, mobile: 56},
                size: {desktop: 64, mobile: 48},
                weight: 'regular',
            },
            title1: {weight: 'medium'},
            title2: {weight: 'regular'},
            title3: {
                lineHeight: {desktop: 32, mobile: 24},
                size: {desktop: 28, mobile: 20},
                weight: 'regular',
            },
        },
        themeVariants: {
            successFeedback: 'inverse',
            brandLoadingScreen: 'inverse',
        },
    };
    return skin;
};
