import {TU_SKIN} from './constants';
import {applyAlpha} from '../utils/color';

import type {GetKnownSkin, KnownSkin} from './types';

export const palette = {
    primary: '#2B3447',
    primary65: '#202735',
    primary80: '#161A24',
    secondary: '#4343FF',
    secondary10: '#ECECFF',
    secondary20: '#C7C7FF',
    secondary30: '#A1A1FF',
    secondary70: '#3232B9',
    orange: '#EFE384',
    orange20: '#FAF7DA',
    orange55: '#D5C77D',
    orange65: '#BBAF6F',
    orange70: '#958946',
    red: '#CB4D3A',
    red10: '#FAEDEB',
    red40: '#DB8275',
    red70: '#8E3629',
    red80: '#5B231A',
    purple: '#7274E7',
    purple10: '#F1F1FD',
    purple40: '#9C9EEE',
    purple70: '#5051A2',
    green: '#187189',
    green10: '#E8F1F3',
    green40: '#5D9CAC',
    green70: '#114F60',
    grey1: '#F0F1F5',
    grey2: '#E2E4EC',
    grey3: '#CBCFDE',
    grey4: '#999999',
    grey5: '#727579',
    grey6: '#2B3447',
    white: '#FFFFFF',
    darkModeBlack: '#161A24',
    darkModeGrey: '#202735',
    darkModeGrey6: '#2B3447',
};

export const getTuSkin: GetKnownSkin = () => {
    const skin: KnownSkin = {
        name: TU_SKIN,
        colors: {
            appBarBackground: palette.white,
            background: palette.white,
            backgroundContainer: palette.white,
            backgroundContainerHover: applyAlpha(palette.primary, 0.03),
            backgroundContainerPressed: applyAlpha(palette.primary, 0.05),
            backgroundContainerBrand: palette.primary,
            backgroundContainerBrandHover: applyAlpha(palette.darkModeBlack, 0.2),
            backgroundContainerBrandPressed: applyAlpha(palette.darkModeBlack, 0.4),
            backgroundContainerBrandOverInverse: palette.primary80,
            backgroundContainerAlternative: palette.grey1,
            backgroundBrand: palette.primary,
            backgroundBrandSecondary: palette.secondary,
            backgroundOverlay: applyAlpha(palette.primary, 0.8),
            backgroundSkeleton: palette.grey2,
            backgroundSkeletonInverse: palette.primary65,
            navigationBarBackground: palette.primary,
            backgroundAlternative: palette.grey1,
            backgroundFeedbackBottom: palette.primary,
            skeletonWave: palette.grey2,
            borderLow: palette.grey1,
            border: palette.grey3,
            borderHigh: palette.grey5,
            borderSelected: palette.secondary,
            coverBackgroundHover: applyAlpha(palette.darkModeBlack, 0.25),
            coverBackgroundPressed: applyAlpha(palette.darkModeBlack, 0.35),
            buttonDangerBackground: palette.red,
            buttonDangerBackgroundSelected: palette.red80,
            buttonDangerBackgroundHover: palette.red80,
            buttonLinkDangerBackgroundSelected: palette.red10,
            buttonLinkDangerBackgroundInverse: palette.white,
            buttonLinkDangerBackgroundInverseSelected: palette.red10,
            buttonLinkBackgroundSelected: palette.secondary10,
            buttonLinkBackgroundInverseSelected: applyAlpha(palette.white, 0.08),
            buttonPrimaryBackground: palette.secondary,
            buttonPrimaryBackgroundInverse: palette.white,
            buttonPrimaryBackgroundSelected: palette.secondary70,
            buttonPrimaryBackgroundHover: palette.secondary70,
            buttonPrimaryBackgroundInverseSelected: applyAlpha(palette.white, 0.8),
            buttonSecondaryBorder: palette.secondary,
            buttonSecondaryBorderSelected: palette.secondary70,
            buttonSecondaryBackgroundHover: palette.secondary10,
            buttonSecondaryBackgroundSelected: palette.secondary10,
            buttonSecondaryBorderInverse: palette.white,
            buttonSecondaryBorderInverseSelected: palette.white,
            buttonSecondaryBackgroundInverseHover: applyAlpha(palette.white, 0.1),
            buttonSecondaryBackgroundInverseSelected: applyAlpha(palette.white, 0.1),
            textButtonPrimary: palette.white,
            textButtonPrimaryInverse: palette.primary,
            textButtonPrimaryInverseSelected: palette.primary,
            textButtonSecondary: palette.secondary,
            textButtonSecondarySelected: palette.secondary70,
            textButtonSecondaryInverse: palette.white,
            textButtonSecondaryInverseSelected: palette.white,
            textLink: palette.secondary,
            textLinkInverse: palette.white,
            textLinkDanger: palette.red,
            textLinkSnackbar: palette.secondary30,
            control: palette.grey3,
            controlActivated: palette.secondary,
            controlInverse: palette.white,
            controlActivatedInverse: palette.white,
            controlError: palette.red,
            loadingBar: palette.secondary30,
            loadingBarBackground: palette.secondary70,
            toggleAndroidInactive: palette.grey2,
            toggleAndroidBackgroundActive: palette.secondary20,
            iosControlKnob: palette.white,
            divider: palette.grey2,
            dividerInverse: applyAlpha(palette.white, 0.2),
            navigationBarDivider: palette.secondary,
            badge: palette.red70,
            feedbackErrorBackground: palette.red,
            feedbackInfoBackground: palette.grey6,
            brand: palette.secondary,
            brandHigh: palette.secondary70,
            brandLow: palette.secondary10,
            inverse: palette.white,
            neutralHigh: palette.grey6,
            neutralMedium: palette.grey5,
            neutralMediumInverse: palette.grey5,
            neutralLow: palette.grey1,
            neutralLowAlternative: palette.grey2,
            textPrimary: palette.grey6,
            textPrimaryInverse: palette.white,
            textSecondary: palette.grey5,
            textSecondaryInverse: palette.secondary10,
            error: palette.red,
            success: palette.green,
            warning: palette.orange,
            promo: palette.secondary,
            highlight: palette.red40,
            successLow: palette.green10,
            warningLow: palette.orange20,
            errorLow: palette.red10,
            promoLow: palette.secondary10,
            successHigh: palette.green70,
            warningHigh: palette.orange70,
            errorHigh: palette.red70,
            promoHigh: palette.secondary,
            successHighInverse: palette.green70,
            warningHighInverse: palette.orange70,
            errorHighInverse: palette.red70,
            promoHighInverse: palette.secondary,
            textNavigationBarPrimary: palette.white,
            textNavigationBarSecondary: palette.grey1,
            textNavigationSearchBarHint: palette.grey1,
            textNavigationSearchBarText: palette.white,
            textAppBar: palette.grey4,
            textAppBarSelected: palette.secondary,
            customTabsBackground: palette.secondary,
        },
        darkModeColors: {
            background: palette.darkModeBlack,
            backgroundAlternative: palette.darkModeBlack,
            backgroundBrand: palette.darkModeBlack,
            backgroundBrandSecondary: palette.darkModeBlack,
            backgroundContainer: palette.darkModeGrey,
            backgroundContainerHover: applyAlpha(palette.white, 0.03),
            backgroundContainerPressed: applyAlpha(palette.white, 0.05),
            backgroundContainerBrand: palette.darkModeGrey,
            backgroundContainerBrandHover: applyAlpha(palette.white, 0.03),
            backgroundContainerBrandPressed: applyAlpha(palette.white, 0.05),
            backgroundContainerBrandOverInverse: palette.darkModeGrey,
            backgroundContainerAlternative: palette.darkModeGrey,
            backgroundOverlay: applyAlpha(palette.darkModeGrey, 0.8),
            backgroundSkeleton: palette.darkModeGrey6,
            backgroundSkeletonInverse: palette.darkModeGrey6,
            backgroundFeedbackBottom: palette.darkModeBlack,
            appBarBackground: palette.darkModeGrey,
            navigationBarBackground: palette.darkModeBlack,
            skeletonWave: palette.grey5,
            borderLow: palette.darkModeBlack,
            border: palette.darkModeGrey,
            borderHigh: palette.grey5,
            borderSelected: palette.secondary30,
            coverBackgroundHover: applyAlpha(palette.darkModeBlack, 0.25),
            coverBackgroundPressed: applyAlpha(palette.darkModeBlack, 0.35),
            buttonDangerBackground: palette.red,
            buttonDangerBackgroundSelected: palette.red80,
            buttonDangerBackgroundHover: palette.red80,
            buttonLinkBackgroundSelected: applyAlpha(palette.white, 0.08),
            buttonLinkBackgroundInverseSelected: applyAlpha(palette.white, 0.08),
            buttonPrimaryBackground: palette.secondary30,
            buttonPrimaryBackgroundInverse: palette.secondary30,
            buttonPrimaryBackgroundSelected: palette.secondary70,
            buttonPrimaryBackgroundHover: palette.secondary70,
            buttonPrimaryBackgroundInverseSelected: palette.secondary70,
            buttonSecondaryBackgroundSelected: applyAlpha(palette.white, 0.15),
            buttonSecondaryBorder: palette.white,
            buttonSecondaryBackgroundHover: applyAlpha(palette.white, 0.15),
            buttonSecondaryBorderSelected: palette.white,
            buttonSecondaryBorderInverse: palette.white,
            buttonSecondaryBorderInverseSelected: palette.white,
            buttonSecondaryBackgroundInverseHover: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundInverseSelected: applyAlpha(palette.white, 0.15),
            textButtonPrimary: palette.grey6,
            textButtonPrimaryInverse: palette.grey6,
            textButtonPrimaryInverseSelected: palette.grey2,
            textButtonSecondary: palette.grey2,
            textButtonSecondarySelected: palette.grey2,
            textButtonSecondaryInverse: palette.grey2,
            textButtonSecondaryInverseSelected: palette.grey2,
            textLink: palette.secondary30,
            textLinkInverse: palette.secondary30,
            textLinkDanger: palette.red,
            textLinkSnackbar: palette.secondary30,
            control: palette.darkModeGrey6,
            controlActivated: palette.secondary30,
            controlInverse: palette.darkModeGrey6,
            controlActivatedInverse: palette.secondary30,
            controlError: palette.red,
            loadingBar: palette.secondary,
            loadingBarBackground: palette.secondary20,
            toggleAndroidInactive: palette.grey4,
            toggleAndroidBackgroundActive: palette.secondary20,
            iosControlKnob: palette.grey2,
            divider: applyAlpha(palette.white, 0.05),
            dividerInverse: applyAlpha(palette.white, 0.05),
            navigationBarDivider: palette.darkModeBlack,
            badge: palette.red70,
            feedbackErrorBackground: palette.red,
            feedbackInfoBackground: palette.darkModeGrey,
            brand: palette.secondary30,
            brandHigh: applyAlpha(palette.white, 0.05),
            inverse: palette.grey2,
            neutralHigh: palette.grey2,
            neutralMedium: palette.grey5,
            neutralMediumInverse: palette.grey5,
            neutralLow: palette.darkModeGrey6,
            neutralLowAlternative: palette.darkModeGrey6,
            textPrimary: palette.grey2,
            textPrimaryInverse: palette.grey2,
            textSecondary: palette.grey4,
            textSecondaryInverse: palette.grey4,
            error: palette.red,
            success: palette.green,
            warning: palette.orange,
            promo: palette.secondary,
            highlight: palette.red40,
            successLow: palette.darkModeGrey6,
            warningLow: palette.darkModeGrey6,
            errorLow: palette.darkModeGrey6,
            promoLow: palette.darkModeGrey6,
            brandLow: palette.darkModeGrey6,
            successHigh: palette.green40,
            warningHigh: palette.orange55,
            errorHigh: palette.red40,
            promoHigh: palette.secondary30,
            successHighInverse: palette.green70,
            warningHighInverse: palette.orange70,
            errorHighInverse: palette.red70,
            promoHighInverse: palette.secondary70,
            textNavigationBarPrimary: palette.grey2,
            textNavigationBarSecondary: palette.grey4,
            textNavigationSearchBarHint: palette.grey4,
            textNavigationSearchBarText: palette.grey2,
            textAppBar: palette.grey5,
            textAppBarSelected: palette.grey2,
            customTabsBackground: palette.darkModeBlack,
        },
        borderRadii: {
            avatar: '50%',
            bar: '999px',
            button: '999px',
            checkbox: '2px',
            container: '16px',
            indicator: '999px',
            input: '999px',
            legacyDisplay: '16px',
            popup: '8px',
            sheet: '16px',
            mediaSmall: '8px',
        },
        textPresets: {
            cardTitle: {weight: 'medium'},
            button: {weight: 'medium'},
            tabsLabel: {
                weight: 'medium',
                size: {mobile: 16, desktop: 18},
                lineHeight: {mobile: 24, desktop: 24},
            },
            link: {weight: 'medium'},
            title1: {weight: 'medium'},
            title2: {
                weight: 'medium',
                size: {mobile: 20, desktop: 28},
                lineHeight: {mobile: 24, desktop: 32},
            },
            indicator: {weight: 'medium'},
            navigationBar: {weight: 'medium'},
            text5: {weight: 'medium'},
            text6: {weight: 'medium'},
            text7: {weight: 'medium'},
            text8: {weight: 'medium'},
            text9: {weight: 'medium'},
            text10: {weight: 'medium'},
        },
    };
    return skin;
};
