import {UNBRANDED_SKIN} from './constants';
import {applyAlpha} from '../utils/color';

import type {GetKnownSkin, KnownSkin} from './types';

export const palette = {
    // Primitivos puros
    black: '#000000',
    white: '#FFFFFF',
    // Escala neutral (50 = casi blanco, 900 = casi negro)
    neutral50: '#F6F6F6',
    neutral100: '#EEEEEE',
    neutral200: '#DDDDDD',
    neutral500: '#8A8C90',
    neutral700: '#666666',
    neutral800: '#313235',
    neutral850: '#242424',
    neutral900: '#191919',
    // Azul-gris (input borders en dark mode)
    slate500: '#6D7D88',
    // Success
    green100: '#E8F5E9',
    green300: '#A5D6A7',
    green600: '#2E7D32',
    green800: '#1B5E20',
    // Warning
    orange100: '#FFF4E5',
    orange400: '#FFB74D',
    orange600: '#ED6C02',
    orange800: '#9A4A00',
    // Error
    red100: '#FDECEC',
    red400: '#E57373',
    red600: '#D32F2F',
    red800: '#9A1B1B',
};

export const getUnbrandedSkin: GetKnownSkin = () => {
    const skin: KnownSkin = {
        name: UNBRANDED_SKIN,
        colors: {
            background: palette.white,
            backgroundAlternative: palette.neutral50,
            backgroundBrand: palette.black,
            backgroundNegative: palette.black,
            backgroundBrandSecondary: palette.neutral900,
            backgroundContainer: palette.white,
            backgroundContainerError: palette.red100,
            backgroundContainerHover: applyAlpha(palette.black, 0.05),
            backgroundContainerPressed: applyAlpha(palette.black, 0.08),
            backgroundContainerBrand: palette.black,
            backgroundContainerBrandHover: applyAlpha(palette.white, 0.1),
            backgroundContainerBrandPressed: applyAlpha(palette.white, 0.2),
            backgroundContainerBrandOverInverse: palette.neutral900,
            backgroundContainerNegative: applyAlpha(palette.black, 0.4),
            backgroundContainerBrandOverBrand: palette.neutral900,
            backgroundContainerAlternative: palette.neutral50,
            backgroundOverlay: applyAlpha(palette.black, 0.6),
            backgroundSkeleton: palette.neutral200,
            backgroundSkeletonInverse: palette.neutral700,
            backgroundSkeletonNegative: applyAlpha(palette.black, 0.2),
            backgroundSkeletonBrand: palette.neutral700,
            backgroundBrandTop: palette.black,
            backgroundBrandBottom: palette.black,
            appBarBackground: palette.white,
            navigationBarBackground: palette.black,
            backgroundDropZoneHover: applyAlpha(palette.black, 0.04),
            backgroundDropZoneDragover: applyAlpha(palette.black, 0.08),
            backgroundDropZoneBrandHover: applyAlpha(palette.white, 0.1),
            backgroundDropZoneBrandDragover: applyAlpha(palette.white, 0.2),
            backgroundDropZoneNegativeHover: applyAlpha(palette.white, 0.1),
            backgroundDropZoneNegativeDragover: applyAlpha(palette.white, 0.17),
            backgroundDropZoneMediaHover: applyAlpha(palette.black, 0.3),
            backgroundDropZoneMediaDragover: applyAlpha(palette.black, 0.5),
            skeletonWave: palette.neutral100,
            borderLow: palette.neutral50,
            border: palette.neutral200,
            borderHigh: palette.neutral700,
            borderSelected: palette.black,
            coverBackgroundHover: applyAlpha(palette.black, 0.25),
            coverBackgroundPressed: applyAlpha(palette.black, 0.35),
            buttonDangerBackground: palette.red600,
            buttonDangerBackgroundPressed: palette.red800,
            buttonDangerBackgroundHover: palette.red800,
            buttonLinkDangerBackgroundInverse: palette.white,
            buttonLinkDangerBackgroundNegative: palette.white,
            buttonLinkDangerBackgroundBrand: palette.white,
            buttonLinkDangerBackgroundMedia: palette.white,
            buttonLinkDangerBackgroundPressed: palette.red100,
            buttonLinkDangerBackgroundInversePressed: palette.red100,
            buttonLinkDangerBackgroundNegativePressed: palette.red100,
            buttonLinkDangerBackgroundBrandPressed: palette.red100,
            buttonLinkDangerBackgroundMediaPressed: palette.red100,
            buttonLinkBackgroundPressed: applyAlpha(palette.black, 0.05),
            buttonLinkBackgroundInversePressed: applyAlpha(palette.white, 0.1),
            buttonLinkBackgroundNegativePressed: applyAlpha(palette.white, 0.1),
            buttonLinkBackgroundBrandPressed: applyAlpha(palette.white, 0.1),
            buttonLinkBackgroundMediaPressed: applyAlpha(palette.white, 0.1),
            buttonPrimaryBackground: palette.black,
            buttonPrimaryBackgroundInverse: palette.white,
            buttonPrimaryBackgroundNegative: palette.white,
            buttonPrimaryBackgroundBrand: palette.white,
            buttonPrimaryBackgroundMedia: palette.white,
            buttonPrimaryBackgroundHover: palette.neutral800,
            buttonPrimaryBackgroundInverseHover: palette.neutral100,
            buttonPrimaryBackgroundNegativeHover: palette.neutral100,
            buttonPrimaryBackgroundBrandHover: palette.neutral100,
            buttonPrimaryBackgroundMediaHover: palette.neutral100,
            buttonPrimaryBackgroundPressed: palette.neutral850,
            buttonPrimaryBackgroundInversePressed: palette.neutral200,
            buttonPrimaryBackgroundNegativePressed: palette.neutral200,
            buttonPrimaryBackgroundBrandPressed: palette.neutral200,
            buttonPrimaryBackgroundMediaPressed: palette.neutral200,
            buttonSecondaryBackgroundBrand: applyAlpha(palette.white, 0),
            buttonSecondaryBorder: palette.black,
            buttonSecondaryBorderInverse: palette.white,
            buttonSecondaryBorderNegative: palette.white,
            buttonSecondaryBorderBrand: palette.white,
            buttonSecondaryBorderMedia: palette.white,
            buttonSecondaryBorderPressed: palette.neutral850,
            buttonSecondaryBorderInversePressed: palette.white,
            buttonSecondaryBorderNegativePressed: palette.white,
            buttonSecondaryBorderBrandPressed: palette.white,
            buttonSecondaryBorderMediaPressed: palette.white,
            buttonSecondaryBackgroundHover: applyAlpha(palette.black, 0.05),
            buttonSecondaryBackgroundInverseHover: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundNegativeHover: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundBrandHover: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundMediaHover: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundPressed: applyAlpha(palette.black, 0.08),
            buttonSecondaryBackgroundInversePressed: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundNegativePressed: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundBrandPressed: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundMediaPressed: applyAlpha(palette.white, 0.15),
            textButtonPrimary: palette.white,
            textButtonPrimaryInverse: palette.black,
            textButtonPrimaryNegative: palette.black,
            textButtonPrimaryBrand: palette.black,
            textButtonPrimaryMedia: palette.black,
            textButtonPrimaryInversePressed: palette.black,
            textButtonPrimaryNegativePressed: palette.black,
            textButtonPrimaryBrandPressed: palette.black,
            textButtonPrimaryMediaPressed: palette.black,
            textButtonSecondary: palette.black,
            textButtonSecondaryInverse: palette.white,
            textButtonSecondaryNegative: palette.white,
            textButtonSecondaryBrand: palette.white,
            textButtonSecondaryMedia: palette.white,
            textButtonSecondaryPressed: palette.neutral850,
            textButtonSecondaryInversePressed: palette.white,
            textButtonSecondaryNegativePressed: palette.white,
            textButtonSecondaryBrandPressed: palette.white,
            textButtonSecondaryMediaPressed: palette.white,
            textLink: palette.black,
            textLinkInverse: palette.white,
            textLinkNegative: palette.white,
            textLinkBrand: palette.white,
            textLinkMedia: palette.white,
            textLinkDanger: palette.red600,
            textLinkDangerMedia: palette.red600,
            textLinkSnackbar: palette.neutral200,
            textActivated: palette.black,
            textBrand: palette.black,
            inputBorder: palette.neutral500,
            inputBorderInverse: palette.white,
            inputBorderNegative: palette.white,
            inputBorderBrand: palette.white,
            completedStep: palette.black,
            completedStepInverse: palette.neutral900,
            completedStepNegative: palette.neutral900,
            completedStepBrand: palette.neutral900,
            control: palette.neutral500,
            controlActivated: palette.black,
            controlInverse: palette.neutral200,
            controlNegative: palette.neutral200,
            controlBrand: palette.neutral200,
            controlActivatedInverse: palette.white,
            controlActivatedNegative: palette.white,
            controlActivatedBrand: palette.white,
            controlError: palette.red600,
            chevronIndicator: palette.neutral700,
            barTrack: palette.neutral200,
            barTrackInverse: applyAlpha(palette.white, 0.5),
            barTrackNegative: applyAlpha(palette.white, 0.5),
            barTrackBrand: applyAlpha(palette.white, 0.5),
            loadingBar: palette.black,
            loadingBarBackground: palette.neutral100,
            toggleAndroidInactive: palette.neutral100,
            toggleAndroidBackgroundActive: palette.neutral500,
            toggleAndroidActiveBrand: palette.white,
            toggleAndroidInactiveBrand: palette.neutral100,
            toggleAndroidBackgroundActiveBrand: palette.neutral500,
            toggleAndroidBackgroundInactiveBrand: palette.neutral700,
            iosControlKnob: palette.white,
            controlKnobInverse: palette.black,
            controlKnobNegative: palette.black,
            controlKnobBrand: palette.black,
            divider: palette.neutral200,
            dividerInverse: applyAlpha(palette.white, 0.2),
            dividerNegative: applyAlpha(palette.white, 0.2),
            dividerBrand: applyAlpha(palette.white, 0.2),
            navigationBarDivider: palette.black,
            badge: palette.red600,
            feedbackErrorBackground: palette.red600,
            feedbackInfoBackground: palette.neutral900,
            brand: palette.black,
            brandHigh: palette.neutral900,
            inverse: palette.white,
            negative: palette.white,
            neutralHigh: palette.black,
            neutralHighNegative: palette.white,
            neutralHighBrand: palette.white,
            neutralMedium: palette.neutral700,
            neutralMediumInverse: palette.neutral700,
            neutralMediumNegative: palette.neutral700,
            neutralMediumBrand: palette.neutral700,
            neutralLow: palette.neutral50,
            neutralLowAlternative: palette.neutral100,
            textPrimary: palette.black,
            textPrimaryInverse: palette.white,
            textPrimaryNegative: palette.white,
            textPrimaryBrand: palette.white,
            textPrimaryMedia: palette.white,
            textSecondary: palette.neutral700,
            textSecondaryInverse: palette.neutral200,
            textSecondaryNegative: palette.neutral200,
            textSecondaryBrand: palette.neutral200,
            textSecondaryMedia: palette.white,
            success: palette.green600,
            warning: palette.orange600,
            error: palette.red600,
            textError: palette.red600,
            textErrorInverse: palette.white,
            textErrorNegative: palette.white,
            textErrorBrand: palette.white,
            promo: palette.black,
            highlight: palette.black,
            successLow: palette.green100,
            warningLow: palette.orange100,
            errorLow: palette.red100,
            promoLow: palette.neutral50,
            brandLow: palette.neutral50,
            successHigh: palette.green800,
            warningHigh: palette.orange800,
            errorHigh: palette.red800,
            promoHigh: palette.black,
            successHighInverse: palette.green800,
            successHighNegative: palette.green800,
            successHighBrand: palette.green800,
            warningHighInverse: palette.orange800,
            warningHighNegative: palette.orange800,
            warningHighBrand: palette.orange800,
            errorHighInverse: palette.red800,
            errorHighNegative: palette.red800,
            errorHighBrand: palette.red800,
            promoHighInverse: palette.black,
            promoHighNegative: palette.black,
            promoHighBrand: palette.black,
            textNavigationBarPrimary: palette.white,
            textNavigationBarSecondary: palette.neutral200,
            textNavigationSearchBarHint: palette.neutral200,
            textNavigationSearchBarText: palette.white,
            textAppBar: palette.neutral700,
            textAppBarSelected: palette.black,
            iosGlassAppBar: palette.black,
            iosGlassAppBarSelected: palette.black,
            customTabsBackground: palette.white,
            tagTextPromo: palette.black,
            tagTextActive: palette.black,
            tagTextInactive: palette.neutral700,
            tagTextInfo: palette.black,
            tagTextSuccess: palette.green800,
            tagTextWarning: palette.orange800,
            tagTextError: palette.red800,
            tagBackgroundPromo: palette.neutral50,
            tagBackgroundActive: palette.neutral50,
            tagBackgroundInactive: palette.neutral50,
            tagBackgroundInfo: palette.neutral50,
            tagBackgroundSuccess: palette.green100,
            tagBackgroundWarning: palette.orange100,
            tagBackgroundError: palette.red100,
            tagTextPromoInverse: palette.black,
            tagTextPromoNegative: palette.black,
            tagTextPromoBrand: palette.black,
            tagTextActiveInverse: palette.black,
            tagTextActiveNegative: palette.black,
            tagTextActiveBrand: palette.black,
            tagTextInactiveInverse: palette.neutral700,
            tagTextInactiveNegative: palette.neutral700,
            tagTextInactiveBrand: palette.neutral700,
            tagTextInfoInverse: palette.black,
            tagTextInfoNegative: palette.black,
            tagTextInfoBrand: palette.black,
            tagTextSuccessInverse: palette.green800,
            tagTextSuccessNegative: palette.green800,
            tagTextSuccessBrand: palette.green800,
            tagTextWarningInverse: palette.orange800,
            tagTextWarningNegative: palette.orange800,
            tagTextWarningBrand: palette.orange800,
            tagTextErrorInverse: palette.red800,
            tagTextErrorNegative: palette.red800,
            tagTextErrorBrand: palette.red800,
            tagBackgroundPromoInverse: palette.neutral50,
            tagBackgroundPromoNegative: palette.neutral50,
            tagBackgroundPromoBrand: palette.neutral50,
            tagBackgroundActiveInverse: palette.neutral50,
            tagBackgroundActiveNegative: palette.neutral50,
            tagBackgroundActiveBrand: palette.neutral50,
            tagBackgroundInactiveInverse: palette.neutral50,
            tagBackgroundInactiveNegative: palette.neutral50,
            tagBackgroundInactiveBrand: palette.neutral50,
            tagBackgroundInfoInverse: palette.neutral50,
            tagBackgroundInfoNegative: palette.neutral50,
            tagBackgroundInfoBrand: palette.neutral50,
            tagBackgroundSuccessInverse: palette.green100,
            tagBackgroundSuccessNegative: palette.green100,
            tagBackgroundSuccessBrand: palette.green100,
            tagBackgroundWarningInverse: palette.orange100,
            tagBackgroundWarningNegative: palette.orange100,
            tagBackgroundWarningBrand: palette.orange100,
            tagBackgroundErrorInverse: palette.red100,
            tagBackgroundErrorNegative: palette.red100,
            tagBackgroundErrorBrand: palette.red100,
            cardContentOverlay: `linear-gradient(180deg, ${applyAlpha(palette.black, 0)} 0%, ${applyAlpha(palette.black, 0.4)} 30%, ${applyAlpha(palette.black, 0.7)} 100%)`,
            cardFooterOverlay: applyAlpha(palette.black, 0.7),
        },
        darkModeColors: {
            background: palette.black,
            backgroundAlternative: palette.black,
            backgroundBrand: palette.black,
            backgroundNegative: palette.black,
            backgroundBrandSecondary: palette.black,
            backgroundContainer: palette.neutral850,
            backgroundContainerError: palette.neutral850,
            backgroundContainerHover: applyAlpha(palette.white, 0.05),
            backgroundContainerPressed: applyAlpha(palette.white, 0.08),
            backgroundContainerBrand: palette.neutral850,
            backgroundContainerBrandHover: applyAlpha(palette.white, 0.03),
            backgroundContainerBrandPressed: applyAlpha(palette.white, 0.05),
            backgroundContainerBrandOverInverse: palette.neutral850,
            backgroundContainerNegative: palette.neutral850,
            backgroundContainerBrandOverBrand: palette.neutral850,
            backgroundContainerAlternative: palette.neutral850,
            backgroundOverlay: applyAlpha(palette.neutral850, 0.8),
            backgroundSkeleton: palette.neutral800,
            backgroundSkeletonInverse: palette.neutral800,
            backgroundSkeletonNegative: palette.neutral800,
            backgroundSkeletonBrand: palette.neutral800,
            backgroundBrandTop: palette.black,
            backgroundBrandBottom: palette.black,
            appBarBackground: palette.neutral850,
            navigationBarBackground: palette.black,
            backgroundDropZoneHover: applyAlpha(palette.white, 0.05),
            backgroundDropZoneDragover: applyAlpha(palette.white, 0.08),
            backgroundDropZoneBrandHover: applyAlpha(palette.white, 0.03),
            backgroundDropZoneBrandDragover: applyAlpha(palette.white, 0.05),
            backgroundDropZoneNegativeHover: applyAlpha(palette.white, 0.03),
            backgroundDropZoneNegativeDragover: applyAlpha(palette.white, 0.05),
            backgroundDropZoneMediaHover: applyAlpha(palette.white, 0.03),
            backgroundDropZoneMediaDragover: applyAlpha(palette.white, 0.05),
            skeletonWave: palette.neutral700,
            borderLow: palette.neutral900,
            border: palette.neutral850,
            borderHigh: palette.neutral700,
            borderSelected: palette.white,
            coverBackgroundHover: applyAlpha(palette.neutral900, 0.25),
            coverBackgroundPressed: applyAlpha(palette.neutral900, 0.35),
            buttonDangerBackground: palette.red600,
            buttonDangerBackgroundPressed: palette.red800,
            buttonDangerBackgroundHover: palette.red800,
            buttonLinkDangerBackgroundInverse: applyAlpha(palette.white, 0),
            buttonLinkDangerBackgroundNegative: applyAlpha(palette.white, 0),
            buttonLinkDangerBackgroundBrand: applyAlpha(palette.white, 0),
            buttonLinkDangerBackgroundMedia: palette.white,
            buttonLinkDangerBackgroundPressed: applyAlpha(palette.white, 0.08),
            buttonLinkDangerBackgroundInversePressed: applyAlpha(palette.white, 0.08),
            buttonLinkDangerBackgroundNegativePressed: applyAlpha(palette.white, 0.08),
            buttonLinkDangerBackgroundBrandPressed: applyAlpha(palette.white, 0.08),
            buttonLinkDangerBackgroundMediaPressed: palette.red100,
            buttonLinkBackgroundPressed: applyAlpha(palette.white, 0.08),
            buttonLinkBackgroundInversePressed: applyAlpha(palette.white, 0.08),
            buttonLinkBackgroundNegativePressed: applyAlpha(palette.white, 0.08),
            buttonLinkBackgroundBrandPressed: applyAlpha(palette.white, 0.08),
            buttonLinkBackgroundMediaPressed: applyAlpha(palette.white, 0.1),
            buttonPrimaryBackground: palette.white,
            buttonPrimaryBackgroundInverse: palette.white,
            buttonPrimaryBackgroundNegative: palette.white,
            buttonPrimaryBackgroundBrand: palette.white,
            buttonPrimaryBackgroundMedia: palette.white,
            buttonPrimaryBackgroundHover: palette.neutral100,
            buttonPrimaryBackgroundInverseHover: palette.neutral100,
            buttonPrimaryBackgroundNegativeHover: palette.neutral100,
            buttonPrimaryBackgroundBrandHover: palette.neutral100,
            buttonPrimaryBackgroundMediaHover: palette.neutral100,
            buttonPrimaryBackgroundPressed: palette.neutral200,
            buttonPrimaryBackgroundInversePressed: palette.neutral200,
            buttonPrimaryBackgroundNegativePressed: palette.neutral200,
            buttonPrimaryBackgroundBrandPressed: palette.neutral200,
            buttonPrimaryBackgroundMediaPressed: palette.neutral200,
            buttonSecondaryBackgroundBrand: applyAlpha(palette.white, 0),
            buttonSecondaryBorder: palette.white,
            buttonSecondaryBorderInverse: palette.white,
            buttonSecondaryBorderNegative: palette.white,
            buttonSecondaryBorderBrand: palette.white,
            buttonSecondaryBorderMedia: palette.white,
            buttonSecondaryBorderPressed: palette.white,
            buttonSecondaryBorderInversePressed: palette.white,
            buttonSecondaryBorderNegativePressed: palette.white,
            buttonSecondaryBorderBrandPressed: palette.white,
            buttonSecondaryBorderMediaPressed: palette.white,
            buttonSecondaryBackgroundHover: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundInverseHover: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundNegativeHover: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundBrandHover: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundMediaHover: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundPressed: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundInversePressed: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundNegativePressed: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundBrandPressed: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundMediaPressed: applyAlpha(palette.white, 0.15),
            textButtonPrimary: palette.neutral900,
            textButtonPrimaryInverse: palette.neutral900,
            textButtonPrimaryNegative: palette.neutral900,
            textButtonPrimaryBrand: palette.neutral900,
            textButtonPrimaryMedia: palette.black,
            textButtonPrimaryInversePressed: palette.neutral900,
            textButtonPrimaryNegativePressed: palette.neutral900,
            textButtonPrimaryBrandPressed: palette.neutral900,
            textButtonPrimaryMediaPressed: palette.black,
            textButtonSecondary: palette.neutral100,
            textButtonSecondaryInverse: palette.neutral100,
            textButtonSecondaryNegative: palette.neutral100,
            textButtonSecondaryBrand: palette.neutral100,
            textButtonSecondaryMedia: palette.white,
            textButtonSecondaryPressed: palette.neutral100,
            textButtonSecondaryInversePressed: palette.neutral100,
            textButtonSecondaryNegativePressed: palette.neutral100,
            textButtonSecondaryBrandPressed: palette.neutral100,
            textButtonSecondaryMediaPressed: palette.white,
            textLink: palette.white,
            textLinkInverse: palette.white,
            textLinkNegative: palette.white,
            textLinkBrand: palette.white,
            textLinkMedia: palette.white,
            textLinkDanger: palette.red400,
            textLinkDangerMedia: palette.red400,
            textLinkSnackbar: palette.neutral200,
            textActivated: palette.white,
            textBrand: palette.white,
            inputBorder: palette.slate500,
            inputBorderInverse: palette.slate500,
            inputBorderNegative: palette.slate500,
            inputBorderBrand: palette.slate500,
            completedStep: palette.white,
            completedStepInverse: palette.white,
            completedStepNegative: palette.white,
            completedStepBrand: palette.white,
            control: palette.neutral800,
            controlActivated: palette.white,
            controlInverse: palette.neutral800,
            controlNegative: palette.neutral800,
            controlBrand: palette.neutral800,
            controlActivatedInverse: palette.white,
            controlActivatedNegative: palette.white,
            controlActivatedBrand: palette.white,
            controlError: palette.red600,
            chevronIndicator: palette.neutral700,
            barTrack: palette.neutral800,
            barTrackInverse: palette.neutral800,
            barTrackNegative: palette.neutral800,
            barTrackBrand: palette.neutral800,
            loadingBar: palette.white,
            loadingBarBackground: palette.neutral800,
            toggleAndroidInactive: palette.neutral500,
            toggleAndroidBackgroundActive: palette.neutral200,
            toggleAndroidActiveBrand: palette.white,
            toggleAndroidInactiveBrand: palette.neutral500,
            toggleAndroidBackgroundActiveBrand: palette.neutral200,
            toggleAndroidBackgroundInactiveBrand: palette.neutral800,
            iosControlKnob: palette.neutral100,
            controlKnobInverse: palette.neutral100,
            controlKnobNegative: palette.neutral100,
            controlKnobBrand: palette.neutral100,
            divider: applyAlpha(palette.white, 0.05),
            dividerInverse: applyAlpha(palette.white, 0.05),
            dividerNegative: applyAlpha(palette.white, 0.05),
            dividerBrand: applyAlpha(palette.white, 0.05),
            navigationBarDivider: palette.neutral900,
            badge: palette.red600,
            feedbackErrorBackground: palette.red600,
            feedbackInfoBackground: palette.black,
            brand: palette.white,
            brandHigh: applyAlpha(palette.white, 0.05),
            inverse: palette.neutral100,
            negative: palette.neutral100,
            neutralHigh: palette.neutral100,
            neutralHighBrand: palette.neutral100,
            neutralHighNegative: palette.neutral100,
            neutralMedium: palette.neutral700,
            neutralMediumInverse: palette.neutral700,
            neutralMediumNegative: palette.neutral700,
            neutralMediumBrand: palette.neutral700,
            neutralLow: palette.neutral800,
            neutralLowAlternative: palette.neutral800,
            textPrimary: palette.neutral100,
            textPrimaryInverse: palette.neutral100,
            textPrimaryNegative: palette.neutral100,
            textPrimaryBrand: palette.neutral100,
            textPrimaryMedia: palette.white,
            textSecondary: palette.neutral200,
            textSecondaryInverse: palette.neutral200,
            textSecondaryNegative: palette.neutral200,
            textSecondaryBrand: palette.neutral200,
            textSecondaryMedia: palette.white,
            success: palette.green600,
            warning: palette.orange600,
            error: palette.red600,
            textError: palette.red400,
            textErrorInverse: palette.red400,
            textErrorNegative: palette.red400,
            textErrorBrand: palette.red400,
            promo: palette.white,
            highlight: palette.white,
            successLow: palette.neutral800,
            warningLow: palette.neutral800,
            errorLow: palette.neutral800,
            promoLow: palette.neutral800,
            brandLow: palette.neutral800,
            successHigh: palette.green300,
            warningHigh: palette.orange400,
            errorHigh: palette.red400,
            promoHigh: palette.neutral200,
            successHighInverse: palette.green800,
            successHighNegative: palette.green800,
            successHighBrand: palette.green800,
            warningHighInverse: palette.orange800,
            warningHighNegative: palette.orange800,
            warningHighBrand: palette.orange800,
            errorHighInverse: palette.red800,
            errorHighNegative: palette.red800,
            errorHighBrand: palette.red800,
            promoHighInverse: palette.black,
            promoHighNegative: palette.black,
            promoHighBrand: palette.black,
            textNavigationBarPrimary: palette.neutral100,
            textNavigationBarSecondary: palette.neutral500,
            textNavigationSearchBarHint: palette.neutral500,
            textNavigationSearchBarText: palette.neutral100,
            textAppBar: palette.neutral700,
            textAppBarSelected: palette.neutral100,
            iosGlassAppBar: palette.white,
            iosGlassAppBarSelected: palette.neutral200,
            customTabsBackground: palette.neutral900,
            tagTextPromo: palette.neutral200,
            tagTextActive: palette.white,
            tagTextInactive: palette.neutral700,
            tagTextInfo: palette.white,
            tagTextSuccess: palette.green300,
            tagTextWarning: palette.orange400,
            tagTextError: palette.red400,
            tagBackgroundPromo: palette.neutral800,
            tagBackgroundActive: palette.neutral800,
            tagBackgroundInactive: palette.neutral800,
            tagBackgroundInfo: palette.neutral800,
            tagBackgroundSuccess: palette.neutral800,
            tagBackgroundWarning: palette.neutral800,
            tagBackgroundError: palette.neutral800,
            tagTextPromoInverse: palette.neutral200,
            tagTextPromoNegative: palette.neutral200,
            tagTextPromoBrand: palette.neutral200,
            tagTextActiveInverse: palette.white,
            tagTextActiveNegative: palette.white,
            tagTextActiveBrand: palette.white,
            tagTextInactiveInverse: palette.neutral700,
            tagTextInactiveNegative: palette.neutral700,
            tagTextInactiveBrand: palette.neutral700,
            tagTextInfoInverse: palette.white,
            tagTextInfoNegative: palette.white,
            tagTextInfoBrand: palette.white,
            tagTextSuccessInverse: palette.green300,
            tagTextSuccessNegative: palette.green300,
            tagTextSuccessBrand: palette.green300,
            tagTextWarningInverse: palette.orange400,
            tagTextWarningNegative: palette.orange400,
            tagTextWarningBrand: palette.orange400,
            tagTextErrorInverse: palette.red400,
            tagTextErrorNegative: palette.red400,
            tagTextErrorBrand: palette.red400,
            tagBackgroundPromoInverse: palette.neutral800,
            tagBackgroundPromoNegative: palette.neutral800,
            tagBackgroundPromoBrand: palette.neutral800,
            tagBackgroundActiveInverse: palette.neutral800,
            tagBackgroundActiveNegative: palette.neutral800,
            tagBackgroundActiveBrand: palette.neutral800,
            tagBackgroundInactiveInverse: palette.neutral800,
            tagBackgroundInactiveNegative: palette.neutral800,
            tagBackgroundInactiveBrand: palette.neutral800,
            tagBackgroundInfoInverse: palette.neutral800,
            tagBackgroundInfoNegative: palette.neutral800,
            tagBackgroundInfoBrand: palette.neutral800,
            tagBackgroundSuccessInverse: palette.neutral800,
            tagBackgroundSuccessNegative: palette.neutral800,
            tagBackgroundSuccessBrand: palette.neutral800,
            tagBackgroundWarningInverse: palette.neutral800,
            tagBackgroundWarningNegative: palette.neutral800,
            tagBackgroundWarningBrand: palette.neutral800,
            tagBackgroundErrorInverse: palette.neutral800,
            tagBackgroundErrorNegative: palette.neutral800,
            tagBackgroundErrorBrand: palette.neutral800,
            cardContentOverlay: `linear-gradient(180deg, ${applyAlpha(palette.black, 0)} 0%, ${applyAlpha(palette.black, 0.4)} 30%, ${applyAlpha(palette.black, 0.7)} 100%)`,
            cardFooterOverlay: applyAlpha(palette.black, 0.7),
        },
        borderRadii: {
            avatar: '50%',
            bar: '999px',
            button: '32px',
            checkbox: '2px',
            container: '16px',
            indicator: '24px',
            chip: '24px',
            tag: '24px',
            input: '12px',
            legacyDisplay: '16px',
            popup: '8px',
            sheet: '16px',
            mediaSmall: '8px',
        },
        textPresets: {
            button: {weight: 'medium'},
            cardDescriptionDefault: {lineHeight: {desktop: 24, mobile: 20}, size: {desktop: 16, mobile: 14}},
            cardDescriptionSnap: {lineHeight: {desktop: 24, mobile: 20}, size: {desktop: 16, mobile: 14}},
            cardPretitleDefault: {lineHeight: {desktop: 24, mobile: 20}, size: {desktop: 16, mobile: 14}},
            cardPretitleSnap: {lineHeight: {desktop: 24, mobile: 20}, size: {desktop: 16, mobile: 14}},
            cardSubtitleDefault: {lineHeight: {desktop: 24, mobile: 20}, size: {desktop: 16, mobile: 14}},
            cardSubtitleSnap: {lineHeight: {desktop: 24, mobile: 20}, size: {desktop: 16, mobile: 14}},
            cardTitle: {weight: 'medium'},
            cardTitleDefault: {lineHeight: {desktop: 28, mobile: 24}, size: {desktop: 24, mobile: 18}},
            cardTitleSnap: {lineHeight: {desktop: 24, mobile: 20}, size: {desktop: 16, mobile: 14}},
            chipLabel: {
                lineHeight: {desktop: 24, mobile: 20},
                size: {desktop: 16, mobile: 14},
                weight: 'medium',
            },
            drawerTitle: {
                lineHeight: {desktop: 32, mobile: 24},
                size: {desktop: 28, mobile: 20},
                weight: 'medium',
            },
            indicator: {weight: 'medium'},
            inputHelperText: {lineHeight: {desktop: 20, mobile: 16}, size: {desktop: 14, mobile: 12}},
            inputLabel: {lineHeight: {desktop: 20, mobile: 16}, size: {desktop: 14, mobile: 12}},
            inputValue: {lineHeight: {desktop: 24, mobile: 24}, size: {desktop: 18, mobile: 16}},
            link: {weight: 'medium'},
            loadingScreenTitle: {lineHeight: {desktop: 28, mobile: 24}, size: {desktop: 24, mobile: 18}},
            navigationBar: {weight: 'regular'},
            rowTitle: {weight: 'regular'},
            stepperStepLabel: {lineHeight: {desktop: 24, mobile: 20}, size: {desktop: 16, mobile: 14}},
            tabsLabel: {
                lineHeight: {desktop: 24, mobile: 24},
                size: {desktop: 18, mobile: 18},
                weight: 'medium',
            },
            text1: {lineHeight: {desktop: 20, mobile: 16}, size: {desktop: 14, mobile: 12}},
            text2: {lineHeight: {desktop: 24, mobile: 20}, size: {desktop: 16, mobile: 14}},
            text3: {lineHeight: {desktop: 24, mobile: 24}, size: {desktop: 18, mobile: 16}},
            text4: {lineHeight: {desktop: 28, mobile: 24}, size: {desktop: 24, mobile: 18}},
            text5: {lineHeight: {desktop: 32, mobile: 24}, size: {desktop: 28, mobile: 20}, weight: 'medium'},
            text6: {lineHeight: {desktop: 40, mobile: 32}, size: {desktop: 32, mobile: 24}, weight: 'medium'},
            text7: {lineHeight: {desktop: 48, mobile: 32}, size: {desktop: 40, mobile: 28}, weight: 'medium'},
            text8: {
                lineHeight: {desktop: 56, mobile: 40},
                size: {desktop: 48, mobile: 32},
                weight: 'regular',
            },
            text9: {
                lineHeight: {desktop: 64, mobile: 48},
                size: {desktop: 56, mobile: 40},
                weight: 'regular',
            },
            text10: {
                lineHeight: {desktop: 72, mobile: 56},
                size: {desktop: 64, mobile: 48},
                weight: 'regular',
            },
            title1: {
                lineHeight: {desktop: 20, mobile: 16},
                size: {desktop: 14, mobile: 12},
                weight: 'medium',
            },
            title2: {
                lineHeight: {desktop: 24, mobile: 24},
                size: {desktop: 18, mobile: 16},
                weight: 'medium',
            },
            title3: {
                lineHeight: {desktop: 28, mobile: 24},
                size: {desktop: 24, mobile: 18},
                weight: 'medium',
            },
            title4: {
                lineHeight: {desktop: 40, mobile: 32},
                size: {desktop: 32, mobile: 24},
                weight: 'medium',
            },
        },
        themeVariants: {
            successFeedback: 'inverse',
            brandLoadingScreen: 'inverse',
        },
        spacing: {
            buttonDefaultPadding: {left: {mobile: 16, desktop: 16}, right: {mobile: 16, desktop: 16}},
            buttonSmallPadding: {left: {mobile: 12, desktop: 12}, right: {mobile: 12, desktop: 12}},
            cardDefaultPadding: {
                top: {mobile: 16, desktop: 24},
                bottom: {mobile: 16, desktop: 24},
                left: {mobile: 16, desktop: 24},
                right: {mobile: 16, desktop: 24},
            },
            inputPadding: {top: {mobile: 8, desktop: 8}, bottom: {mobile: 8, desktop: 8}},
            tagPadding: {top: {mobile: 4, desktop: 4}, bottom: {mobile: 4, desktop: 4}},
            feedbackScreenPadding: {
                top: {mobile: 64, desktop: 64},
                bottom: {mobile: 16, desktop: 64},
                left: {mobile: 16, desktop: 64},
                right: {mobile: 16, desktop: 64},
            },
            heroPadding: {top: {mobile: 24, desktop: 56}, bottom: {mobile: 24, desktop: 56}},
            headerPadding: {top: {mobile: 24, desktop: 48}, bottom: {mobile: 24, desktop: 48}},
            drawerPadding: {
                top: {mobile: 32, desktop: 40},
                bottom: {mobile: 16, desktop: 24},
                left: {mobile: 16, desktop: 40},
                right: {mobile: 16, desktop: 40},
            },
        },
    };
    return skin;
};
