import {VIVO_SKIN} from './constants';
import {applyAlpha} from '../utils/color';

import type {GetKnownSkin, KnownSkin} from './types';

export const palette = {
    vivoPurple: '#660099',
    vivoPurpleDark: '#461E5F',
    vivoPurpleLight10: '#EFE5F4',
    vivoPurpleLight20: '#E0CCEB',
    vivoPurpleLight50: '#B280CC',
    vivoPurpleLight80: '#8433AD',
    vivoPurpleLight90: '#751AA3',
    vivoGreen: '#99CC33',
    vivoGreenDark: '#225C3D',
    vivoGreenLight10: '#EDF8E8',
    vivoGreen25: '#D6EBAD',
    vivoGreenLight30: '#91AE9E',
    vivoBlue: '#00ABDB',
    orange: '#FF9900',
    orange25: '#FFD699',
    orangeDark: '#972A1D',
    orangeLight10: '#FFEFE1',
    orangeLight40: '#FFB84C',
    pink: '#EB3D7D',
    pepper: '#CC1F59',
    pepperDark: '#B71D63',
    pepperDark80: '#8F2052',
    pepperLight10: '#FCE4EF',
    pepperLight30: '#F7B1CB',
    pepperLight40: '#DB628B',
    grey1: '#F6F6F6',
    grey2: '#EEEEEE',
    grey3: '#DDDDDD',
    grey4: '#999999',
    grey5: '#666666',
    grey6: '#000000',
    white: '#FFFFFF',
    darkModeBlack: '#191919',
    darkModeGrey: '#242424',
    darkModeGrey6: '#313235',
};

export const getVivoSkin: GetKnownSkin = () => {
    const skin: KnownSkin = {
        name: VIVO_SKIN,
        colors: {
            background: palette.white,
            backgroundAlternative: palette.grey1,
            backgroundBrand: palette.vivoPurple,
            backgroundBrandSecondary: palette.vivoPurple,
            backgroundContainer: palette.white,
            backgroundContainerError: palette.pepperLight10,
            backgroundContainerHover: applyAlpha(palette.darkModeBlack, 0.05),
            backgroundContainerPressed: applyAlpha(palette.darkModeBlack, 0.08),
            backgroundContainerBrand: palette.vivoPurple,
            backgroundContainerBrandHover: applyAlpha(palette.darkModeBlack, 0.2),
            backgroundContainerBrandPressed: applyAlpha(palette.darkModeBlack, 0.4),
            backgroundContainerBrandOverInverse: palette.vivoPurpleDark,
            backgroundContainerAlternative: palette.grey1,
            backgroundOverlay: applyAlpha(palette.grey6, 0.6),
            backgroundSkeleton: palette.grey2,
            backgroundSkeletonInverse: palette.vivoPurpleDark,
            backgroundBrandTop: palette.vivoPurple,
            backgroundBrandBottom: palette.vivoPurple,
            appBarBackground: palette.white,
            navigationBarBackground: palette.vivoPurple,
            skeletonWave: palette.grey2,
            borderLow: palette.grey1,
            border: palette.grey3,
            borderHigh: palette.grey5,
            borderSelected: palette.vivoPurple,
            coverBackgroundHover: applyAlpha(palette.darkModeBlack, 0.25),
            coverBackgroundPressed: applyAlpha(palette.darkModeBlack, 0.35),
            buttonDangerBackground: palette.pepper,
            buttonDangerBackgroundPressed: palette.pepperDark,
            buttonDangerBackgroundHover: palette.pepperDark,
            buttonLinkDangerBackgroundInverse: palette.white,
            buttonLinkDangerBackgroundMedia: palette.white,
            buttonLinkDangerBackgroundPressed: palette.pepperLight10,
            buttonLinkDangerBackgroundInversePressed: palette.pepperLight10,
            buttonLinkDangerBackgroundMediaPressed: palette.pepperLight10,
            buttonLinkBackgroundPressed: palette.vivoPurpleLight10,
            buttonLinkBackgroundInversePressed: applyAlpha(palette.white, 0.1),
            buttonLinkBackgroundMediaPressed: applyAlpha(palette.white, 0.1),
            buttonPrimaryBackground: palette.vivoPurple,
            buttonPrimaryBackgroundInverse: palette.white,
            buttonPrimaryBackgroundMedia: palette.white,
            buttonPrimaryBackgroundHover: palette.vivoPurpleDark,
            buttonPrimaryBackgroundInverseHover: palette.vivoPurpleLight50,
            buttonPrimaryBackgroundMediaHover: palette.vivoPurpleLight50,
            buttonPrimaryBackgroundPressed: palette.vivoPurpleDark,
            buttonPrimaryBackgroundInversePressed: palette.vivoPurpleLight50,
            buttonPrimaryBackgroundMediaPressed: palette.vivoPurpleLight50,
            buttonSecondaryBorder: palette.vivoPurple,
            buttonSecondaryBorderInverse: palette.white,
            buttonSecondaryBorderMedia: palette.white,
            buttonSecondaryBorderPressed: palette.vivoPurpleDark,
            buttonSecondaryBorderInversePressed: palette.white,
            buttonSecondaryBorderMediaPressed: palette.white,
            buttonSecondaryBackgroundHover: palette.vivoPurpleLight10,
            buttonSecondaryBackgroundInverseHover: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundMediaHover: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundPressed: palette.vivoPurpleLight10,
            buttonSecondaryBackgroundInversePressed: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundMediaPressed: applyAlpha(palette.white, 0.15),
            textButtonPrimary: palette.white,
            textButtonPrimaryInverse: palette.vivoPurple,
            textButtonPrimaryMedia: palette.vivoPurple,
            textButtonPrimaryInversePressed: palette.vivoPurple,
            textButtonPrimaryMediaPressed: palette.vivoPurple,
            textButtonSecondary: palette.vivoPurple,
            textButtonSecondaryInverse: palette.white,
            textButtonSecondaryMedia: palette.white,
            textButtonSecondaryPressed: palette.vivoPurpleDark,
            textButtonSecondaryInversePressed: palette.white,
            textButtonSecondaryMediaPressed: palette.white,
            textLink: palette.vivoPurple,
            textLinkInverse: palette.white,
            textLinkMedia: palette.white,
            textLinkDanger: palette.pepper,
            textLinkDangerMedia: palette.pepper,
            textLinkSnackbar: palette.vivoPurpleLight50,
            textActivated: palette.vivoPurple,
            textBrand: palette.vivoPurple,
            inputBorder: palette.grey3,
            inputBorderInverse: palette.white,
            completedStep: palette.vivoPurple,
            completedStepInverse: palette.vivoPurpleDark,
            control: palette.grey3,
            controlActivated: palette.vivoPurple,
            controlInverse: palette.vivoPurpleLight50,
            controlActivatedInverse: palette.white,
            controlError: palette.pepper,
            barTrack: palette.grey3,
            barTrackInverse: applyAlpha(palette.white, 0.5),
            loadingBar: palette.pink,
            loadingBarBackground: palette.pepperLight30,
            toggleAndroidInactive: palette.grey2,
            toggleAndroidBackgroundActive: palette.vivoPurpleLight20,
            iosControlKnob: palette.white,
            controlKnobInverse: palette.vivoPurple,
            divider: palette.grey2,
            dividerInverse: applyAlpha(palette.white, 0.2),
            navigationBarDivider: palette.vivoPurple,
            badge: palette.pepperDark,
            feedbackErrorBackground: palette.pepper,
            feedbackInfoBackground: palette.grey6,
            brand: palette.vivoPurple,
            brandHigh: palette.vivoPurpleDark,
            inverse: palette.white,
            neutralHigh: palette.grey6,
            neutralMedium: palette.grey5,
            neutralMediumInverse: palette.grey5,
            neutralLow: palette.grey1,
            neutralLowAlternative: palette.grey2,
            textPrimary: palette.grey6,
            textPrimaryInverse: palette.white,
            textPrimaryMedia: palette.white,
            textSecondary: palette.grey5,
            textSecondaryInverse: palette.vivoPurpleLight20,
            textSecondaryMedia: palette.white,
            success: palette.vivoGreen,
            warning: palette.orange,
            error: palette.pepper,
            textError: palette.pepper,
            textErrorInverse: palette.white,
            promo: palette.vivoPurple,
            highlight: palette.pink,
            successLow: palette.vivoGreenLight10,
            warningLow: palette.orangeLight10,
            errorLow: palette.pepperLight10,
            promoLow: palette.vivoPurpleLight10,
            brandLow: palette.vivoPurpleLight10,
            successHigh: palette.vivoGreenDark,
            warningHigh: palette.orangeDark,
            errorHigh: palette.pepperDark80,
            promoHigh: palette.vivoPurple,
            successHighInverse: palette.vivoGreenDark,
            warningHighInverse: palette.orangeDark,
            errorHighInverse: palette.pepperDark80,
            promoHighInverse: palette.vivoPurple,
            textNavigationBarPrimary: palette.white,
            textNavigationBarSecondary: palette.vivoPurpleLight50,
            textNavigationSearchBarHint: palette.vivoPurpleLight50,
            textNavigationSearchBarText: palette.white,
            textAppBar: palette.grey4,
            textAppBarSelected: palette.vivoPurple,
            customTabsBackground: palette.vivoPurple,
            tagTextPromo: palette.vivoPurple,
            tagTextActive: palette.vivoPurple,
            tagTextInactive: palette.grey5,
            tagTextInfo: palette.vivoPurple,
            tagTextSuccess: palette.vivoGreenDark,
            tagTextWarning: palette.orangeDark,
            tagTextError: palette.pepperDark80,
            tagBackgroundPromo: palette.vivoPurpleLight10,
            tagBackgroundActive: palette.vivoPurpleLight10,
            tagBackgroundInactive: palette.grey1,
            tagBackgroundInfo: palette.vivoPurpleLight10,
            tagBackgroundSuccess: palette.vivoGreenLight10,
            tagBackgroundWarning: palette.orangeLight10,
            tagBackgroundError: palette.pepperLight10,
            tagTextPromoInverse: palette.vivoPurple,
            tagTextActiveInverse: palette.vivoPurple,
            tagTextInactiveInverse: palette.grey5,
            tagTextInfoInverse: palette.vivoPurple,
            tagTextSuccessInverse: palette.vivoGreenDark,
            tagTextWarningInverse: palette.orangeDark,
            tagTextErrorInverse: palette.pepperDark80,
            tagBackgroundPromoInverse: palette.vivoPurpleLight10,
            tagBackgroundActiveInverse: palette.vivoPurpleLight10,
            tagBackgroundInactiveInverse: palette.grey1,
            tagBackgroundInfoInverse: palette.vivoPurpleLight10,
            tagBackgroundSuccessInverse: palette.vivoGreenLight10,
            tagBackgroundWarningInverse: palette.orangeLight10,
            tagBackgroundErrorInverse: palette.pepperLight10,
            cardContentOverlay: `linear-gradient(180deg, ${applyAlpha(palette.grey6, 0)} 0%, ${applyAlpha(palette.grey6, 0.4)} 30%, ${applyAlpha(palette.grey6, 0.7)} 100%)`,
            cardFooterOverlay: applyAlpha(palette.grey6, 0.7),
        },
        darkModeColors: {
            background: palette.darkModeBlack,
            backgroundAlternative: palette.darkModeBlack,
            backgroundBrand: palette.darkModeBlack,
            backgroundBrandSecondary: palette.darkModeBlack,
            backgroundContainer: palette.darkModeGrey,
            backgroundContainerError: palette.darkModeGrey,
            backgroundContainerHover: applyAlpha(palette.white, 0.05),
            backgroundContainerPressed: applyAlpha(palette.white, 0.08),
            backgroundContainerBrand: palette.darkModeGrey,
            backgroundContainerBrandHover: applyAlpha(palette.white, 0.03),
            backgroundContainerBrandPressed: applyAlpha(palette.white, 0.05),
            backgroundContainerBrandOverInverse: palette.darkModeGrey,
            backgroundContainerAlternative: palette.darkModeGrey,
            backgroundOverlay: applyAlpha(palette.darkModeGrey, 0.8),
            backgroundSkeleton: palette.darkModeGrey6,
            backgroundSkeletonInverse: palette.darkModeGrey6,
            backgroundBrandTop: palette.darkModeBlack,
            backgroundBrandBottom: palette.darkModeBlack,
            appBarBackground: palette.darkModeGrey,
            navigationBarBackground: palette.darkModeBlack,
            skeletonWave: palette.grey5,
            borderLow: palette.darkModeBlack,
            border: palette.darkModeGrey,
            borderHigh: palette.grey5,
            borderSelected: palette.vivoPurple,
            coverBackgroundHover: applyAlpha(palette.darkModeBlack, 0.25),
            coverBackgroundPressed: applyAlpha(palette.darkModeBlack, 0.35),
            buttonDangerBackground: palette.pepper,
            buttonDangerBackgroundPressed: palette.pepperDark,
            buttonDangerBackgroundHover: palette.pepperDark,
            buttonLinkDangerBackgroundInverse: applyAlpha(palette.white, 0),
            buttonLinkDangerBackgroundMedia: palette.white,
            buttonLinkDangerBackgroundPressed: applyAlpha(palette.white, 0.08),
            buttonLinkDangerBackgroundInversePressed: applyAlpha(palette.white, 0.08),
            buttonLinkDangerBackgroundMediaPressed: palette.pepperLight10,
            buttonLinkBackgroundPressed: applyAlpha(palette.white, 0.08),
            buttonLinkBackgroundInversePressed: applyAlpha(palette.white, 0.08),
            buttonLinkBackgroundMediaPressed: applyAlpha(palette.white, 0.1),
            buttonPrimaryBackground: palette.vivoPurpleLight80,
            buttonPrimaryBackgroundInverse: palette.vivoPurpleLight80,
            buttonPrimaryBackgroundMedia: palette.white,
            buttonPrimaryBackgroundHover: palette.vivoPurpleDark,
            buttonPrimaryBackgroundInverseHover: palette.vivoPurpleDark,
            buttonPrimaryBackgroundMediaHover: palette.vivoPurpleLight50,
            buttonPrimaryBackgroundPressed: palette.vivoPurpleDark,
            buttonPrimaryBackgroundInversePressed: palette.vivoPurpleDark,
            buttonPrimaryBackgroundMediaPressed: palette.vivoPurpleLight50,
            buttonSecondaryBorder: palette.white,
            buttonSecondaryBorderInverse: palette.white,
            buttonSecondaryBorderMedia: palette.white,
            buttonSecondaryBorderPressed: palette.white,
            buttonSecondaryBorderInversePressed: palette.white,
            buttonSecondaryBorderMediaPressed: palette.white,
            buttonSecondaryBackgroundHover: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundInverseHover: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundMediaHover: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundPressed: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundInversePressed: applyAlpha(palette.white, 0.15),
            buttonSecondaryBackgroundMediaPressed: applyAlpha(palette.white, 0.15),
            textButtonPrimary: palette.grey2,
            textButtonPrimaryInverse: palette.grey2,
            textButtonPrimaryMedia: palette.vivoPurple,
            textButtonPrimaryInversePressed: palette.grey2,
            textButtonPrimaryMediaPressed: palette.vivoPurple,
            textButtonSecondary: palette.grey2,
            textButtonSecondaryInverse: palette.grey2,
            textButtonSecondaryMedia: palette.white,
            textButtonSecondaryPressed: palette.grey2,
            textButtonSecondaryInversePressed: palette.grey2,
            textButtonSecondaryMediaPressed: palette.white,
            textLink: palette.vivoPurpleLight50,
            textLinkInverse: palette.vivoPurpleLight50,
            textLinkMedia: palette.white,
            textLinkDanger: palette.pepper,
            textLinkDangerMedia: palette.pepper,
            textLinkSnackbar: palette.vivoPurpleLight50,
            textActivated: palette.vivoPurpleLight80,
            textBrand: palette.vivoPurpleLight80,
            inputBorder: palette.darkModeGrey6,
            inputBorderInverse: palette.darkModeGrey6,
            completedStep: palette.vivoPurpleLight80,
            completedStepInverse: palette.vivoPurpleLight80,
            control: palette.darkModeGrey6,
            controlActivated: palette.vivoPurpleLight80,
            controlInverse: palette.darkModeGrey6,
            controlActivatedInverse: palette.vivoPurpleLight80,
            controlError: palette.pepper,
            barTrack: palette.darkModeGrey6,
            barTrackInverse: palette.darkModeGrey6,
            loadingBar: palette.vivoPurpleLight80,
            loadingBarBackground: palette.darkModeGrey6,
            toggleAndroidInactive: palette.grey4,
            toggleAndroidBackgroundActive: palette.vivoPurpleLight50,
            iosControlKnob: palette.grey2,
            controlKnobInverse: palette.grey2,
            divider: applyAlpha(palette.white, 0.05),
            dividerInverse: applyAlpha(palette.white, 0.05),
            navigationBarDivider: palette.darkModeBlack,
            badge: palette.pepperDark,
            feedbackErrorBackground: palette.pepper,
            feedbackInfoBackground: palette.grey6,
            brand: palette.vivoPurpleLight80,
            brandHigh: applyAlpha(palette.white, 0.05),
            inverse: palette.grey2,
            neutralHigh: palette.grey2,
            neutralMedium: palette.grey5,
            neutralMediumInverse: palette.grey5,
            neutralLow: palette.darkModeGrey6,
            neutralLowAlternative: palette.darkModeGrey6,
            textPrimary: palette.grey2,
            textPrimaryInverse: palette.grey2,
            textPrimaryMedia: palette.white,
            textSecondary: palette.grey4,
            textSecondaryInverse: palette.grey4,
            textSecondaryMedia: palette.white,
            success: palette.vivoGreen,
            warning: palette.orange,
            error: palette.pepper,
            textError: palette.pepper,
            textErrorInverse: palette.pepper,
            promo: palette.vivoPurpleLight80,
            highlight: palette.pink,
            successLow: palette.darkModeGrey6,
            warningLow: palette.darkModeGrey6,
            errorLow: palette.darkModeGrey6,
            promoLow: palette.darkModeGrey6,
            brandLow: palette.darkModeGrey6,
            successHigh: palette.vivoGreenLight30,
            warningHigh: palette.orangeLight40,
            errorHigh: palette.pepperLight40,
            promoHigh: palette.vivoPurpleLight50,
            successHighInverse: palette.vivoGreenDark,
            warningHighInverse: palette.orangeDark,
            errorHighInverse: palette.pepperDark80,
            promoHighInverse: palette.vivoPurple,
            textNavigationBarPrimary: palette.grey2,
            textNavigationBarSecondary: palette.grey4,
            textNavigationSearchBarHint: palette.grey4,
            textNavigationSearchBarText: palette.grey2,
            textAppBar: palette.grey5,
            textAppBarSelected: palette.grey2,
            customTabsBackground: palette.darkModeBlack,
            tagTextPromo: palette.vivoPurpleLight50,
            tagTextActive: palette.vivoPurpleLight80,
            tagTextInactive: palette.grey5,
            tagTextInfo: palette.vivoPurpleLight80,
            tagTextSuccess: palette.vivoGreenLight30,
            tagTextWarning: palette.orangeLight40,
            tagTextError: palette.pepperLight40,
            tagBackgroundPromo: palette.darkModeGrey6,
            tagBackgroundActive: palette.darkModeGrey6,
            tagBackgroundInactive: palette.darkModeGrey6,
            tagBackgroundInfo: palette.darkModeGrey6,
            tagBackgroundSuccess: palette.darkModeGrey6,
            tagBackgroundWarning: palette.darkModeGrey6,
            tagBackgroundError: palette.darkModeGrey6,
            tagTextPromoInverse: palette.vivoPurpleLight50,
            tagTextActiveInverse: palette.vivoPurpleLight80,
            tagTextInactiveInverse: palette.grey5,
            tagTextInfoInverse: palette.vivoPurpleLight80,
            tagTextSuccessInverse: palette.vivoGreenLight30,
            tagTextWarningInverse: palette.orangeLight40,
            tagTextErrorInverse: palette.pepperLight40,
            tagBackgroundPromoInverse: palette.darkModeGrey6,
            tagBackgroundActiveInverse: palette.darkModeGrey6,
            tagBackgroundInactiveInverse: palette.darkModeGrey6,
            tagBackgroundInfoInverse: palette.darkModeGrey6,
            tagBackgroundSuccessInverse: palette.darkModeGrey6,
            tagBackgroundWarningInverse: palette.darkModeGrey6,
            tagBackgroundErrorInverse: palette.darkModeGrey6,
            cardContentOverlay: `linear-gradient(180deg, ${applyAlpha(palette.grey6, 0)} 0%, ${applyAlpha(palette.grey6, 0.4)} 30%, ${applyAlpha(palette.grey6, 0.7)} 100%)`,
            cardFooterOverlay: applyAlpha(palette.grey6, 0.7),
        },
        borderRadii: {
            avatar: '50%',
            bar: '999px',
            button: '4px',
            checkbox: '2px',
            container: '8px',
            indicator: '24px',
            chip: '24px',
            tag: '24px',
            input: '8px',
            legacyDisplay: '16px',
            popup: '8px',
            sheet: '8px',
            mediaSmall: '8px',
        },
        textPresets: {
            button: {weight: 'medium'},
            cardTitle: {weight: 'regular'},
            indicator: {weight: 'medium'},
            link: {weight: 'medium'},
            navigationBar: {weight: 'medium'},
            rowTitle: {weight: 'regular'},
            tabsLabel: {
                lineHeight: {desktop: 24, mobile: 24},
                size: {desktop: 18, mobile: 16},
                weight: 'medium',
            },
            text1: {lineHeight: {desktop: 20, mobile: 16}, size: {desktop: 14, mobile: 12}},
            text2: {lineHeight: {desktop: 24, mobile: 20}, size: {desktop: 16, mobile: 14}},
            text3: {lineHeight: {desktop: 24, mobile: 24}, size: {desktop: 18, mobile: 16}},
            text4: {lineHeight: {desktop: 28, mobile: 24}, size: {desktop: 20, mobile: 18}},
            text5: {lineHeight: {desktop: 32, mobile: 24}, size: {desktop: 28, mobile: 20}, weight: 'light'},
            text6: {lineHeight: {desktop: 40, mobile: 32}, size: {desktop: 32, mobile: 24}, weight: 'light'},
            text7: {lineHeight: {desktop: 48, mobile: 32}, size: {desktop: 40, mobile: 28}, weight: 'light'},
            text8: {lineHeight: {desktop: 56, mobile: 40}, size: {desktop: 48, mobile: 32}, weight: 'light'},
            text9: {lineHeight: {desktop: 64, mobile: 48}, size: {desktop: 56, mobile: 40}, weight: 'light'},
            text10: {lineHeight: {desktop: 72, mobile: 56}, size: {desktop: 64, mobile: 48}, weight: 'light'},
            title1: {weight: 'medium'},
            title2: {weight: 'light'},
            title3: {lineHeight: {desktop: 32, mobile: 24}, size: {desktop: 28, mobile: 20}, weight: 'light'},
        },
        themeVariants: {
            successFeedback: 'inverse',
            brandLoadingScreen: 'inverse',
        },
    };
    return skin;
};
