import React from "react"
import IconFileMp4Regular from "../../generated/mistica-icons/icon-file-mp-4-regular"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  IconFileMp4Regular,
  "https://www.figma.com/design/JHuzksh01yxExMeMQBvymq/M%C3%ADstica-Icons?node-id=36%3A5312",
  {
    props: {},
    example: (props) => <IconFileMp4Regular />,
  },
)
