import React from "react"
import IconArtificialIntelligenceFilled from "../../generated/mistica-icons/icon-artificial-intelligence-filled"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  IconArtificialIntelligenceFilled,
  "https://www.figma.com/design/JHuzksh01yxExMeMQBvymq/M%C3%ADstica-Icons?node-id=9538%3A3709",
  {
    props: {},
    example: () => <IconArtificialIntelligenceFilled />,
  },
)
