import React from "react"
import IconMobileAddUserLight from "../../generated/mistica-icons/icon-mobile-add-user-light"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  IconMobileAddUserLight,
  "https://www.figma.com/design/JHuzksh01yxExMeMQBvymq/M%C3%ADstica-Icons?node-id=7847%3A29206",
  {
    props: {},
    example: () => <IconMobileAddUserLight />,
  },
)
