import React from "react"
import IconConnectionDotTriangleRegular from "../../generated/mistica-icons/icon-connection-dot-triangle-regular"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  IconConnectionDotTriangleRegular,
  "https://www.figma.com/design/JHuzksh01yxExMeMQBvymq/M%C3%ADstica-Icons?node-id=13698%3A31980",
  {
    props: {},
    example: (props) => <IconConnectionDotTriangleRegular />,
  },
)
