import React from "react"
import IconIotSensorHumidityFilled from "../../generated/mistica-icons/icon-iot-sensor-humidity-filled"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  IconIotSensorHumidityFilled,
  "https://www.figma.com/design/JHuzksh01yxExMeMQBvymq/M%C3%ADstica-Icons?node-id=7886%3A9441",
  {
    props: {},
    example: () => <IconIotSensorHumidityFilled />,
  },
)
