import React from "react"
import IconFaceSlightlySadRegular from "../../generated/mistica-icons/icon-face-slightly-sad-regular"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  IconFaceSlightlySadRegular,
  "https://www.figma.com/design/JHuzksh01yxExMeMQBvymq/M%C3%ADstica-Icons?node-id=7463%3A45",
  {
    props: {},
    example: (props) => <IconFaceSlightlySadRegular />,
  },
)
