/**
 * This is a semantic release plugin that updates the version in the package-version.tsx file, and
 * the two ranges that keep this package and @telefonica/mistica-icons in lockstep.
 *
 * @semantic-release/npm writes the "version" field of both manifests, one instance for each
 * package. It does not know about the ranges between them, so this plugin writes those.
 */
const fs = require('fs').promises;
const path = require('path');

const versionFilePath = require.resolve('../src/package-version.tsx');
const rootPackagePath = require.resolve('../package.json');
const iconsPackagePath = path.join(__dirname, '..', 'packages', 'mistica-icons', 'package.json');

const writeVersionFile = async (version, logger) => {
    logger.log(`Writing new version in ${versionFilePath}`);
    const code = `// DO NOT EDIT THIS FILE. It's autogenerated by set-version.js\nexport const PACKAGE_VERSION = '${version}' as string;\n`;
    await fs.writeFile(versionFilePath, code, 'utf8');
    logger.log(code);
};

const writeRange = async (packagePath, apply, logger) => {
    const source = await fs.readFile(packagePath, 'utf8');
    const manifest = JSON.parse(source);
    apply(manifest);
    // keep the file style of the repository: four spaces and a final newline
    await fs.writeFile(packagePath, `${JSON.stringify(manifest, null, 4)}\n`, 'utf8');
    logger.log(`Updated the mistica range in ${packagePath}`);
};

const prepare = async (config, context) => {
    const {logger, nextRelease} = context;
    const range = `^${nextRelease.version}`;

    await writeVersionFile(nextRelease.version, logger);

    await writeRange(
        rootPackagePath,
        (manifest) => {
            manifest.dependencies['@telefonica/mistica-icons'] = range;
        },
        logger
    );

    await writeRange(
        iconsPackagePath,
        (manifest) => {
            manifest.peerDependencies['@telefonica/mistica'] = range;
        },
        logger
    );
};

module.exports = {prepare};
