import {dirname, resolve} from 'path';
import {fileURLToPath} from 'url';
import {VanillaExtractPlugin} from '@vanilla-extract/webpack-plugin';
import MiniCssExtractPlugin from 'mini-css-extract-plugin';

import type {StorybookConfig} from '@storybook/react-webpack5';

type WebpackConfig = Parameters<NonNullable<StorybookConfig['webpackFinal']>>[0];

// eslint-disable-next-line no-underscore-dangle
const __dirname = dirname(fileURLToPath(import.meta.url));

/**
 * This function is used to resolve the absolute path of a package.
 * It is needed in projects that use Yarn PnP or are set up within a monorepo.
 */
const getAbsolutePath = (value: string): any => {
    return dirname(fileURLToPath(import.meta.resolve?.(`${value}/package.json`) as any));
};

const addVanillaExtractSupport = (config: WebpackConfig) => {
    // Look for rules that match CSS files and make them ignore `.vanilla.css` files (CSS files generated by vanilla-extract)
    config.module?.rules?.forEach((rawRule) => {
        const rule = rawRule as {test?: RegExp | Array<RegExp>; exclude?: RegExp | Array<RegExp>};
        const ruleTest = rule.test as RegExp | Array<RegExp> | undefined;
        if (
            ruleTest &&
            (Array.isArray(ruleTest)
                ? ruleTest.some((exp) => exp.test('random.css'))
                : ruleTest.test('random.css'))
        ) {
            const previousExclude = rule.exclude || [];
            rule.exclude = [
                ...(Array.isArray(previousExclude) ? previousExclude : [previousExclude]),
                /\.vanilla\.css$/,
            ];
        }
    });

    // We add the ignoreOrder flag to supress several warnings regarding conflicts in the order of imports.
    // https://stackoverflow.com/questions/51971857/mini-css-extract-plugin-warning-in-chunk-chunkname-mini-css-extract-plugin-con/67579319#67579319
    config.plugins?.push(
        new VanillaExtractPlugin() as any,
        new MiniCssExtractPlugin({ignoreOrder: true}) as any
    );
    config.module?.rules?.push({
        test: /\.vanilla\.css$/i, // Targets only CSS files generated by vanilla-extract
        use: [
            MiniCssExtractPlugin.loader,
            {
                loader: getAbsolutePath('css-loader'),
                options: {
                    url: false, // Required as image imports should be handled via JS/TS import statements
                },
            },
            getAbsolutePath('postcss-loader'),
        ],
    });
};

const stories = [
    './welcome-story.tsx',
    '../src/__stories__/*-story.tsx',
    '../src/icons/__stories__/*-story.tsx',
    '../src/community/__stories__/index-story.tsx',
    '../src/community/__stories__/*-story.tsx',
];

const config: StorybookConfig = {
    stories,
    addons: [
        getAbsolutePath('@storybook/addon-webpack5-compiler-swc'),
        {
            name: '@storybook/addon-storysource',
            options: {
                rule: {
                    test: [/-story\.tsx/, /welcome-story\.js/],
                    include: [resolve(__dirname, '..', 'src'), __dirname],
                },
                loaderOptions: {
                    prettierConfig: {printWidth: 80, singleQuote: false},
                },
            },
        },
        './theme-selector-addon/preset.ts',
        './dark-mode-addon/preset.ts',
        './font-size-addon/preset.ts',
        './theme-selector-addon/preset.ts',
        './platform-selector-addon/preset.ts',
    ],
    framework: getAbsolutePath('@storybook/react-webpack5'),
    webpackFinal: async (config) => {
        config.watchOptions = {
            ...config.watchOptions,
            ignored: [
                '**/node_modules',
                '**/__tests__',
                '**/__acceptance_tests__',
                '**/__screenshot_tests__',
            ],
        };
        addVanillaExtractSupport(config);
        return config;
    },
    // building stories is slow without this workaround
    // https://github.com/storybookjs/storybook/issues/10784#issuecomment-868329216
    typescript: {
        check: false,
        reactDocgen: false,
    },
};
export default config;
