import {dirname} from 'path';
import {fileURLToPath} from 'url';
import {VanillaExtractPlugin} from '@vanilla-extract/webpack-plugin';
import MiniCssExtractPlugin from 'mini-css-extract-plugin';
// @ts-expect-error Missing types
import WebpackReactComponentNamePlugin from 'webpack-react-component-name';
import webpack from 'webpack';

import type {StorybookConfig} from '@storybook/react-webpack5';

type WebpackConfig = Parameters<NonNullable<StorybookConfig['webpackFinal']>>[0];

/**
 * This function is used to resolve the absolute path of a package.
 * It is needed in projects that use Yarn PnP or are set up within a monorepo.
 */
const getAbsolutePath = (value: string): any => {
    return dirname(fileURLToPath(import.meta.resolve?.(`${value}/package.json`) as any));
};

const addVanillaExtractSupport = (config: WebpackConfig) => {
    // Look for rules that match CSS files and make them ignore `.vanilla.css` files (CSS files generated by vanilla-extract)
    config.module?.rules?.forEach((rawRule) => {
        const rule = rawRule as {test?: RegExp | Array<RegExp>; exclude?: RegExp | Array<RegExp>};
        const ruleTest = rule.test as RegExp | Array<RegExp> | undefined;
        if (
            ruleTest &&
            (Array.isArray(ruleTest)
                ? ruleTest.some((exp) => exp.test('random.css'))
                : ruleTest.test('random.css'))
        ) {
            const previousExclude = rule.exclude || [];
            rule.exclude = [
                ...(Array.isArray(previousExclude) ? previousExclude : [previousExclude]),
                /\.vanilla\.css$/,
            ];
        }
    });

    // We add the ignoreOrder flag to supress several warnings regarding conflicts in the order of imports.
    // https://stackoverflow.com/questions/51971857/mini-css-extract-plugin-warning-in-chunk-chunkname-mini-css-extract-plugin-con/67579319#67579319
    config.plugins?.push(
        new VanillaExtractPlugin() as any,
        new MiniCssExtractPlugin({ignoreOrder: true}) as any
    );
    config.module?.rules?.push({
        test: /\.vanilla\.css$/i, // Targets only CSS files generated by vanilla-extract
        use: [
            MiniCssExtractPlugin.loader,
            {
                loader: getAbsolutePath('css-loader'),
                options: {
                    url: false, // Required as image imports should be handled via JS/TS import statements
                },
            },
            getAbsolutePath('postcss-loader'),
        ],
    });
};

const stories = [
    './welcome-story.tsx',
    '../src/__stories__/*-story.tsx',
    '../src/icons/__stories__/*-story.tsx',
    '../src/community/__stories__/index-story.tsx',
    '../src/community/__stories__/*-story.tsx',
];

const shouldIncludePrivateStories = !process.env.VERCEL_PROD_BUILD;

if (shouldIncludePrivateStories) {
    stories.push('../src/**/__private_stories__/*-story.tsx');
}

const config: StorybookConfig = {
    stories,

    addons: [
        getAbsolutePath('@storybook/addon-webpack5-compiler-swc'),
        getAbsolutePath('@storybook/addon-docs'),
        './theme-selector-addon/preset.ts',
        './dark-mode-addon/preset.ts',
        './font-size-addon/preset.ts',
        './theme-selector-addon/preset.ts',
        './platform-selector-addon/preset.ts',
    ],

    framework: getAbsolutePath('@storybook/react-webpack5'),

    staticDirs: ['./css/fonts'],

    webpackFinal: async (config) => {
        config.watchOptions = {
            ...config.watchOptions,
            ignored: [
                '**/node_modules',
                '**/__tests__',
                '**/__acceptance_tests__',
                '**/__screenshot_tests__',
            ],
        };

        // Define process.env variables for browser
        config.plugins?.push(
            /** workaround for: https://github.com/storybookjs/storybook/issues/22287 */
            new WebpackReactComponentNamePlugin(),
            new webpack.DefinePlugin({
                'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV || 'development'),
                'process.env.SSR_TEST': JSON.stringify(''),
            }) as any
        );

        addVanillaExtractSupport(config);
        return config;
    },

    // building stories is slow without this workaround
    // https://github.com/storybookjs/storybook/issues/10784#issuecomment-868329216
    typescript: {
        check: false,
        reactDocgen: false,
    },

    /** hide interactions tab */
    features: {
        interactions: false,
    },

    core: {
        disableWhatsNewNotifications: true,
    },
};

export default config;
