import React from 'react';
import {Accordion} from '../../accordion';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Accordion,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=25050%3A313',
    {
        links: [
            {
                name: 'Mobile',
                url: 'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/Mística-Mobile?node-id=25050%3A313',
            },
        ],
        props: {
            divider: figma.boolean('Divider'),
            replaceSlot: figma.instance('🔄 Replace slot'),
            autoCollapse: figma.boolean('Auto collapse'),
            asset: figma.boolean('Asset'),
            detail: figma.boolean('Detail'),
            rightSlot: figma.boolean('Right slot'),
            replaceRightSlot: figma.instance('🔄 Replace right slot'),
            themeContext: figma.enum('Theme context', {
                Default: 'default',
                Inverse: 'inverse',
            }),
            open: figma.boolean('Open'),
            subtitle: figma.boolean('Subtitle'),
            customContent: figma.boolean('Custom content'),
        },
        example: (props) => <Accordion />,
    }
);
