import React from 'react';
import {AdvancedDataCard} from '../../community/advanced-data-card';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    AdvancedDataCard,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=22670%3A11143',
    {
        props: {
            topActions: figma.boolean('Top actions'),
            tag: figma.boolean('Tag'),
            title: figma.boolean('Title'),
            subtitle: figma.boolean('Subtitle'),
            description: figma.boolean('Description'),
            slot01: figma.boolean('Slot 01'),
            slot02: figma.boolean('Slot 02'),
            slot03: figma.boolean('Slot 03'),
            replaceSlot01: figma.instance('🔄 Replace slot 01'),
            replaceSlot02: figma.instance('🔄 Replace slot 02'),
            replaceSlot03: figma.instance('🔄 Replace slot 03'),
            footer: figma.boolean('Footer'),
            stackedGroup: figma.boolean('Stacked group'),
            pretitle: figma.boolean('Pretitle'),
            spacerLarger: figma.boolean('Spacer larger'),
            dividers: figma.boolean('Dividers'),
        },
        example: (props) => <AdvancedDataCard />,
    }
);
