import React from 'react';
import Avatar from '../../avatar';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Avatar,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=4772%3A9007',
    {
        props: {
            chooseIcon: figma.instance('Choose icon'),
            initials: figma.string('Initials'),
            badge: figma.boolean('Badge'),
            border: figma.boolean('Border'),
            themeContext: figma.enum('Theme context', {
                Default: 'default',
                Inverse: 'inverse',
            }),
            type: figma.enum('Type', {
                Image: 'image',
                Icon: 'icon',
                Initials: 'initials',
            }),
            '40Px': figma.boolean('< 40px'),
        },
        example: (props) => <Avatar />,
    }
);
