import React from 'react';
import Badge from '../../badge';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Badge,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=6180%3A9123',
    {
        props: {
            themeContext: figma.enum('Theme context', {
                Default: 'default',
                Inverse: 'inverse',
            }),
            '9': figma.boolean('+9'),
            nonnumeric: figma.boolean('Non-numeric'),
        },
        example: (props) => <Badge />,
    }
);
