import React from 'react';
import {
    HighlightedValueBlock,
    InformationBlock,
    ProgressBlock,
    SimpleBlock,
    RowBlock,
    ValueBlock,
} from '../../community/blocks';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    HighlightedValueBlock,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=22670%3A11222',
    {
        props: {
            tag: figma.boolean('Tag'),
            title: figma.boolean('Title'),
            description01: figma.boolean('Description 01'),
            description02: figma.boolean('Description 02'),
            heading02: figma.boolean('Heading 02'),
            heading03: figma.boolean('Heading 03'),
            heading04: figma.boolean('Heading 04'),
            strikedValue: figma.boolean('Striked value'),
            pretitle: figma.boolean('Pretitle'),
        },
        example: (props) => <HighlightedValueBlock />,
    }
);

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    InformationBlock,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=22670%3A11214',
    {
        props: {
            secondaryValue: figma.boolean('Secondary value'),
            title: figma.boolean('Title'),
            description01: figma.boolean('Description 01'),
            description02: figma.boolean('Description 02'),
            mainValue: figma.boolean('Main Value'),
        },
        example: (props) => <InformationBlock />,
    }
);

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    ProgressBlock,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=22670%3A11188',
    {
        props: {
            header: figma.boolean('Header'),
            stackedGroup: figma.boolean('Stacked group'),
            progressBar: figma.boolean('ProgressBar'),
            description: figma.boolean('Description'),
        },
        example: (props) => <ProgressBlock />,
    }
);

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    SimpleBlock,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=22670%3A11238',
    {
        props: {
            image: figma.boolean('Image'),
            description: figma.boolean('Description'),
            rightText: figma.boolean('Right text'),
        },
        example: (props) => <SimpleBlock />,
    }
);

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    RowBlock,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=22670%3A11199',
    {
        props: {
            title: figma.boolean('Title'),
            stackedGroup: figma.boolean('Stacked group'),
            description: figma.boolean('Description'),
        },
        example: (props) => <RowBlock />,
    }
);

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    ValueBlock,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=22670%3A11206',
    {
        props: {
            title: figma.boolean('Title'),
            value: figma.boolean('Value'),
            description01: figma.boolean('Description 01'),
            description02: figma.boolean('Description 02'),
        },
        example: (props) => <ValueBlock />,
    }
);
