import React from 'react';
import ButtonLayout from '../../button-layout';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    ButtonLayout,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=35946%3A4151',
    {
        props: {
            themeContext: figma.enum('Theme context', {
                Default: 'default',
                Inverse: 'inverse',
                Media: 'media',
            }),
            align: figma.enum('Align', {
                'Full width': 'full-width',
                Left: 'left',
                Center: 'center',
                Right: 'right',
            }),
            longLabels: figma.boolean('Long labels'),
            primary: figma.boolean('Primary'),
            secondary: figma.boolean('Secondary'),
            link: figma.boolean('Link'),
        },
        example: (props) => <ButtonLayout />,
    }
);
