import React from 'react';
import ButtonGroup from '../../button-group';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    ButtonGroup,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=184%3A5972',
    {
        props: {
            themeContext: figma.enum('🚫 Theme context', {
                Default: 'default',
                Inverse: 'inverse',
                Media: 'media',
            }),
            variant: figma.enum('Variant', {
                'Primary+ButtonLink': 'primary-buttonlink',
                ButtonLink: 'buttonlink',
                Primary: 'primary',
                'Secondary+ButtonLink': 'secondary-buttonlink',
                Secondary: 'secondary',
                'Primary+Secondary': 'primary-secondary',
            }),
            small: figma.boolean('Small'),
            alignment: figma.enum('Alignment', {
                'Space-between': 'space-between',
                Left: 'left',
            }),
        },
        example: (props) => <ButtonGroup />,
    }
);
