import React from 'react';
import {ButtonDanger, ButtonLink, ButtonPrimary} from '../../button';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    ButtonDanger,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=22230%3A10269',
    {
        props: {
            chooseIcon: figma.instance('Choose icon'),
            state: figma.enum('State', {
                Default: 'default',
                Disabled: 'disabled',
                Loading: 'loading',
                Pressed: 'pressed',
            }),
            small: figma.boolean('Small'),
            icon: figma.enum('Icon', {
                None: 'none',
                StartIcon: 'starticon',
                EndIcon: 'endicon',
            }),
        },
        example: (props) => <ButtonDanger />,
    }
);

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    ButtonLink,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=22230%3A10270',
    {
        props: {
            chooseIcon: figma.instance('Choose icon'),
            navigation: figma.boolean('Navigation'),
            themeContext: figma.enum('Theme context', {
                Default: 'default',
                Inverse: 'inverse',
                Media: 'media',
            }),
            state: figma.enum('State', {
                Default: 'default',
                Disabled: 'disabled',
                Loading: 'loading',
                Pressed: 'pressed',
            }),
            small: figma.boolean('Small'),
            icon: figma.enum('Icon', {
                None: 'none',
                StartIcon: 'starticon',
                EndIcon: 'endicon',
            }),
            bleedY: figma.boolean('BleedY'),
            bleedLeft: figma.boolean('BleedLeft'),
            bleedRight: figma.boolean('BleedRight'),
        },
        example: (props) => <ButtonLink />,
    }
);

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    ButtonPrimary,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=31%3A4085',
    {
        props: {
            chooseIcon: figma.instance('Choose icon'),
            themeContext: figma.enum('Theme context', {
                Inverse: 'inverse',
                Default: 'default',
                Media: 'media',
            }),
            state: figma.enum('State', {
                Default: 'default',
                Pressed: 'pressed',
                Disabled: 'disabled',
                Loading: 'loading',
            }),
            small: figma.boolean('Small'),
            icon: figma.enum('Icon', {
                None: 'none',
                StartIcon: 'starticon',
                EndIcon: 'endicon',
            }),
        },
        example: (props) => <ButtonPrimary />,
    }
);
