import React from 'react';
import Callout from '../../callout';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Callout,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=775%3A154',
    {
        props: {
            asset: figma.boolean('Asset'),
            dismissable: figma.boolean('Dismissable'),
            action: figma.boolean('Action'),
            title: figma.boolean('Title'),
            themeContext: figma.enum('Theme context', {
                Default: 'default',
                Inverse: 'inverse',
                Alternative: 'alternative',
            }),
            type: figma.enum('Type', {
                Default: 'default',
                Alert: 'alert',
                Critical: 'critical',
                Informative: 'informative',
            }),
        },
        example: (props) => <Callout />,
    }
);
