import React from 'react';
import {DataCard} from '../../card-data';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    DataCard,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=12965%3A8508',
    {
        props: {
            slot: figma.boolean('Slot'),
            replaceSlot: figma.instance('🔄 Replace Slot'),
            topActions: figma.boolean('Top actions'),
            tag: figma.boolean('Tag'),
            asset: figma.boolean('Asset'),
            title: figma.boolean('Title'),
            subtitle: figma.boolean('Subtitle'),
            pretitle: figma.boolean('Pretitle'),
            description: figma.boolean('Description'),
            actions: figma.boolean('Actions'),
            aspectRatioValue: figma.instance('Aspect ratio value'),
            footerSlot: figma.boolean('Footer slot'),
            replaceFooterSlot: figma.instance('🔄 Replace footer slot'),
            themeContext: figma.enum('Theme context', {
                Default: 'default',
                Inverse: 'inverse',
            }),
            variant: figma.enum('Variant', {
                Default: 'default',
                Inverse: 'inverse',
            }),
            size: figma.enum('Size', {
                Default: 'default',
                Snap: 'snap',
                Display: 'display',
            }),
            footer: figma.boolean('Footer'),
            aspectRatio: figma.boolean('Aspect ratio'),
        },
        example: (props) => <DataCard />,
    }
);
