import React from 'react';
import {NakedCard} from '../../card-naked';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    NakedCard,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=22748%3A12424',
    {
        props: {
            replaceSlot: figma.instance('🔄 Replace slot'),
            pretitle: figma.boolean('Pretitle'),
            slot: figma.boolean('Slot'),
            asset: figma.boolean('Asset'),
            topActions: figma.boolean('Top actions'),
            subtitle: figma.boolean('Subtitle'),
            actions: figma.boolean('Actions'),
            description: figma.boolean('Description'),
            title: figma.boolean('Title'),
            tag: figma.boolean('Tag'),
            videoControls: figma.boolean('Video controls'),
            aspectRatioValue: figma.instance('Aspect ratio value'),
            footerSlot: figma.boolean('Footer slot'),
            replaceFooterSlot: figma.instance('🔄 Replace footer slot'),
            themeContext: figma.enum('Theme context', {
                Default: 'default',
                Inverse: 'inverse',
            }),
            size: figma.enum('Size', {
                Default: 'default',
                Display: 'display',
                Snap: 'snap',
            }),
            mediaPosition: figma.enum('Media position', {
                Top: 'top',
                Right: 'right',
                Left: 'left',
                None: 'none',
            }),
            mediaType: figma.enum('Media type', {
                Image: 'image',
                None: 'none',
                'Circular image': 'circular-image',
                '❗ Video [Deprecated]': '--video--deprecated-',
            }),
            footer: figma.boolean('Footer'),
            aspectRatio: figma.boolean('Aspect ratio'),
        },
        example: (props) => <NakedCard />,
    }
);
