import React from 'react';
import {CoverCard} from '../../card-cover';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    CoverCard,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=13305%3A10725',
    {
        props: {
            tag: figma.boolean('Tag'),
            pretitle: figma.boolean('Pretitle'),
            description: figma.boolean('Description'),
            topActions: figma.boolean('Top actions'),
            aspectRatioValue: figma.instance('Aspect ratio value'),
            asset: figma.boolean('Asset'),
            subtitle: figma.boolean('Subtitle'),
            slot: figma.boolean('Slot'),
            replaceSlot: figma.instance('🔄 Replace slot'),
            videoControls: figma.boolean('Video controls'),
            actions: figma.boolean('Actions'),
            replaceFooterSlot: figma.instance('🔄 Replace footer slot'),
            footerSlot: figma.boolean('Footer slot'),
            title: figma.boolean('Title'),
            themeContext: figma.enum('Theme context', {
                Default: 'default',
                Inverse: 'inverse',
            }),
            variant: figma.enum('Variant', {
                Media: 'media',
                Inverse: 'inverse',
                Default: 'default',
                Alternative: 'alternative',
            }),
            background: figma.enum('Background', {
                Image: 'image',
                'Custom color': 'custom-color',
            }),
            size: figma.enum('Size', {
                Default: 'default',
                Display: 'display',
                Snap: 'snap',
            }),
            footer: figma.boolean('Footer'),
            aspectRatio: figma.boolean('Aspect ratio'),
        },
        example: (props) => <CoverCard />,
    }
);
