import React from 'react';
import {Carousel} from '../../carousel';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Carousel,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=4229%3A8914',
    {
        props: {
            slide1: figma.instance('Slide 1 →'),
            slide2: figma.instance('Slide 2 →'),
            slide3: figma.instance('Slide 3 →'),
            slide4: figma.instance('Slide 4 →'),
            slide5: figma.instance('Slide 5 →'),
            showBullets: figma.boolean('Show Bullets'),
            autoplay: figma.boolean('Autoplay'),
            controls: figma.boolean('Controls'),
            themeContext: figma.enum('Theme context', {
                Inverse: 'inverse',
                Default: 'default',
            }),
            nOfSlides: figma.enum('Nº of slides', {
                '3': '3',
                '4': '4',
                '5': '5',
            }),
            currentSlide: figma.enum('Current slide', {
                '#1': '-1',
                '#2': '-2',
                '#3': '-3',
                '#4': '-4',
                '#5': '-5',
            }),
            itemsPerPage: figma.enum('Items per page', {
                '1': '1',
                '2': '2',
            }),
            pageOffsetMobileOnly: figma.enum('Page Offset (mobile only)', {
                Regular: 'regular',
                Large: 'large',
            }),
        },
        example: (props) => <Carousel />,
    }
);
