import React from 'react';
import Checkbox from '../../checkbox';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Checkbox,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=3114%3A10236',
    {
        props: {
            themeContext: figma.enum('Theme context', {
                Default: 'default',
                Inverse: 'inverse',
            }),
            disabled: figma.boolean('Disabled'),
        },
        example: (props) => <Checkbox />,
    }
);

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Checkbox,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=1952%3A7131',
    {
        props: {
            themeContext: figma.enum('Theme context', {
                Inverse: 'inverse',
                Default: 'default',
            }),
            state: figma.boolean('State'),
            disabled: figma.boolean('Disabled'),
        },
        example: (props) => <Checkbox />,
    }
);
