import React from 'react';
import Chip from '../../chip';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Chip,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=3610%3A9110',
    {
        props: {
            chooseIcon: figma.instance('Choose icon →'),
            variant: figma.enum('Variant', {
                Brand: 'brand',
                Default: 'default',
            }),
            icon: figma.boolean('Icon'),
            selected: figma.boolean('Selected'),
            closable: figma.boolean('Closable'),
            badge: figma.boolean('Badge'),
            type: figma.enum('Type', {
                Action: 'action',
                Selection: 'selection',
            }),
        },
        example: (props) => <Chip />,
    }
);
