import React from 'react';
import Counter from '../../counter';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Counter,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=24524%3A1267',
    {
        props: {
            remove: figma.boolean('Remove'),
            disabled: figma.boolean('Disabled'),
            maxValue: figma.boolean('MaxValue'),
            minValue: figma.boolean('MinValue'),
        },
        example: (props) => <Counter />,
    }
);
