import React from 'react';
import CreditCardExpirationField from '../../credit-card-expiration-field';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    CreditCardExpirationField,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=15432%3A9465',
    {
        props: {
            helperText: figma.boolean('Helper text'),
            themeContext: figma.enum('Theme Context', {
                Inverse: 'inverse',
                Default: 'default',
            }),
            state: figma.enum('State', {
                Inactive: 'inactive',
                Focused: 'focused',
                Activated: 'activated',
            }),
            error: figma.boolean('Error'),
            disabled: figma.boolean('Disabled'),
            readOnly: figma.boolean('Read only'),
        },
        example: (props) => <CreditCardExpirationField />,
    }
);
