import React from 'react';
import Dialog from '../../dialog';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Dialog,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=10722%3A6907',
    {
        props: {
            title: figma.boolean('Title'),
        },
        example: (props) => <Dialog />,
    }
);

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Dialog,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=10720%3A7368',
    {
        props: {
            slot: figma.boolean('Slot'),
            subtitle: figma.boolean('Subtitle'),
            description: figma.boolean('Description'),
            asset: figma.boolean('Asset'),
            chooseAsset: figma.instance('Choose asset'),
            title: figma.boolean('Title'),
        },
        example: (props) => <Dialog />,
    }
);

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Dialog,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=1953%3A10250',
    {
        props: {
            title: figma.boolean('Title'),
        },
        example: (props) => <Dialog />,
    }
);
