import React from 'react';
import Drawer from '../../drawer';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Drawer,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=48528%3A4975',
    {
        props: {
            title: figma.boolean('Title'),
            description: figma.boolean('Description'),
            subtitle: figma.boolean('Subtitle'),
            slot: figma.boolean('Slot'),
            replaceSlot: figma.instance('🔄 Replace Slot'),
            contentOverflow: figma.boolean('Content overflow'),
            dismiss: figma.boolean('Dismiss'),
            actions: figma.boolean('Actions'),
        },
        example: (props) => <Drawer />,
    }
);
