import React from 'react';
import EmptyState from '../../empty-state';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    EmptyState,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=765%3A53',
    {
        props: {
            chooseAsset: figma.instance('Choose asset'),
            actions: figma.boolean('Actions'),
            assetType: figma.enum('Asset type', {
                Large: 'large',
                Small: 'small',
                Icon: 'icon',
            }),
        },
        example: (props) => <EmptyState />,
    }
);
