import React from 'react';
import {
    ErrorFeedbackScreen,
    InfoFeedbackScreen,
    SuccessFeedback,
    SuccessFeedbackScreen,
} from '../../feedback';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
    ErrorFeedbackScreen,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=567%3A9999',
    {
        props: {
            // No matching props could be found for these Figma properties:
            // "slot": figma.boolean('Slot')
        },
        example: (props) => <ErrorFeedbackScreen title={/* TODO */} />,
    }
);

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
    InfoFeedbackScreen,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=567%3A10354',
    {
        props: {
            // No matching props could be found for these Figma properties:
            // "slot": figma.instance('Slot →'),
            // "slot": figma.boolean('Slot'),
            // "chooseIcon": figma.instance('Choose icon')
        },
        example: (props) => <InfoFeedbackScreen title={/* TODO */} />,
    }
);

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
    SuccessFeedback,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=53562%3A5654',
    {
        props: {},
        example: (props) => <SuccessFeedback title={/* TODO */} />,
    }
);

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
    SuccessFeedbackScreen,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=53562%3A5202',
    {
        props: {},
        example: (props) => <SuccessFeedbackScreen title={/* TODO */} />,
    }
);
