import React from 'react';
import FixedFooterLayout from '../../fixed-footer-layout';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    FixedFooterLayout,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=1335%3A6535',
    {
        props: {
            shadow: figma.boolean('Shadow'),
            slot: figma.enum('Slot', {
                Yes: 'yes',
            }),
        },
        example: (props) => <FixedFooterLayout />,
    }
);
