import React from 'react';
import {Header} from '../../header';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Header,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=17101%3A10577',
    {
        props: {
            description: figma.boolean('Description'),
            pretitle: figma.boolean('Pretitle'),
            replaceSlot: figma.instance('🔄 Replace slot'),
            slot: figma.boolean('Slot'),
            title: figma.boolean('Title'),
            content: figma.boolean('Content'),
            tag: figma.boolean('Tag'),
            inverse: figma.boolean('Inverse'),
            small: figma.boolean('Small'),
            bleed: figma.boolean('Bleed'),
            paddingY: figma.boolean('PaddingY'),
            slotType: figma.enum('Slot type', {
                Slot: 'slot',
                Carousel: 'carousel',
            }),
        },
        example: (props) => <Header />,
    }
);
