import React from 'react';
import Hero from '../../hero';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Hero,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=15890%3A11120',
    {
        props: {
            slideshowBullets: figma.boolean('Slideshow bullets'),
            slideshow: figma.boolean('Slideshow'),
            slideshowAutoplay: figma.boolean('Slideshow autoplay'),
            height: figma.enum('Height', {
                Hug: 'hug',
                Fixed: 'fixed',
            }),
            background: figma.enum('Background', {
                Default: 'default',
                Brand: 'brand',
                'Brand Secondary': 'brand-secondary',
                Alternative: 'alternative',
            }),
            noPaddingY: figma.boolean('NoPaddingY'),
        },
        example: (props) => <Hero />,
    }
);
