import React from 'react';
import {IconButton} from '../../icon-button';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    IconButton,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=2044%3A7604',
    {
        props: {
            chooseIcon: figma.instance('Choose icon'),
            themeContext: figma.enum('Theme context', {
                Default: 'default',
                Inverse: 'inverse',
                Alternative: 'alternative',
                Media: 'media',
            }),
            type: figma.enum('Type', {
                Brand: 'brand',
                Neutral: 'neutral',
                Danger: 'danger',
            }),
            backgroundType: figma.enum('Background type', {
                Solid: 'solid',
                Soft: 'soft',
                Transparent: 'transparent',
                '—': '-',
            }),
            state: figma.enum('State', {
                Default: 'default',
                Loading: 'loading',
                Disabled: 'disabled',
            }),
            small: figma.boolean('Small'),
        },
        example: (props) => <IconButton />,
    }
);
