import React from 'react';
import Image from '../../image';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Image,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=569%3A24369',
    {
        props: {
            themeContext: figma.enum('Theme context', {
                '—': '-',
                Default: 'default',
                Inverse: 'inverse',
            }),
            type: figma.enum('Type', {
                'Aspect Ratio': 'aspect-ratio',
                Circular: 'circular',
                Free: 'free',
            }),
            aspectRatio: figma.enum('Aspect Ratio', {
                '1:1': '1-1',
                '4:3': '4-3',
                '7:10': '7-10',
                '16:9': '16-9',
                '21:9': '21-9',
                '—': '-',
            }),
            fallbackState: figma.boolean('Fallback state'),
            borderRadius: figma.boolean('Border radius'),
            border: figma.boolean('Border'),
        },
        example: (props) => <Image />,
    }
);
