import React from 'react';
import {BoxedRow} from '../../list';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    BoxedRow,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=1428%3A8270',
    {
        props: {
            themeContext: figma.enum('Theme context', {
                Default: 'default',
                Inverse: 'inverse',
            }),
            inverse: figma.boolean('Inverse'),
            centered: figma.boolean('Centered'),
            disabled: figma.boolean('Disabled'),
            danger: figma.boolean('Danger'),
        },
        example: (props) => <BoxedRow />,
    }
);
