import React from 'react';
import {LoadingScreen} from '../../loading-screen';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    LoadingScreen,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=32834%3A517',
    {
        props: {
            description: figma.boolean('Description'),
            title: figma.boolean('Title'),
            content: figma.boolean('Content'),
            themeContext: figma.enum('Theme context', {
                Default: 'default',
                Inverse: 'inverse',
            }),
        },
        example: (props) => <LoadingScreen />,
    }
);
