import React from 'react';
import {Menu} from '../../menu';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Menu,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=26711%3A3771',
    {
        props: {
            item1: figma.boolean('Item 1'),
            item2: figma.boolean('Item 2'),
            item3: figma.boolean('Item 3'),
            item4: figma.boolean('Item 4'),
            item5: figma.boolean('Item 5'),
        },
        example: (props) => <Menu />,
    }
);
