import React from 'react';
import Meter from '../../meter';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Meter,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=46432%3A4971',
    {
        props: {
            reverse: figma.boolean('Reverse'),
            replaceSlot: figma.instance('🔄 Replace slot'),
            slot: figma.boolean('Slot'),
            variant: figma.enum('Variant', {
                Brand: 'brand',
                Default: 'default',
            }),
            type: figma.enum('Type', {
                Linear: 'linear',
                Angular: 'angular',
                Circular: 'circular',
            }),
            totalValue: figma.enum('Total value', {
                '0%': '0-',
                '25%': '25-',
                '50%': '50-',
                '75%': '75-',
                '100%': '100-',
            }),
            segments: figma.enum('Segments', {
                '1': '1',
                '2': '2',
                '3': '3',
                '4': '4',
                '5': '5',
                '6': '6',
                '7': '7',
                '8': '8',
            }),
        },
        example: (props) => <Meter />,
    }
);
