import React from 'react';
import {HorizontalMosaic, VerticalMosaic} from '../../mosaic';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
    HorizontalMosaic,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=32416%3A2749',
    {
        props: {
            // These props were automatically mapped based on your linked code:
            withBullets: figma.boolean('Show bullets'),
            // No matching props could be found for these Figma properties:
            // "showBullets": figma.boolean('Show bullets'),
            // "item1": figma.instance('Item 1'),
            // "item2": figma.instance('Item 2'),
            // "item3": figma.instance('Item 3'),
            // "item4": figma.instance('Item 4'),
            // "item5": figma.instance('Item 5'),
            // "item6": figma.instance('Item 6'),
            // "item7": figma.instance('Item 7'),
            // "item8": figma.instance('Item 8'),
            // "items": figma.enum('Items', {
            //   "1": "1",
            //   "2": "2",
            //   "3": "3",
            //   "4": "4",
            //   "5": "5",
            //   "6": "6",
            //   "7": "7",
            //   "8": "8"
            // }),
            // "page": figma.enum('Page', {
            //   "1": "1",
            //   "2": "2",
            //   "3": "3",
            //   "—": "-"
            // }),
            // "slot": figma.boolean('Slot')
        },
        example: (props) => <HorizontalMosaic items={/* TODO */} withBullets={props.withBullets} />,
    }
);

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
    VerticalMosaic,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=32415%3A986',
    {
        props: {
            // No matching props could be found for these Figma properties:
            // "item1": figma.instance('Item 1'),
            // "item2": figma.instance('Item 2'),
            // "item3": figma.instance('Item 3'),
            // "item4": figma.instance('Item 4'),
            // "item5": figma.instance('Item 5'),
            // "item6": figma.instance('Item 6'),
            // "item7": figma.instance('Item 7'),
            // "item8": figma.instance('Item 8'),
            // "items": figma.enum('Items', {
            //   "1": "1",
            //   "2": "2",
            //   "3": "3",
            //   "4": "4",
            //   "5": "5",
            //   "6": "6",
            //   "7": "7",
            //   "8": "8"
            // }),
            // "slot": figma.boolean('Slot')
        },
        example: (props) => <VerticalMosaic items={/* TODO */} />,
    }
);
