import React from 'react';
import {FunnelNavigationBar, MainNavigationBar, NavigationBar} from '../../navigation-bar';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
    FunnelNavigationBar,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=1953%3A8805',
    {
        props: {
            // These props were automatically mapped based on your linked code:
            variant: figma.enum('Theme variant', {
                Default: 'default',
                Inverse: 'inverse',
                Alternative: 'alternative',
            }),
            // No matching props could be found for these Figma properties:
            // "item1": figma.boolean('Item 1'),
            // "item2": figma.boolean('Item 2'),
            // "item3": figma.boolean('Item 3'),
            // "slot": figma.boolean('Slot')
        },
        example: (props) => <FunnelNavigationBar variant={props.variant} />,
    }
);

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
    MainNavigationBar,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=1953%3A8116',
    {
        props: {
            // These props were automatically mapped based on your linked code:
            variant: figma.enum('Theme variant', {
                Default: 'default',
                Inverse: 'inverse',
                Alternative: 'alternative',
            }),
            burgerMenuExtra: figma.enum('Menu', {
                False: false,
                True: true,
            }),
            desktopLargeMenu: figma.boolean('Menu'),
            // No matching props could be found for these Figma properties:
            // "slot": figma.instance('Slot →')
        },
        example: (props) => (
            <MainNavigationBar
                variant={props.variant}
                burgerMenuExtra={props.burgerMenuExtra}
                desktopLargeMenu={props.desktopLargeMenu}
            />
        ),
    }
);

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
    NavigationBar,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=1953%3A9656',
    {
        props: {
            // These props were automatically mapped based on your linked code:
            variant: figma.enum('Theme variant', {
                Default: 'default',
                Inverse: 'inverse',
                Alternative: 'alternative',
            }),
            // No matching props could be found for these Figma properties:
            // "item1": figma.boolean('Item 1'),
            // "item2": figma.boolean('Item 2'),
            // "item3": figma.boolean('Item 3'),
            // "back": figma.boolean('Back'),
            // "slot": figma.boolean('Slot')
        },
        example: (props) => <NavigationBar variant={props.variant} />,
    }
);
