import React from 'react';
import NavigationBreadcrumbs from '../../navigation-breadcrumbs';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    NavigationBreadcrumbs,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=4448%3A8247',
    {
        props: {
            themeContext: figma.enum('Theme context', {
                Default: 'default',
                Inverse: 'inverse',
            }),
            levelsOfNavigation: figma.enum('Levels of navigation', {
                '1': '1',
                '2': '2',
                '3': '3',
                '4': '4',
            }),
        },
        example: (props) => <NavigationBreadcrumbs />,
    }
);
