import React from 'react';
import PinField from '../../pin-field';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    PinField,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=27757%3A1753',
    {
        props: {
            helperText: figma.boolean('Helper text'),
            pin: figma.string('Pin'),
            themeContext: figma.enum('Theme Context', {
                Inverse: 'inverse',
                Default: 'default',
            }),
            state: figma.enum('State', {
                Focused: 'focused',
                Activated: 'activated',
            }),
            length: figma.enum('Length', {
                '6': '6',
                '5': '5',
                '4': '4',
                '3': '3',
                '2': '2',
            }),
            error: figma.boolean('Error'),
            disabled: figma.boolean('Disabled'),
            readOnly: figma.boolean('Read only'),
            hidePin: figma.boolean('Hide Pin'),
        },
        example: (props) => <PinField />,
    }
);
