import React from 'react';
import Popover from '../../popover';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Popover,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=809%3A6216',
    {
        props: {
            asset: figma.boolean('Asset'),
            title: figma.boolean('Title'),
            description: figma.boolean('Description'),
            slotOnlyWeb: figma.boolean('Slot (Only web)'),
            replaceSlot: figma.instance('🔄 Replace Slot'),
            position: figma.enum('Position', {
                Left: 'left',
                Right: 'right',
                Bottom: 'bottom',
                Top: 'top',
            }),
        },
        example: (props) => <Popover />,
    }
);
