import React from 'react';
import {ProgressBar} from '../../progress-bar';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    ProgressBar,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=571%3A7442',
    {
        props: {
            reverse: figma.boolean('Reverse'),
            themeContext: figma.enum('Theme context', {
                Inverse: 'inverse',
                Default: 'default',
            }),
            progress: figma.enum('Progress', {
                '0%': '0-',
                '10%': '10-',
                '20%': '20-',
                '30%': '30-',
                '40%': '40-',
                '50%': '50-',
                '60%': '60-',
                '70%': '70-',
                '80%': '80-',
                '90%': '90-',
                '100%': '100-',
            }),
        },
        example: (props) => <ProgressBar />,
    }
);
