import React from 'react';
import RadioButton from '../../radio-button';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
    RadioButton,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=1952%3A7125',
    {
        props: {
            // No matching props could be found for these Figma properties:
            // "themeContext": figma.enum('Theme context', {
            //   "Brand": "brand",
            //   "Default": "default"
            // }),
            // "state": figma.boolean('State'),
            // "disabled": figma.boolean('Disabled')
        },
        example: (props) => <RadioButton value={/* TODO */} render={/* TODO */} />,
    }
);
