import React from 'react';
import {Rating} from '../../rating';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Rating,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=42108%3A8419',
    {
        props: {
            themeContext: figma.enum('Theme context', {
                Inverse: 'inverse',
                Default: 'default',
            }),
            type: figma.enum('Type', {
                Quantitative: 'quantitative',
                Qualititative: 'qualititative',
            }),
            disabled: figma.boolean('Disabled'),
        },
        example: (props) => <Rating />,
    }
);
