import React from 'react';
import SheetWeb from '../../sheet-web';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    SheetWeb,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=10854%3A7964',
    {
        props: {
            protoGuide: figma.boolean('PROTO GUIDE'),
            hideSheetForPrototyping: figma.boolean('Hide sheet (for prototyping)'),
        },
        example: (props) => <SheetWeb />,
    }
);
