import React from 'react';
import {SkeletonCircle, SkeletonLine, SkeletonRectangle, SkeletonRow, SkeletonText} from '../../skeletons';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
    SkeletonCircle,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=16075%3A9337',
    {
        props: {
            // No matching props could be found for these Figma properties:
            // "themeContext": figma.enum('Theme context', {
            //   "Default": "default",
            //   "Brand": "brand"
            // })
        },
        example: (props) => <SkeletonCircle />,
    }
);

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
    SkeletonLine,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=16075%3A9335',
    {
        props: {
            // No matching props could be found for these Figma properties:
            // "themeContext": figma.enum('Theme context', {
            //   "Default": "default",
            //   "Brand": "brand"
            // })
        },
        example: (props) => <SkeletonLine />,
    }
);

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
    SkeletonRectangle,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=16075%3A9338',
    {
        props: {
            // These props were automatically mapped based on your linked code:
            noBorderRadius: figma.boolean('No border radius'),
            // No matching props could be found for these Figma properties:
            // "themeContext": figma.enum('Theme context', {
            //   "Default": "default",
            //   "Brand": "brand"
            // })
        },
        example: (props) => <SkeletonRectangle noBorderRadius={props.noBorderRadius} />,
    }
);

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
    SkeletonRow,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=16075%3A9336',
    {
        props: {
            // No matching props could be found for these Figma properties:
            // "themeContext": figma.enum('Theme context', {
            //   "Default": "default",
            //   "Brand": "brand"
            // })
        },
        example: (props) => <SkeletonRow />,
    }
);

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
    SkeletonText,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=16075%3A9334',
    {
        props: {
            // No matching props could be found for these Figma properties:
            // "themeContext": figma.enum('Theme context', {
            //   "Default": "default",
            //   "Brand": "brand"
            // })
        },
        example: (props) => <SkeletonText />,
    }
);
