import React from 'react';
import Slider from '../../slider';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Slider,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=2373%3A8535',
    {
        props: {
            tooltip: figma.boolean('Tooltip'),
            themeContext: figma.enum('Theme context', {
                Inverse: 'inverse',
                Default: 'default',
            }),
            state: figma.enum('State', {
                Activated: 'activated',
                Pressed: 'pressed',
                Disabled: 'disabled',
                State6: 'state6',
                State5: 'state5',
                State4: 'state4',
            }),
        },
        example: (props) => <Slider />,
    }
);
