import React from 'react';
import Snackbar from '../../snackbar';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Snackbar,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=6102%3A8009',
    {
        props: {
            dismiss: figma.boolean('Dismiss'),
            type: figma.enum('Type', {
                Informative: 'informative',
                Critical: 'critical',
            }),
            action: figma.boolean('Action'),
            longAction: figma.boolean('Long action'),
            duration: figma.enum('Duration', {
                Default: 'default',
                Infinite: 'infinite',
            }),
        },
        example: (props) => <Snackbar />,
    }
);
