import React from 'react';
import Stepper from '../../stepper';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Stepper,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=1369%3A6481',
    {
        props: {
            steps: figma.enum('Steps', {
                '2': '2',
                '3': '3',
                '4': '4',
                '5': '5',
            }),
        },
        example: (props) => <Stepper />,
    }
);
