import React from 'react';
import SwitchComponent from '../../switch-component';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
    SwitchComponent,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=1952%3A7138',
    {
        props: {
            // These props were automatically mapped based on your linked code:
            disabled: figma.boolean('Disabled'),
            // No matching props could be found for these Figma properties:
            // "themeContext": figma.enum('Theme context', {
            //   "Brand": "brand",
            //   "Default": "default"
            // }),
            // "state": figma.boolean('State'),
            // "material3OnlyCss": figma.boolean('Material 3 (Only CSS)')
        },
        example: (props) => (
            <SwitchComponent name={/* TODO */} disabled={props.disabled} render={/* TODO */} />
        ),
    }
);
