import React from 'react';
import {Table} from '../../table';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Table,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=39455%3A1048',
    {
        props: {
            themeContext: figma.enum('Theme context', {
                Default: 'default',
                Inverse: 'inverse',
            }),
            collapseRows: figma.boolean('Collapse rows'),
            headers: figma.boolean('Headers'),
            boxed: figma.boolean('Boxed'),
            headerRow: figma.boolean('Header row'),
        },
        example: (props) => <Table />,
    }
);
