import React from 'react';
import Tabs from '../../tabs';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Tabs,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=571%3A6553',
    {
        props: {
            itemNumber: figma.enum('Item number', {
                '2': '2',
                '3': '3',
                '+3 (Scroll)': '-3--scroll-',
            }),
            icon: figma.boolean('Icon'),
            themeContext: figma.enum('Theme context', {
                Default: 'default',
                Inverse: 'inverse',
            }),
        },
        example: (props) => <Tabs />,
    }
);
