import React from 'react';
import TextLink from '../../text-link';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    TextLink,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=9511%3A6607',
    {
        props: {
            themeContext: figma.enum('Theme context', {
                Default: 'default',
                Inverse: 'inverse',
            }),
            state: figma.enum('State', {
                Default: 'default',
                Disabled: 'disabled',
            }),
            underline: figma.enum('Underline', {
                Always: 'always',
                onHover: 'onhover',
            }),
        },
        example: (props) => <TextLink />,
    }
);
