import React from 'react';
import Timeline from '../../timeline';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Timeline,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=49350%3A5116',
    {
        props: {
            event3: figma.boolean('Event 3'),
            event4: figma.boolean('Event 4'),
            event6: figma.boolean('Event 6'),
            event7: figma.boolean('Event 7'),
            event5: figma.boolean('Event 5'),
            event2: figma.boolean('Event 2'),
            themeVariant: figma.enum('Theme Variant', {
                Default: 'default',
                Alternative: 'alternative',
                Inverse: 'inverse',
            }),
            orientation: figma.enum('Orientation', {
                Vertical: 'vertical',
                Horizontal: 'horizontal',
            }),
            assets: figma.enum('Assets', {
                Dot: 'dot',
                Number: 'number',
                Icon: 'icon',
                'Icon circle': 'icon-circle',
            }),
        },
        example: (props) => <Timeline />,
    }
);
