import React from 'react';
import {Timer} from '../../timer';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Timer,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=38945%3A1300',
    {
        props: {
            days: figma.string('Days'),
            hours: figma.string('Hours'),
            minutes: figma.string('Minutes'),
            seconds: figma.string('Seconds'),
            themeContext: figma.enum('Theme context', {
                Default: 'default',
                Alternative: 'alternative',
                Inverse: 'inverse',
                Media: 'media',
            }),
            boxed: figma.boolean('Boxed'),
            maxValue: figma.enum('Max value', {
                Days: 'days',
                Hours: 'hours',
                Minutes: 'minutes',
                Seconds: 'seconds',
            }),
            minValue: figma.enum('Min value', {
                Seconds: 'seconds',
                Minutes: 'minutes',
                Hours: 'hours',
                Days: 'days',
            }),
        },
        example: (props) => <Timer />,
    }
);
