import React from 'react';
import {Title4} from '../../title';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Title4,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=23715%3A135',
    {
        props: {
            level: figma.instance('Level'),
            themeContext: figma.enum('Theme context', {
                Default: 'default',
                Inverse: 'inverse',
            }),
            right: figma.enum('Right', {
                None: 'none',
                'Icon button': 'icon-button',
                'Button link': 'button-link',
            }),
        },
        example: (props) => <Title4 />,
    }
);
