import React from 'react';
import Tooltip from '../../tooltip';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Tooltip,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=2147%3A7654',
    {
        props: {
            slot: figma.boolean('Slot'),
            replaceSlot: figma.instance('🔄 Replace Slot'),
            description: figma.boolean('Description'),
            descriptionText: figma.string('Description Text'),
            titleText: figma.string('Title Text'),
            title: figma.boolean('Title'),
            delay: figma.boolean('Delay'),
            arrowPosition: figma.enum('Arrow position', {
                '↑ Top': '--top',
                '→ Right': '--right',
                '↓ Bottom': '--bottom',
                '← Left': '--left',
            }),
        },
        example: (props) => <Tooltip />,
    }
);
