import React from 'react';
import Video from '../../video';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Video,
    'https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/M%C3%ADstica-Mobile?node-id=2615%3A8435',
    {
        props: {
            loop: figma.boolean('Loop'),
            muted: figma.boolean('Muted'),
            autoplay: figma.boolean('Autoplay'),
            type: figma.enum('Type', {
                'Aspect Ratio': 'aspect-ratio',
                Free: 'free',
            }),
            aspectRatio: figma.enum('Aspect Ratio', {
                '1:1': '1-1',
                '4:3': '4-3',
                '16:9': '16-9',
                '21:9': '21-9',
                '—': '-',
            }),
            borderRadius: figma.boolean('Border radius'),
        },
        example: (props) => <Video />,
    }
);
