// @flow
import {applyAlpha} from './utils';
import c from './colors/movistar';

// LAYOUT
export const PRIMARY = c.MOVISTAR_BLUE;
export const BACKGROUND_BRAND = c.MOVISTAR_BLUE;
export const BACKGROUND_BRAND_VARIATION = c.MOVISTAR_BLUE;
export const BACKGROUND_SPECIAL_0 = c.WHITE;
export const BACKGROUND_SPECIAL_1 = c.MOVISTAR_BLUE;
export const PRIMARY_DARK = c.MOVISTAR_BLUE_DARK;
export const ACCENT = c.MOVISTAR_GREEN;
export const DIVIDER = c.GREY_4;
export const DIVIDER_SPECIAL_0 = c.GREY_4;
export const DIVIDER_SPECIAL_1 = c.MOVISTAR_BLUE_LIGHT_60;

export const BACKGROUND = c.WHITE;
export const BACKGROUND_PROMO = c.PURPLE;
export const BACKGROUND_DARK = c.GREY_0;
export const BACKGROUND_ALTERNATIVE = c.GREY_5;
export const BACKGROUND_SELECTED_DARK = c.WHITE;
export const BACKGROUND_UNSELECTED_DARK = c.MOVISTAR_BLUE_LIGHT_30;
export const BACKGROUND_ACCENT = c.MOVISTAR_BLUE;
export const BACKGROUND_HEADING = c.MOVISTAR_BLUE;
export const LAYER_DECORATIONS = c.BLACK;
export const BACKGROUND_SKELETON = c.GREY_5;
export const BACKGROUND_SKELETON_DARK: string = applyAlpha(c.MOVISTAR_BLUE_DARK, 0.5);
export const BACKGROUND_OPACITY: string = applyAlpha(c.GREY_0, 0.6);
export const BACKGROUND_LOYALTY = c.MOVISTAR_PRIORITY;
export const BACKGROUND_SPECIAL = c.MOVISTAR_BLUE;
export const OVERSCROLL_COLOR_TOP = c.MOVISTAR_BLUE;
export const BACKGROUND_SPECIAL_BOTTOM = c.MOVISTAR_BLUE;
export const GRID_BUTTON_SPECIAL_1_HOVER = c.MOVISTAR_BLUE_LIGHT_60;

export const BACKGROUND_SHEET_BAR_TOP = c.WHITE;
export const BACKGROUND_SHEET_BAR_TOP_SPECIAL = c.MOVISTAR_BLUE;
export const ICN_SHEET_BAR_TOP = c.GREY_3;
export const ICN_SHEET_BAR_TOP_SPECIAL = c.MOVISTAR_BLUE_LIGHT_30;

// BORDERS
export const BORDER = c.GREY_3;
export const BORDER_SELECTED = c.MOVISTAR_GREEN;
export const BORDER_DARK = c.GREY_1;
export const BORDER_LIGHT = c.GREY_5;
export const BORDER_ALTERNATIVE = c.WHITE;
export const BORDER_SPECIAL_0 = c.GREY_3;

// TABS
export const TAB_SELECTED = c.MOVISTAR_BLUE;

// ITEM
export const ITEM_ACTIVE = c.GREY_5;
export const ITEM_HOVER = c.GREY_4;

// TEXT
export const TEXT_ACCENT = c.MOVISTAR_GREEN;
export const TEXT_PRIMARY = c.GREY_0;
export const TEXT_PRIMARY_SPECIAL = c.WHITE;
export const TEXT_PRIMARY_INVERSE = c.WHITE;
export const TEXT_SECONDARY = c.GREY_1;
export const TEXT_SECONDARY_DARK = c.GREY_2;
export const TEXT_GROUP_TITLE_LIST = c.GREY_0;
export const TEXT_HINT = c.GREY_1;
export const TEXT_LINK = c.MOVISTAR_BLUE;
export const TEXT_LINK_SNACKBAR = c.MOVISTAR_BLUE_LIGHT_60;
export const TEXT_CLICKABLE = TEXT_LINK;
export const TEXT_ERROR = c.PEPPER;
export const TEXT_HIGHLIGHT = c.PINK;
export const TEXT_LABEL = c.MOVISTAR_GREEN;
export const TEXT_INACTIVE = c.GREY_3;
export const TEXT_INACTIVE_INVERSE = c.MOVISTAR_BLUE_LIGHT_50;
export const TEXT_WARNING = c.EGG;
export const TEXT_DANGER = c.PINK;

// TAG
export const TAG_BACKGROUND_FIRST = c.MOVISTAR_GREEN;
export const TAG_BACKGROUND_SECOND = c.GREY_3;
export const TAG_BACKGROUND_THIRD = c.MOVISTAR_BLUE;
export const TAG_BACKGROUND_FOURTH = c.EGG;
export const TAG_BACKGROUND_FIFTH = c.MOVISTAR_BLUE_DARK;
export const TAG_BACKGROUND_SIXTH = c.PURPLE;
export const TAG_BACKGROUND_SEVENTH = c.PINK;

// ICON
export const ICON_ACCENT = c.MOVISTAR_GREEN;
export const ICON_NAVIGATION_BAR = c.WHITE;
export const ICON_INVERSE_DISABLE: string = applyAlpha(c.WHITE, 0.5);
export const ICON_INACTIVE = c.GREY_1;
export const ICON_PRIMARY = c.GREY_0;
export const ICON_SECONDARY = c.GREY_2;
export const ICON_SECONDARY_SPECIAL_0 = c.GREY_2;
export const ICON_TERTIARY = c.MOVISTAR_BLUE;
export const ICON_INVERSE = c.WHITE;
export const ICON_DISABLED = c.GREY_3;
export const ICON_DANGER = c.PEPPER;
export const ICON_PLACEHOLDER = c.GREY_4;
export const ICON_HEADER = c.GREY_3;
export const ICON_HIGHLIGHT = c.PINK;

// BUTTONS
export const BUTTON_PRIMARY_BACKGROUND = c.MOVISTAR_GREEN;
export const BUTTON_PRIMARY_BACKGROUND_SELECTED = c.MOVISTAR_GREEN_DARK;
export const BUTTON_PRIMARY_BACKGROUND_HOVER = c.MOVISTAR_GREEN_DARK;
export const BUTTON_PRIMARY_BACKGROUND_DISABLED = c.MOVISTAR_GREEN_LIGHT_50;
export const BUTTON_PRIMARY_TEXT = c.WHITE;

export const BUTTON_PRIMARY_BACKGROUND_INVERSE = c.WHITE;
export const TEXT_BUTTON_PRIMARY_INVERSE = c.MOVISTAR_BLUE;
export const BUTTON_PRIMARY_BACKGROUND_INVERSE_SELECTED = c.MOVISTAR_BLUE_LIGHT_60;
export const TEXT_BUTTON_PRIMARY_INVERSE_SELECTED = c.MOVISTAR_BLUE;
export const BUTTON_PRIMARY_BACKGROUND_INVERSE_DISABLED = c.MOVISTAR_BLUE_LIGHT_60;
export const TEXT_BUTTON_PRIMARY_INVERSE_DISABLED = c.MOVISTAR_BLUE_LIGHT_30;

export const BUTTON_SECONDARY_BACKGROUND = 'transparent';
export const BUTTON_SECONDARY_TEXT = c.MOVISTAR_GREEN;
export const BUTTON_SECONDARY_TEXT_SELECTED = c.MOVISTAR_GREEN_DARK;
export const BUTTON_SECONDARY_TEXT_DISABLED = c.MOVISTAR_GREEN_LIGHT_50;
export const BUTTON_SECONDARY_BORDER = c.MOVISTAR_GREEN;
export const BUTTON_SECONDARY_BORDER_SELECTED = c.MOVISTAR_GREEN_DARK;
export const BUTTON_SECONDARY_BORDER_DISABLED = c.MOVISTAR_GREEN_LIGHT_50;

export const BUTTON_SECONDARY_BORDER_INVERSE = c.WHITE;
export const TEXT_BUTTON_SECONDARY_INVERSE = c.WHITE;
export const BUTTON_SECONDARY_BORDER_INVERSE_SELECTED = c.MOVISTAR_BLUE_LIGHT_60;
export const TEXT_BUTTON_SECONDARY_INVERSE_SELECTED = c.WHITE;
export const BUTTON_SECONDARY_BORDER_INVERSE_DISABLED = c.MOVISTAR_BLUE_LIGHT_60;
export const TEXT_BUTTON_SECONDARY_INVERSE_DISABLED = c.MOVISTAR_BLUE_LIGHT_50;

export const BUTTON_TERTIARY_BACKGROUND = c.GREY_4;

export const BUTTON_DANGER_BACKGROUND = c.PEPPER;
export const BUTTON_DANGER_BACKGROUND_SELECTED = c.PEPPER_DARK;
export const BUTTON_DANGER_BACKGROUND_HOVER = c.PEPPER_DARK;
export const BUTTON_DANGER_BACKGROUND_DISABLED = c.PEPPER_LIGHT;

export const BUTTON_LINK_BACKGROUND_SELECTED = '#e5f6fb'; // No palette constant?

// AVATAR BUTTONS

// FEEDBACKS
export const FEEDBACK_SUCCESS_BACKGROUND = c.MOVISTAR_GREEN_DARK;
export const FEEDBACK_SYSTEM_BACKGROUND = c.GREY_1;
export const FEEDBACK_INFO_BACKGROUND = c.GREY_0;
export const FEEDBACK_ERROR_BACKGROUND = c.PEPPER;
export const FEEDBACK_PERMANENT_BORDER = c.EGG;

// FORM CONTROLS - https://app.zeplin.io/project/5a81c7fc94d98154381bec44/screen/5c6a96a14b2e4246345bc2a6
export const CONTROL_INACTIVE = c.GREY_3;
export const CONTROL_ACTIVE = c.MOVISTAR_BLUE;
export const CONTROL_ERROR = c.PEPPER;
export const CONTROL_HOVER = c.GREY_1;

export const CONTROL_SPECIAL_0_ACTIVE = c.MOVISTAR_BLUE;
export const CONTROL_SPECIAL_0_INACTIVE = c.GREY_3;
export const CONTROL_INVERSE_ACTIVE = c.WHITE;
export const CONTROL_INVERSE_INACTIVE: string = applyAlpha(c.WHITE, 0.3);

// TOGGLE
export const TOGGLE_ANDROID_INACTIVE = CONTROL_INACTIVE;
export const TOGGLE_ANDROID_BACKGROUND_INACTIVE = c.GREY_4;
export const TOGGLE_ANDROID_ACTIVE = c.MOVISTAR_BLUE;
export const TOGGLE_ANDROID_BACKGROUND_ACTIVE = c.MOVISTAR_BLUE_LIGHT_60;
export const TOGGLE_IOS_INACTIVE = c.WHITE;
export const TOGGLE_IOS_BACKGROUND_INACTIVE = c.GREY_3;
export const TOGGLE_IOS_BACKGROUND_ACTIVE = c.MOVISTAR_BLUE;

// CHARTS
export const PROGRESS_CHART_0 = c.MOVISTAR_GREEN;
export const PROGRESS_CHART_1 = c.MOVISTAR_GREEN_DARK;
export const PROGRESS_CHART_2 = c.MOVISTAR_GREEN_LIGHT_50;
export const PROGRESS_CHART_3 = c.EGG;
export const PROGRESS_CHART_4 = c.EGG_LIGHT;
export const PROGRESS_CHART_5 = c.PINK;
export const PROGRESS_CHART_6 = c.MOVISTAR_GREEN_LIGHT_50;

export const CHART_SECONDARY_LIGHT = c.MOVISTAR_BLUE_LIGHT_30;
export const CHART_SECONDARY_DARK = c.MOVISTAR_BLUE;
export const CHART_TERTIARY_LIGHT = c.GREY_4;
export const CHART_TERTIARY_DARK = c.GREY_3;
export const CHART_SPECIAL_DARK = c.EGG;

export const BAR_CHART_INACTIVE = c.GREY_3;
export const BAR_CHART_INACTIVE_DARK = c.MOVISTAR_BLUE_LIGHT_60;
export const BAR_CHART_ACTIVE = c.MOVISTAR_BLUE;
export const BAR_CHART_ACTIVE_DARK = c.WHITE;
export const CHART_LABEL_INACTIVE = c.GREY_3;
export const CHART_LABEL_INACTIVE_DARK = c.MOVISTAR_BLUE_LIGHT_50;
export const CHART_LABEL_ACTIVE = c.GREY_1;
export const CHART_LABEL_ACTIVE_DARK = BACKGROUND;

export const BAR_CHART_0 = c.MOVISTAR_BLUE;
export const BAR_CHART_1 = c.MOVISTAR_GREEN;
export const BAR_CHART_2 = c.EGG;
export const BAR_CHART_3 = c.PINK;
export const BAR_CHART_4 = c.PURPLE;

export const BRANCH = c.GREY_4;
export const CHART_BACKGROUND = c.GREY_4;
export const CHART_BACKGROUND_TOOLTIP = c.GREY_4;
export const CHART_BACKGROUND_SPECIAL_0 = c.GREY_4;
export const CHART_TEXT_AMOUNT = c.MOVISTAR_BLUE;

export const STAKED_BAR_CHART_0 = c.MOVISTAR_BLUE;
export const STAKED_BAR_CHART_1 = c.MOVISTAR_BLUE_LIGHT_50;
export const STAKED_BAR_CHART_2 = c.MOVISTAR_GREEN_DARK;
export const STAKED_BAR_CHART_3 = c.EGG;
export const STAKED_BAR_CHART_4 = c.PURPLE;
export const STAKED_BAR_CHART_5 = c.PINK;
export const STAKED_BAR_CHART_6 = c.MOVISTAR_GREEN_LIGHT_50;

// PROGRESS BAR
export const PROGRESSBAR_BACKGROUND_DARK = c.GREY_2;
export const PROGRESSBAR_INNER = ACCENT;

// MAIN NAVIGATION
export const MAIN_NAV_PRIMARY = PRIMARY_DARK;
export const MAIN_NAV_PRIMARY_HOME = c.MOVISTAR_BLUE;
export const NAVIGATION_BAR_BACKGROUND = c.MOVISTAR_BLUE;
export const MAIN_NAV_NOTIFICATION = c.WHITE;
export const MAIN_NAV_ITEM_INACTIVE = c.MOVISTAR_BLUE_LIGHT_50;
export const MAIN_NAV_ITEM_ACTIVE = c.WHITE;

// SECONDARY NAVIGATION TABLET AND MOBILE
export const NAVTAB_IOS_BACKGROUND = c.WHITE;
export const NAVTAB_IOS_BORDER = c.MOVISTAR_BLUE;
export const NAVTAB_IOS_ACTIVE_TAB_BACKGROUND = c.MOVISTAR_BLUE;
export const NAVTAB_ANDROID_BACKGROUND = c.GREY_5;
export const NAVTAB_ANDROID_ACTIVE_TAB_BACKGROUND = c.GREY_5;
export const NAVTAB_ANDROID_ACTIVE_TAB_BORDER = ACCENT;
export const NAVTAB_PRIMARY_TEXT = c.GREY_0;
export const NAVTAB_IOS_ACTIVE_TEXT = c.WHITE;
export const NAVTAB_IOS_INACTIVE_TEXT = c.MOVISTAR_BLUE;
export const NAVTAB_ANDROID_ACTIVE_TEXT = c.GREY_0;
export const NAVTAB_ANDROID_INACTIVE_TEXT = c.GREY_1;

// BUBBLES
export const BUBBLE_FROM_ME_BACKGROUND = c.GREY_4;
export const BUBBLE_FROM_OTHERS_BACKGROUND = c.MOVISTAR_GREEN_LIGHT_30;
export const BUBBLE_TEXT = '#191919';

// AUDIO WAVES
export const WAVE_PLAYER_SOUND = c.GREY_3;
export const WAVE_PLAYER_SOUND_FILLED = c.MOVISTAR_BLUE_LIGHT_50;

// ALERTS
export const BACKGROUND_TRANSACTIONAL_ALERT = c.MOVISTAR_BLUE;

// SHADOWS
export const CONTAINER_SHADOW = c.GREY_0;

// PROGRESS INDICATOR
export const LOADING_BAR_PRIMARY = c.MOVISTAR_GREEN;
export const LOADING_BAR_BACKGROUND = c.MOVISTAR_GREEN_LIGHT_50;
export const LOADING_BAR_PRIMARY_INVERSE = c.MOVISTAR_BLUE_LIGHT_60;
export const LOADING_BAR_BACKGROUND_INVERSE = c.MOVISTAR_BLUE_DARK;

// BADGE
export const BADGE_BACKGROUND = c.PEPPER_DARK;
