name: 'Upload failed screenshot diffs'
description: 'This action uploads diff pngs to the cloud and returns image URLs'

inputs:
    azure-account-name:
        description: 'Azure Account Name'
        required: true
    azure-account-key:
        description: 'Azure Account Key'
        required: true

outputs:
    uploads:
        description: 'TBD'

runs:
    using: 'node12'
    main: 'main.js'

branding:
    # https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#branding
    # https://haya14busa.github.io/github-action-brandings/
    icon: 'upload-cloud'
    color: 'green'
