// flow-typed signature: 90ea92d88684a763c3655736e2112468
// flow-typed version: <<STUB>>/@storybook/components_v5.3.19/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/components/dist/ActionBar/ActionBar' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/ActionBar/ActionBar.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/addon-panel/addon-panel' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/Badge/Badge' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/Badge/Badge.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/bar/bar' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/bar/button' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/bar/separator' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/blocks/BlockBackgroundStyles' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/blocks/ColorPalette' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/blocks/ColorPalette.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/blocks/Description' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/blocks/Description.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/blocks/DocsPage' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/blocks/DocsPage.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/blocks/EmptyBlock' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/blocks/EmptyBlock.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/blocks/IconGallery' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/blocks/IconGallery.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/blocks/IFrame' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/blocks' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/blocks/Preview' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/blocks/Preview.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/blocks/PropsTable/PropDef' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/blocks/PropsTable/PropJsDoc' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/blocks/PropsTable/PropRow' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/blocks/PropsTable/PropRow.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/blocks/PropsTable/PropsTable' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/blocks/PropsTable/PropsTable.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/blocks/PropsTable/PropValue' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/blocks/PropsTable/SectionRow' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/blocks/PropsTable/SectionRow.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/blocks/Source' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/blocks/Source.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/blocks/Story' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/blocks/Story.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/blocks/Toolbar' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/blocks/Typeset' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/blocks/Typeset.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/blocks/ZoomContext' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/brand/StorybookIcon' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/brand/StorybookIcon.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/brand/StorybookLogo' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/brand/StorybookLogo.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/Button/Button' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/Button/Button.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/form/field/field' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/form/form.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/form' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/form/input/input' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/html' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/icon/icon' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/icon/icon.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/icon/icons' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/icon/svg' {
  declare module.exports: any;
}

declare module '@storybook/components/dist' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/placeholder/placeholder' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/placeholder/placeholder.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/ScrollArea/ScrollArea' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/ScrollArea/ScrollArea.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/ScrollArea/ScrollAreaStyles' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/spaced/Spaced' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/spaced/Spaced.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/syntaxhighlighter/formatter' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/syntaxhighlighter/syntaxhighlighter' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/syntaxhighlighter/syntaxhighlighter.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/tabs/tabs' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/tabs/tabs.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/tooltip/ListItem' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/tooltip/ListItem.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/tooltip/Tooltip' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/tooltip/Tooltip.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/tooltip/TooltipLinkList' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/tooltip/TooltipLinkList.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/tooltip/TooltipMessage' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/tooltip/TooltipMessage.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/tooltip/TooltipNote' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/tooltip/TooltipNote.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/tooltip/WithTooltip' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/tooltip/WithTooltip.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/typings.d' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/typography/DocumentFormatting' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/typography/DocumentWrapper' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/typography/DocumentWrapper.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/typography/link/link' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/typography/link/link.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/typography/shared' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/typography/typography.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/html' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/components/dist/ActionBar/ActionBar.js' {
  declare module.exports: $Exports<'@storybook/components/dist/ActionBar/ActionBar'>;
}
declare module '@storybook/components/dist/ActionBar/ActionBar.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/ActionBar/ActionBar.stories'>;
}
declare module '@storybook/components/dist/addon-panel/addon-panel.js' {
  declare module.exports: $Exports<'@storybook/components/dist/addon-panel/addon-panel'>;
}
declare module '@storybook/components/dist/Badge/Badge.js' {
  declare module.exports: $Exports<'@storybook/components/dist/Badge/Badge'>;
}
declare module '@storybook/components/dist/Badge/Badge.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/Badge/Badge.stories'>;
}
declare module '@storybook/components/dist/bar/bar.js' {
  declare module.exports: $Exports<'@storybook/components/dist/bar/bar'>;
}
declare module '@storybook/components/dist/bar/button.js' {
  declare module.exports: $Exports<'@storybook/components/dist/bar/button'>;
}
declare module '@storybook/components/dist/bar/separator.js' {
  declare module.exports: $Exports<'@storybook/components/dist/bar/separator'>;
}
declare module '@storybook/components/dist/blocks/BlockBackgroundStyles.js' {
  declare module.exports: $Exports<'@storybook/components/dist/blocks/BlockBackgroundStyles'>;
}
declare module '@storybook/components/dist/blocks/ColorPalette.js' {
  declare module.exports: $Exports<'@storybook/components/dist/blocks/ColorPalette'>;
}
declare module '@storybook/components/dist/blocks/ColorPalette.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/blocks/ColorPalette.stories'>;
}
declare module '@storybook/components/dist/blocks/Description.js' {
  declare module.exports: $Exports<'@storybook/components/dist/blocks/Description'>;
}
declare module '@storybook/components/dist/blocks/Description.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/blocks/Description.stories'>;
}
declare module '@storybook/components/dist/blocks/DocsPage.js' {
  declare module.exports: $Exports<'@storybook/components/dist/blocks/DocsPage'>;
}
declare module '@storybook/components/dist/blocks/DocsPage.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/blocks/DocsPage.stories'>;
}
declare module '@storybook/components/dist/blocks/EmptyBlock.js' {
  declare module.exports: $Exports<'@storybook/components/dist/blocks/EmptyBlock'>;
}
declare module '@storybook/components/dist/blocks/EmptyBlock.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/blocks/EmptyBlock.stories'>;
}
declare module '@storybook/components/dist/blocks/IconGallery.js' {
  declare module.exports: $Exports<'@storybook/components/dist/blocks/IconGallery'>;
}
declare module '@storybook/components/dist/blocks/IconGallery.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/blocks/IconGallery.stories'>;
}
declare module '@storybook/components/dist/blocks/IFrame.js' {
  declare module.exports: $Exports<'@storybook/components/dist/blocks/IFrame'>;
}
declare module '@storybook/components/dist/blocks/index' {
  declare module.exports: $Exports<'@storybook/components/dist/blocks'>;
}
declare module '@storybook/components/dist/blocks/index.js' {
  declare module.exports: $Exports<'@storybook/components/dist/blocks'>;
}
declare module '@storybook/components/dist/blocks/Preview.js' {
  declare module.exports: $Exports<'@storybook/components/dist/blocks/Preview'>;
}
declare module '@storybook/components/dist/blocks/Preview.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/blocks/Preview.stories'>;
}
declare module '@storybook/components/dist/blocks/PropsTable/PropDef.js' {
  declare module.exports: $Exports<'@storybook/components/dist/blocks/PropsTable/PropDef'>;
}
declare module '@storybook/components/dist/blocks/PropsTable/PropJsDoc.js' {
  declare module.exports: $Exports<'@storybook/components/dist/blocks/PropsTable/PropJsDoc'>;
}
declare module '@storybook/components/dist/blocks/PropsTable/PropRow.js' {
  declare module.exports: $Exports<'@storybook/components/dist/blocks/PropsTable/PropRow'>;
}
declare module '@storybook/components/dist/blocks/PropsTable/PropRow.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/blocks/PropsTable/PropRow.stories'>;
}
declare module '@storybook/components/dist/blocks/PropsTable/PropsTable.js' {
  declare module.exports: $Exports<'@storybook/components/dist/blocks/PropsTable/PropsTable'>;
}
declare module '@storybook/components/dist/blocks/PropsTable/PropsTable.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/blocks/PropsTable/PropsTable.stories'>;
}
declare module '@storybook/components/dist/blocks/PropsTable/PropValue.js' {
  declare module.exports: $Exports<'@storybook/components/dist/blocks/PropsTable/PropValue'>;
}
declare module '@storybook/components/dist/blocks/PropsTable/SectionRow.js' {
  declare module.exports: $Exports<'@storybook/components/dist/blocks/PropsTable/SectionRow'>;
}
declare module '@storybook/components/dist/blocks/PropsTable/SectionRow.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/blocks/PropsTable/SectionRow.stories'>;
}
declare module '@storybook/components/dist/blocks/Source.js' {
  declare module.exports: $Exports<'@storybook/components/dist/blocks/Source'>;
}
declare module '@storybook/components/dist/blocks/Source.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/blocks/Source.stories'>;
}
declare module '@storybook/components/dist/blocks/Story.js' {
  declare module.exports: $Exports<'@storybook/components/dist/blocks/Story'>;
}
declare module '@storybook/components/dist/blocks/Story.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/blocks/Story.stories'>;
}
declare module '@storybook/components/dist/blocks/Toolbar.js' {
  declare module.exports: $Exports<'@storybook/components/dist/blocks/Toolbar'>;
}
declare module '@storybook/components/dist/blocks/Typeset.js' {
  declare module.exports: $Exports<'@storybook/components/dist/blocks/Typeset'>;
}
declare module '@storybook/components/dist/blocks/Typeset.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/blocks/Typeset.stories'>;
}
declare module '@storybook/components/dist/blocks/ZoomContext.js' {
  declare module.exports: $Exports<'@storybook/components/dist/blocks/ZoomContext'>;
}
declare module '@storybook/components/dist/brand/StorybookIcon.js' {
  declare module.exports: $Exports<'@storybook/components/dist/brand/StorybookIcon'>;
}
declare module '@storybook/components/dist/brand/StorybookIcon.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/brand/StorybookIcon.stories'>;
}
declare module '@storybook/components/dist/brand/StorybookLogo.js' {
  declare module.exports: $Exports<'@storybook/components/dist/brand/StorybookLogo'>;
}
declare module '@storybook/components/dist/brand/StorybookLogo.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/brand/StorybookLogo.stories'>;
}
declare module '@storybook/components/dist/Button/Button.js' {
  declare module.exports: $Exports<'@storybook/components/dist/Button/Button'>;
}
declare module '@storybook/components/dist/Button/Button.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/Button/Button.stories'>;
}
declare module '@storybook/components/dist/form/field/field.js' {
  declare module.exports: $Exports<'@storybook/components/dist/form/field/field'>;
}
declare module '@storybook/components/dist/form/form.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/form/form.stories'>;
}
declare module '@storybook/components/dist/form/index' {
  declare module.exports: $Exports<'@storybook/components/dist/form'>;
}
declare module '@storybook/components/dist/form/index.js' {
  declare module.exports: $Exports<'@storybook/components/dist/form'>;
}
declare module '@storybook/components/dist/form/input/input.js' {
  declare module.exports: $Exports<'@storybook/components/dist/form/input/input'>;
}
declare module '@storybook/components/dist/html.js' {
  declare module.exports: $Exports<'@storybook/components/dist/html'>;
}
declare module '@storybook/components/dist/icon/icon.js' {
  declare module.exports: $Exports<'@storybook/components/dist/icon/icon'>;
}
declare module '@storybook/components/dist/icon/icon.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/icon/icon.stories'>;
}
declare module '@storybook/components/dist/icon/icons.js' {
  declare module.exports: $Exports<'@storybook/components/dist/icon/icons'>;
}
declare module '@storybook/components/dist/icon/svg.js' {
  declare module.exports: $Exports<'@storybook/components/dist/icon/svg'>;
}
declare module '@storybook/components/dist/index' {
  declare module.exports: $Exports<'@storybook/components/dist'>;
}
declare module '@storybook/components/dist/index.js' {
  declare module.exports: $Exports<'@storybook/components/dist'>;
}
declare module '@storybook/components/dist/placeholder/placeholder.js' {
  declare module.exports: $Exports<'@storybook/components/dist/placeholder/placeholder'>;
}
declare module '@storybook/components/dist/placeholder/placeholder.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/placeholder/placeholder.stories'>;
}
declare module '@storybook/components/dist/ScrollArea/ScrollArea.js' {
  declare module.exports: $Exports<'@storybook/components/dist/ScrollArea/ScrollArea'>;
}
declare module '@storybook/components/dist/ScrollArea/ScrollArea.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/ScrollArea/ScrollArea.stories'>;
}
declare module '@storybook/components/dist/ScrollArea/ScrollAreaStyles.js' {
  declare module.exports: $Exports<'@storybook/components/dist/ScrollArea/ScrollAreaStyles'>;
}
declare module '@storybook/components/dist/spaced/Spaced.js' {
  declare module.exports: $Exports<'@storybook/components/dist/spaced/Spaced'>;
}
declare module '@storybook/components/dist/spaced/Spaced.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/spaced/Spaced.stories'>;
}
declare module '@storybook/components/dist/syntaxhighlighter/formatter.js' {
  declare module.exports: $Exports<'@storybook/components/dist/syntaxhighlighter/formatter'>;
}
declare module '@storybook/components/dist/syntaxhighlighter/syntaxhighlighter.js' {
  declare module.exports: $Exports<'@storybook/components/dist/syntaxhighlighter/syntaxhighlighter'>;
}
declare module '@storybook/components/dist/syntaxhighlighter/syntaxhighlighter.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/syntaxhighlighter/syntaxhighlighter.stories'>;
}
declare module '@storybook/components/dist/tabs/tabs.js' {
  declare module.exports: $Exports<'@storybook/components/dist/tabs/tabs'>;
}
declare module '@storybook/components/dist/tabs/tabs.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/tabs/tabs.stories'>;
}
declare module '@storybook/components/dist/tooltip/ListItem.js' {
  declare module.exports: $Exports<'@storybook/components/dist/tooltip/ListItem'>;
}
declare module '@storybook/components/dist/tooltip/ListItem.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/tooltip/ListItem.stories'>;
}
declare module '@storybook/components/dist/tooltip/Tooltip.js' {
  declare module.exports: $Exports<'@storybook/components/dist/tooltip/Tooltip'>;
}
declare module '@storybook/components/dist/tooltip/Tooltip.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/tooltip/Tooltip.stories'>;
}
declare module '@storybook/components/dist/tooltip/TooltipLinkList.js' {
  declare module.exports: $Exports<'@storybook/components/dist/tooltip/TooltipLinkList'>;
}
declare module '@storybook/components/dist/tooltip/TooltipLinkList.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/tooltip/TooltipLinkList.stories'>;
}
declare module '@storybook/components/dist/tooltip/TooltipMessage.js' {
  declare module.exports: $Exports<'@storybook/components/dist/tooltip/TooltipMessage'>;
}
declare module '@storybook/components/dist/tooltip/TooltipMessage.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/tooltip/TooltipMessage.stories'>;
}
declare module '@storybook/components/dist/tooltip/TooltipNote.js' {
  declare module.exports: $Exports<'@storybook/components/dist/tooltip/TooltipNote'>;
}
declare module '@storybook/components/dist/tooltip/TooltipNote.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/tooltip/TooltipNote.stories'>;
}
declare module '@storybook/components/dist/tooltip/WithTooltip.js' {
  declare module.exports: $Exports<'@storybook/components/dist/tooltip/WithTooltip'>;
}
declare module '@storybook/components/dist/tooltip/WithTooltip.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/tooltip/WithTooltip.stories'>;
}
declare module '@storybook/components/dist/typings.d.js' {
  declare module.exports: $Exports<'@storybook/components/dist/typings.d'>;
}
declare module '@storybook/components/dist/typography/DocumentFormatting.js' {
  declare module.exports: $Exports<'@storybook/components/dist/typography/DocumentFormatting'>;
}
declare module '@storybook/components/dist/typography/DocumentWrapper.js' {
  declare module.exports: $Exports<'@storybook/components/dist/typography/DocumentWrapper'>;
}
declare module '@storybook/components/dist/typography/DocumentWrapper.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/typography/DocumentWrapper.stories'>;
}
declare module '@storybook/components/dist/typography/link/link.js' {
  declare module.exports: $Exports<'@storybook/components/dist/typography/link/link'>;
}
declare module '@storybook/components/dist/typography/link/link.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/typography/link/link.stories'>;
}
declare module '@storybook/components/dist/typography/shared.js' {
  declare module.exports: $Exports<'@storybook/components/dist/typography/shared'>;
}
declare module '@storybook/components/dist/typography/typography.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/typography/typography.stories'>;
}
declare module '@storybook/components/html.js' {
  declare module.exports: $Exports<'@storybook/components/html'>;
}
