name: Unpublish
on:
    workflow_dispatch:
        inputs:
            version:
                description: 'version to unpublish'
                required: true
jobs:
    release:
        name: Unpublish
        runs-on: ubuntu-latest
        steps:
            - name: 'Set npm token'
              uses: './.github/actions/set-npm-token'
              with:
                  npm-token: ${{ secrets.NPM_PUBLISH_TOKEN }}

            - name: Unpublish npm package version
              env:
                  GITHUB_TOKEN: ${{ secrets.FLOW_GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
              run: npm unpublish @telefonica/mistica@${{ github.event.inputs.version }}
