name: update_screenshots

on:
    workflow_dispatch:
        inputs:
            branch:
                description: 'Branch name'
                required: true
                default: ''

jobs:
    update-screenshots:
        name: update-screenshots
        runs-on: [self-hosted, cdorunner-life-novum, Linux, cdorunner-life-large]
        container: telefonica/web-builder:chromium93.0.4577-node24-1.0.0
        strategy:
            matrix:
                shard: [1, 2, 3]
            fail-fast: false
        env:
            ACTION_INPUT_BRANCH: ${{github.event.inputs.branch || 'master'}}
        steps:
            - name: checkout
              uses: actions/checkout@v4
              with:
                  token: ${{secrets.FLOW_GITHUB_TOKEN}}
                  ref: ${{github.event.inputs.branch}}
            - name: Install dependencies
              env:
                  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
              run: yarn install --immutable --immutable-cache

            - run: yarn storybook-static
            - run: yarn test-acceptance -u --ci --shard=${{ matrix.shard }}/${{ strategy.job-total }}

            - name: commit-changes
              run: |
                  git status --porcelain
                  if [ ! -z "$(git status --porcelain)" ]; then
                    git config --global user.name ${GITHUB_ACTOR}
                    git config --global user.email ${GITHUB_ACTOR}@users.noreply.github.com
                    git add -A
                    git commit -m "[bot] Update screenshots"
                    git push origin HEAD:$ACTION_INPUT_BRANCH
                  else
                    echo "No changes to commit"
                  fi
